(() => {
'use strict';
const $ = id => document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false}),images={};
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const chapters=[
 {id:'south-vale',name:'SOUTH VALE',line:'Follow the road beyond the fog.',areas:['THE EMPTY STREETS','THE SHOPPING DISTRICT','THE APARTMENT GATE'],accent:'#bac8b5'},
 {id:'apartments',name:'WOOD SIDE APARTMENTS',line:'Something is moving behind the doors.',areas:['THE WEST CORRIDOR','THE SILENT ROOMS','THE EAST STAIRWELL'],accent:'#c4b887'},
 {id:'hospital',name:'BROOKHAVEN HOSPITAL',line:'The radio will not stop.',areas:['THE RECEPTION HALL','THE TREATMENT WARD','THE LOCKED EXIT'],accent:'#bbd0b9'},
 {id:'prison',name:'TOLUCA PRISON',line:'Every passage leads deeper.',areas:['THE CELL BLOCK','THE GALLOWS CORRIDOR','THE LABYRINTH'],accent:'#d1a27b'},
 {id:'hotel',name:'LAKEVIEW HOTEL',line:'One last shadow stands between you and the truth.',areas:['THE HOTEL LOBBY','THE LAKE WING','THE FINAL CONFRONTATION'],accent:'#caaea0'}
];
const AREA=900,END=AREA*3,MAX_HP=100,MAG=8,SAVE='sh2-brawler-checkpoint-v1';
const PLAYER_HEIGHT=181,SHOT_MUZZLE={x:525,y:189};
const ui={menu:$('menu'),primary:$('primaryButton'),label:$('primaryLabel'),help:$('helpButton'),cont:$('continueButton'),home:$('mainMenuButton'),helpContent:$('helpContent')};
let W=1280,H=720,DPR=1,scale=1,VW=1280,VH=680,ground=410,ready=false,loadingError=false;
let state='main',helpOrigin='main',chapter=0,area=0,p=null,enemies=[],props=[],projectiles=[],particles=[],floaters=[],camera=0,shake=0,simTime=0,presentation=0;
let checkpoint=null,save=null,score=0,combo=0,comboLife=0,chain=0,chainLife=0,clearAnnounced=false,intro=0,toastTime=0,hitstop=0,transition=null,runStarted=false,deathTime=0;
let stick={x:0,y:0,id:null},keys=new Set(),touchHeld=new Set(),touchMode=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0,last=0,hudTick=0;
let audio=null,master=null,muted=false;
try{save=JSON.parse(localStorage.getItem(SAVE)||'null');muted=localStorage.getItem('sh2-muted')==='1';if(!save||save.version!==1||!Number.isInteger(save.chapter)||save.chapter<0||save.chapter>4||!Number.isFinite(save.hp)||!Number.isFinite(save.reserve)||!Number.isFinite(save.score))save=null;}catch{save=null;}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);VH=W/H<.8?950:680;scale=H/VH;VW=W/scale;ground=VH*.60;ctx.imageSmoothingEnabled=false;}
addEventListener('resize',resize);resize();
function sound(type){if(muted)return;try{if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.3;master.connect(audio.destination);}if(audio.state==='suspended')audio.resume();const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(master);let f=170,len=.1,vol=.12,kind='triangle';if(type==='hit'){f=95;len=.12;vol=.21;kind='sawtooth';}if(type==='heavy'){f=65;len=.22;vol=.22;kind='sawtooth';}if(type==='shoot'){f=230;len=.15;vol=.3;kind='square';}if(type==='hurt'){f=60;len=.25;vol=.13;kind='sawtooth';}if(type==='pickup'){f=600;len=.22;vol=.12;}if(type==='reload'){f=380;len=.1;kind='square';vol=.08;}if(type==='dodge'){f=145;len=.18;vol=.07;}if(type==='clear'){f=330;len=.6;vol=.10;}o.type=kind;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(type==='pickup'?1100:Math.max(25,f*.32),t+len);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+len);o.start(t);o.stop(t+len+.02);}catch{}}
function unlockAudio(){sound('reload');}
function syncMute(){$('muteButton').textContent=muted?'♪̸':'♪';$('muteButton').setAttribute('aria-label',muted?'Unmute sound':'Mute sound');}
$('muteButton').onclick=()=>{muted=!muted;try{localStorage.setItem('sh2-muted',muted?'1':'0');}catch{}syncMute();if(!muted)unlockAudio();};syncMute();
$('fullscreenButton').onclick=()=>{try{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{});}catch{}};
document.addEventListener('fullscreenchange',()=>{$('fullscreenButton').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');resize();});
$('moreGames').href='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
function notify(text,time=2.1){$('toast').textContent=text;toastTime=time;$('toast').classList.add('visible');}
function releaseInput(){keys.clear();touchHeld.clear();stick.x=stick.y=0;stick.id=null;$('stick').querySelector('span').style.transform='';document.querySelectorAll('.pressed').forEach(x=>x.classList.remove('pressed'));}
function showMenu(type){state=type;releaseInput();ui.menu.hidden=false;ui.menu.className=type==='main'?'main-menu':'sub-menu'+(type==='help'?' help-menu':'');$('hud').hidden=true;$('bossHud').hidden=true;$('touchControls').hidden=true;$('keyboardHint').style.display='none';$('pauseButton').hidden=true;$('chapterIntro').hidden=true;$('toast').classList.remove('visible');ui.helpContent.hidden=type!=='help';ui.cont.hidden=true;ui.home.hidden=type==='main'||type==='help';ui.help.hidden=type==='help';$('menuDescription').hidden=type==='help';$('menuChapter').textContent=String(chapter+1).padStart(2,'0')+' / 05';$('menuLocation').textContent=chapters[chapter].name;
 const set=(eye,title,sub,desc,primary)=>{$('eyebrow').innerHTML='<i></i>'+eye;$('menuTitle').innerHTML=title;$('menuSubtitle').textContent=sub;$('menuDescription').innerHTML=desc;ui.label.textContent=primary;};
 if(type==='main'){set('A LETTER. A TOWN. A NIGHTMARE.','<span>SILENT HILL</span><em>2</em>','BEAT EM UP','Some things follow you into the fog.<br>Fight your way through five chapters.',ready?'START GAME':loadingError?'RETRY LOADING':ui.label.textContent);ui.cont.hidden=!(ready&&(runStarted||save));ui.cont.textContent=runStarted?'CONTINUE RUN':save?'CONTINUE · CHAPTER '+String(save.chapter+1).padStart(2,'0'):'CONTINUE';$('menuChapter').textContent='01 / 05';$('menuLocation').textContent='SOUTH VALE';}
 if(type==='pause')set('THE FOG CAN WAIT.','PAUSED',chapters[chapter].name,'Catch your breath.<br>Your progress in this area is safe.','RESUME');
 if(type==='help')set('SURVIVE THE NIGHT.','HOW TO PLAY','STAY ALIVE. KEEP MOVING.','','BACK');
 if(type==='defeat')set('THE NIGHTMARE IS NOT OVER.','LOST IN THE FOG',chapters[chapter].name,'Try this chapter again.<br>Your chapter-entry supplies will be restored.','RETRY CHAPTER');
 if(type==='chapter')set('KEEP MOVING.','CHAPTER COMPLETE',chapters[chapter].name,'The road leads to '+chapters[Math.min(4,chapter+1)].name+'.<br>Next chapter: +35 health and 16 rounds.','NEXT CHAPTER');
 if(type==='victory')set('THE FOG IS LIFTING.','THE LONG WAY HOME','ALL FIVE CHAPTERS COMPLETE','You faced the thing that followed you.<br>Final score: '+String(score).padStart(6,'0'),'PLAY AGAIN');
 ui.primary.disabled=type==='main'&&!ready&&!loadingError;}
function resume(){if(!p||p.hp<=0)return;state='play';ui.menu.hidden=true;$('hud').hidden=false;$('pauseButton').hidden=false;$('touchControls').hidden=!touchMode;$('keyboardHint').style.display=touchMode?'none':'flex';releaseInput();last=performance.now();updateHud();}
function pause(){if(state==='play'&&!transition)showMenu('pause');else if(state==='pause')resume();}
$('pauseButton').onclick=pause;ui.help.onclick=()=>{helpOrigin=state;showMenu('help');};ui.home.onclick=()=>showMenu('main');
ui.cont.onclick=()=>{unlockAudio();if(runStarted&&p&&p.hp>0){resume();}else if(save){chapter=save.chapter;startChapter({...save});}};
ui.primary.onclick=()=>{unlockAudio();if(state==='main'){if(loadingError){loadAssets();return;}if(!ready)return;newGame();}else if(state==='pause')resume();else if(state==='help'){if(helpOrigin==='main')showMenu('main');else showMenu(helpOrigin);}else if(state==='defeat')startChapter({...checkpoint});else if(state==='chapter')beginTransition(()=>{chapter++;startChapter({chapter,hp:Math.min(MAX_HP,p.hp+35),clip:MAG,reserve:Math.min(80,p.reserve+p.clip+16-MAG),score});});else if(state==='victory')newGame();};
function beginTransition(fn){if(transition)return;releaseInput();transition={t:0,fn,done:false};$('fade').style.opacity='1';}
function newGame(){chapter=0;runStarted=true;startChapter({chapter:0,hp:MAX_HP,clip:MAG,reserve:24,score:0});}
function persist(){save={...checkpoint,version:1};try{localStorage.setItem(SAVE,JSON.stringify(save));}catch{}}
function startChapter(c){chapter=clamp(c.chapter,0,4);checkpoint={chapter,hp:clamp(c.hp,35,100),clip:clamp(c.clip??MAG,0,MAG),reserve:clamp(c.reserve,0,80),score:Math.max(0,c.score)};persist();score=checkpoint.score;area=0;camera=0;enemies=[];props=[];particles=[];projectiles=[];floaters=[];combo=0;chain=0;comboLife=0;chainLife=0;shake=0;hitstop=0;simTime=0;deathTime=0;runStarted=true;
 p={x:100,y:92,hp:checkpoint.hp,clip:checkpoint.clip,reserve:checkpoint.reserve,stamina:100,face:1,walk:0,moving:false,action:null,inv:1.5,hurt:0,dodge:0,dx:0,dy:0};
 spawnArea();resume();intro=2.5;$('introNumber').textContent='CHAPTER '+String(chapter+1).padStart(2,'0')+' / 05';$('introTitle').textContent=chapters[chapter].name;$('introSubtitle').textContent=chapters[chapter].line;$('chapterIntro').hidden=false;}
function spawnArea(){clearAnnounced=false;const start=area*AREA;let count=3+Math.min(chapter,2)+(area===2?1:0);if(chapter===4&&area===2)count=1;
 for(let i=0;i<count;i++){const type=chapter===4&&area===2?'pyramid':(chapter===0?'lying':((i+area)%3===0?'lying':'nurse'));const maxHp=type==='pyramid'?560:type==='nurse'?70+chapter*4:52+chapter*3;enemies.push({id:chapter*100+area*10+i,type,x:start+350+i*112,y:30+(i*67+area*31)%145,hp:maxHp,maxHp,face:-1,walk:0,moving:false,hurt:0,inv:0,state:'approach',t:0,cool:1+i*.42,wind:0,aimX:0,aimY:0,attackFace:-1,attackKind:'melee',dead:0,hitDone:false});}
 for(let j=0;j<2;j++)props.push({x:start+260+j*370,y:j===0?154:32,hp:60,frame:0,reward:j===0?'health':'ammo',paid:false});
 if(chapter===4&&area===2)notify('PYRAMID HEAD · Dodge the red sweep, then strike.',3.7);else if(area>0)notify(chapters[chapter].areas[area],2.2);}
function living(){return enemies.filter(e=>e.hp>0);}
function action(kind){if(state!=='play'||!p||p.hp<=0||transition||intro>1.7)return;if(p.action||p.dodge>0||p.hurt>0)return;
 if(kind==='dodge'){if(p.stamina<38){notify('Catch your breath',.8);return;}const m=movement();let dx=m.x,dy=m.y;if(!dx&&!dy)dx=p.face;let len=Math.hypot(dx,dy)||1;p.dx=dx/len;p.dy=dy/len;p.dodge=.32;p.inv=.4;p.stamina-=38;combo=0;sound('dodge');return;}
 if(kind==='reload'){if(p.clip===MAG||p.reserve<=0)return;p.action={type:'reload',t:0,duration:1.12,hit:true};notify('RELOADING',1.1);sound('reload');return;}
 if(kind==='shoot'){if(p.clip<=0){if(p.reserve>0)action('reload');else notify('NO AMMO · Use your pipe',1.1);return;}p.clip--;p.action={type:'shoot',t:0,duration:.4,hit:false};return;}
 if(kind==='heavy'){if(p.stamina<24){notify('Catch your breath',.8);return;}p.stamina-=24;p.action={type:'heavy',t:0,duration:.72,hit:false};combo=0;return;}
 if(kind==='attack'){combo=comboLife>0?(combo%3)+1:1;comboLife=.85;p.action={type:'attack',t:0,duration:combo===3?.43:.31,hit:false,combo};}
}
function movement(){let x=stick.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y=stick.y+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);let n=Math.hypot(x,y);if(n>1){x/=n;y/=n;}return{x,y};}
const bindings={KeyJ:'attack',KeyK:'heavy',KeyL:'shoot',Space:'dodge',KeyR:'reload'};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyJ','KeyK','KeyL','KeyR','Escape','KeyP'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat)pause();return;}if(e.code==='KeyM'&&!e.repeat){$('muteButton').click();return;}if(state!=='play')return;keys.add(e.code);if(bindings[e.code]&&!e.repeat)action(bindings[e.code]);});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{releaseInput();if(state==='play'&&!transition)showMenu('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){releaseInput();if(state==='play'&&!transition)showMenu('pause');}});
const stickEl=$('stick');function stickMove(e){const r=stickEl.getBoundingClientRect(),radius=r.width*.34;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius;let n=Math.hypot(x,y);if(n>1){x/=n;y/=n;}stick.x=Math.abs(x)<.12?0:x;stick.y=Math.abs(y)<.12?0:y;stickEl.querySelector('span').style.transform=`translate(${x*radius*.7}px,${y*radius*.7}px)`;}
stickEl.addEventListener('pointerdown',e=>{e.preventDefault();if(stick.id!==null)return;stick.id=e.pointerId;stickEl.setPointerCapture(e.pointerId);stickMove(e);});stickEl.addEventListener('pointermove',e=>{if(e.pointerId===stick.id)stickMove(e);});for(const evt of ['pointerup','pointercancel','lostpointercapture'])stickEl.addEventListener(evt,e=>{if(e.pointerId===stick.id){stick.id=null;stick.x=stick.y=0;stickEl.querySelector('span').style.transform='';}});
document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touchHeld.add(b.dataset.action);b.classList.add('pressed');action(b.dataset.action);});for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,()=>{touchHeld.delete(b.dataset.action);b.classList.remove('pressed');});});
addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!touchMode){touchMode=true;if(state==='play'){$('touchControls').hidden=false;$('keyboardHint').style.display='none';}}});
function burst(x,y,n=12,color='#d1c6a7'){for(let i=0;i<n;i++){const a=Math.random()*TAU,v=35+Math.random()*110;particles.push({x,y,z:65,vx:Math.cos(a)*v,vy:Math.sin(a)*30,vz:60+Math.random()*130,life:.25+Math.random()*.28,color});}}
function floating(text,x,y,color='#e9d8b8'){floaters.push({text,x,y,z:125,life:1,color});}
function hitEnemy(e,damage,push,heavy=false){if(e.hp<=0||e.inv>0)return false;e.hp=Math.max(0,e.hp-damage);e.inv=.16;e.hurt=.19;const armor=e.type==='pyramid'&&e.state==='windup';if(!armor){e.x+=p.face*push;e.state='recover';e.t=e.type==='pyramid'?.32:.45;e.cool=.65;}burst(e.x,e.y,heavy?16:9);floating(String(damage),e.x,e.y);chain++;chainLife=2.4;hitstop=heavy?.055:.027;shake=heavy?5:2;sound(heavy?'heavy':'hit');if(e.hp<=0){e.state='dead';e.dead=0;score+=e.type==='pyramid'?2500:120+chapter*25;burst(e.x,e.y,18,'#a9b096');}return true;}
function hitProp(o,damage){if(o.hp<=0)return;o.hp=Math.max(0,o.hp-damage);o.frame=o.hp<=0?2:o.hp<=36?1:0;burst(o.x,o.y,10,'#b4a37e');sound('hit');if(o.hp===0&&!o.paid){o.paid=true;score+=60;if(o.reward==='health'){p.hp=Math.min(100,p.hp+24);floating('+24 HEALTH',o.x,o.y,'#bddaaa');}else{p.reserve=Math.min(80,p.reserve+8);floating('+8 ROUNDS',o.x,o.y,'#e1cba5');}sound('pickup');}}
function resolveAttack(a){a.hit=true;if(a.type==='shoot'){sound('shoot');let target=living().filter(e=>(e.x-p.x)*p.face>-12&&Math.abs(e.y-p.y)<35&&Math.abs(e.x-p.x)<610).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];let end=p.x+p.face*570;if(target){end=target.x;hitEnemy(target,37,13);}else{let o=props.find(o=>o.hp>0&&(o.x-p.x)*p.face>0&&Math.abs(o.y-p.y)<40&&Math.abs(o.x-p.x)<570);if(o){end=o.x;hitProp(o,25);}}const m=ASSETS.james,ratio=PLAYER_HEIGHT/m.bodyHeight,x=p.x+p.face*(SHOT_MUZZLE.x-m.anchorX)*ratio,z=(m.anchorY-SHOT_MUZZLE.y)*ratio;end=x+p.face*Math.max(0,(end-x)*p.face);particles.push({type:'tracer',x,y:p.y,z,end,life:.07,color:'#ffe3a0'});shake=2;return;}
 const heavy=a.type==='heavy',finisher=a.combo===3,reach=heavy?139:112,wide=heavy?56:38,damage=heavy?48:finisher?36:24;let hit=false;
 for(const e of enemies){const dx=(e.x-p.x)*p.face;if(e.hp>0&&dx>-27&&dx<reach&&Math.abs(e.y-p.y)<wide)hit=hitEnemy(e,damage,heavy?52:finisher?42:14,heavy||finisher)||hit;}
 for(const o of props){const dx=(o.x-p.x)*p.face;if(o.hp>0&&dx>-25&&dx<reach+15&&Math.abs(o.y-p.y)<wide+8){hitProp(o,heavy?65:30);hit=true;}}
 if(!hit)sound(heavy?'dodge':'reload');if(finisher&&hit)floating('FINISHER',p.x,p.y,'#e7dfbd');}
function hitPlayer(damage,dir){if(p.hp<=0||p.inv>0||p.dodge>0)return;p.hp=Math.max(0,p.hp-damage);p.hurt=.3;p.inv=1;p.action=null;combo=0;chain=0;p.x=clamp(p.x+dir*23,35,area*AREA+AREA-75);shake=7;burst(p.x,p.y,8,'#c9a481');sound('hurt');if(p.hp<=0){deathTime=1.1;p.action=null;releaseInput();}}
function tickEnemy(e,dt){e.moving=false;e.inv=Math.max(0,e.inv-dt);e.hurt=Math.max(0,e.hurt-dt);if(e.hp<=0){e.dead+=dt;return;}e.cool=Math.max(0,e.cool-dt);const dx=p.x-e.x,dy=p.y-e.y,dist=Math.abs(dx),boss=e.type==='pyramid';
 if(e.state==='windup'){e.t-=dt;if(e.t<=0){e.state='strike';e.t=boss?.35:.25;e.hitDone=false;e.x+=e.attackFace*(e.attackKind==='lunge'?75:boss?25:9);}return;}
 if(e.state==='strike'){if(!e.hitDone){e.hitDone=true;if(e.attackKind==='spit'){projectiles.push({x:e.x+e.attackFace*40,y:e.y,z:78,dx:e.attackFace*225,dy:clamp(e.aimY-e.y,-65,65)*1.1,life:2.2});}else{const d=(p.x-e.x)*e.attackFace,range=boss?158:e.attackKind==='lunge'?104:91,lane=boss?62:36;if(d>-35&&d<range&&Math.abs(p.y-e.y)<lane)hitPlayer(boss?22:e.type==='nurse'?12:10,e.attackFace);}}e.t-=dt;if(e.t<=0){e.state='recover';e.t=boss?1.15:.68;e.cool=boss?1.4:1+Math.random()*.6;}return;}
 if(e.state==='recover'){e.t-=dt;if(e.t<=0)e.state='approach';return;}
 e.face=dx>=0?1:-1;let desired=boss?116:63;const canSpit=e.type==='lying'&&dist>125&&dist<310&&Math.abs(dy)<37;const onScreen=Math.abs(e.x-p.x)<Math.min(560,VW*.82);let attacking=enemies.filter(q=>q.hp>0&&(q.state==='windup'||q.state==='strike')).length;
 if(e.cool<=0&&onScreen&&p.hp>0&&intro<.7&&attacking<2&&((dist<desired+25&&Math.abs(dy)<(boss?52:26))||canSpit)){e.state='windup';e.attackKind=canSpit?'spit':boss&&e.hp<e.maxHp*.45&&Math.random()<.4?'lunge':'melee';e.wind=boss?1.0:e.type==='nurse'?.58:.78;e.t=e.wind;e.attackFace=e.face;e.aimY=p.y;e.aimX=p.x;return;}
 let mx=dist>desired?(dx>0?1:-1):dist<desired-23?(dx>0?-.5:.5):0,my=Math.abs(dy)>9?(dy>0?1:-1):0;let n=Math.hypot(mx,my)||1;const speed=boss?51:e.type==='nurse'?83+chapter*3:65+chapter*2,oldX=e.x,oldY=e.y;e.x+=mx/n*speed*dt;e.y+=my/n*speed*.72*dt;
 for(const q of enemies){if(q===e||q.hp<=0)continue;const sx=e.x-q.x,sy=e.y-q.y;if(Math.abs(sx)<30&&Math.abs(sy)<21){e.y+=(sy>=0?1:-1)*28*dt;}}
 e.x=clamp(e.x,45,area*AREA+AREA-100);e.y=clamp(e.y,15,176);const move=Math.hypot(e.x-oldX,e.y-oldY);e.moving=move>.08;e.walk+=move;}
function update(dt){if(transition){transition.t+=dt;if(transition.t>.36&&!transition.done){transition.done=true;transition.fn();$('fade').style.opacity='0';}if(transition.t>.78)transition=null;return;}if(state!=='play')return;
 simTime+=dt;toastTime=Math.max(0,toastTime-dt);if(!toastTime)$('toast').classList.remove('visible');intro=Math.max(0,intro-dt);if(intro<=0)$('chapterIntro').hidden=true;if(hitstop>0){hitstop-=dt;return;}if(deathTime>0){deathTime-=dt;if(deathTime<=0)showMenu('defeat');}
 p.inv=Math.max(0,p.inv-dt);p.hurt=Math.max(0,p.hurt-dt);comboLife=Math.max(0,comboLife-dt);chainLife=Math.max(0,chainLife-dt);if(!chainLife)chain=0;p.stamina=Math.min(100,p.stamina+dt*(p.action?9:26));p.moving=false;
 if(p.hp>0){if(p.dodge>0){p.dodge=Math.max(0,p.dodge-dt);p.x+=p.dx*425*dt;p.y+=p.dy*290*dt;p.walk+=425*dt;}else if(p.action){const a=p.action;a.t+=dt;if(a.type==='reload'){if(a.t>=a.duration){let r=Math.min(MAG-p.clip,p.reserve);p.clip+=r;p.reserve-=r;p.action=null;sound('reload');}}else{if(!a.hit&&a.t>=(a.type==='heavy'?.35:a.type==='shoot'?.075:.105))resolveAttack(a);if(a.t>=a.duration)p.action=null;}}
 else if(p.hurt<=0&&intro<1.7){for(const [code,a] of Object.entries(bindings)){if(keys.has(code)){action(a);break;}}if(!p.action&&!p.dodge)for(const a of touchHeld){action(a);break;}if(!p.action&&!p.dodge){const m=movement(),oldX=p.x,oldY=p.y;p.x+=m.x*193*dt;p.y+=m.y*143*dt;if(Math.abs(m.x)>.1)p.face=m.x>0?1:-1;p.moving=!!(m.x||m.y);p.walk+=Math.hypot(p.x-oldX,p.y-oldY);}}}
 let active=living();p.x=clamp(p.x,35,active.length?(area+1)*AREA-92:END-34);p.y=clamp(p.y,12,178);for(const e of enemies)tickEnemy(e,dt);
 for(const b of projectiles){b.x+=b.dx*dt;b.y+=b.dy*dt;b.life-=dt;if(p.hp>0&&Math.abs(b.x-p.x)<27&&Math.abs(b.y-p.y)<24){hitPlayer(9,Math.sign(b.dx));b.life=0;}}projectiles=projectiles.filter(b=>b.life>0);
 for(const q of particles){q.life-=dt;if(q.type==='tracer')continue;q.x+=q.vx*dt;q.y+=q.vy*dt;q.z+=q.vz*dt;q.vz-=480*dt;}particles=particles.filter(q=>q.life>0);for(const q of floaters){q.life-=dt;q.z+=dt*28;}floaters=floaters.filter(q=>q.life>0);shake=Math.max(0,shake-25*dt);
 active=living();if(!active.length&&p.hp>0){if(!clearAnnounced){clearAnnounced=true;notify(area===2?'AREA CLEAR · Head for the exit →':'AREA CLEAR · Follow the road →',3);sound('clear');score+=200;}if(p.x>(area+1)*AREA-65){if(area<2){area++;spawnArea();}else if(chapter<4)showMenu('chapter');else{score+=1000;try{localStorage.removeItem(SAVE);}catch{}save=null;runStarted=false;showMenu('victory');}}}
 let target=clamp(p.x-VW*.34,0,Math.max(0,END-VW*.7));camera=lerp(camera,target,1-Math.exp(-dt*7));hudTick-=dt;if(hudTick<=0){updateHud();hudTick=.06;}}
function updateHud(){if(!p)return;$('healthText').textContent=Math.ceil(p.hp)+' / 100';$('healthBar').style.width=p.hp+'%';$('healthBar').style.background=p.hp<30?'#b45c45':'#b9bd9b';$('ammo').textContent=String(p.clip).padStart(2,'0')+' / '+String(p.reserve).padStart(2,'0');$('staminaBar').style.width=p.stamina+'%';$('staminaLabel').textContent=p.stamina>=38?'DODGE READY':'RECOVERING';$('scoreValue').textContent=String(score).padStart(6,'0');$('chapterLabel').textContent='CH. '+String(chapter+1).padStart(2,'0')+' / 05 · AREA '+String(area+1).padStart(2,'0')+' / 03';$('areaName').textContent=chapters[chapter].areas[area];const alive=living();$('threats').textContent=alive.length?alive.length+(alive.length===1?' THREAT REMAINS':' THREATS REMAIN'):'AREA CLEAR · MOVE RIGHT →';const boss=alive.find(e=>e.type==='pyramid');$('bossHud').hidden=state!=='play'||!boss;if(boss)$('bossBar').style.width=(boss.hp/boss.maxHp*100)+'%';}
function layer(name,cam,factor,y,height,opaque=false){const im=images[name];if(!im)return;const w=im.width/im.height*height,offset=((cam*factor)%w+w)%w;for(let x=-offset;x<VW;x+=w)ctx.drawImage(im,Math.floor(x),y,w+1,height);}
function drawScene(theme,cam,t,hero=false){const id=chapters[theme].id;ctx.fillStyle=['#69746b','#31392e','#283c37','#30291e','#373b3d'][theme];ctx.fillRect(0,0,VW,VH);const backH=ground+30;layer(id+'-far',cam,.08,-70,backH+70,true);const mh=theme===0?386:Math.max(420,ground+36),nh=theme===0?347:Math.max(392,ground+18);layer(id+'-mid',cam,.3,ground-mh+14,mh);layer(id+'-near',cam,.62,ground-nh+10,nh);const floor=images[id+'-floor'];if(floor){const fh=Math.max(315,VH-ground+25);layer(id+'-floor',cam,1,ground-5,fh,true);}ctx.fillStyle='#07110b18';ctx.fillRect(0,0,VW,VH);
 if(theme===0||theme===4){ctx.save();const haze=ctx.createLinearGradient(0,ground-80,0,VH);haze.addColorStop(0,'#bcc9bc00');haze.addColorStop(.35,'#d4ddc011');haze.addColorStop(1,'#b0bcb700');ctx.fillStyle=haze;ctx.fillRect(0,ground-80,VW,VH);ctx.restore();}
}
function sprite(name,frame,x,y,height,face=1){const im=images[name],m=ASSETS[name];if(!im||!m)return;const f=m.frames[frame]||m.frames[0],ratio=height/m.bodyHeight;ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(im,f.x,f.y,m.cellW,m.cellH,-m.anchorX*ratio,-m.anchorY*ratio,m.cellW*ratio,m.cellH*ratio);ctx.restore();}
function shadow(x,y,w=37,h=10){ctx.fillStyle='#040b0790';ctx.beginPath();ctx.ellipse(x,y,w,h,0,0,TAU);ctx.fill();}
function actorFrame(e,player=false){if(e.hp<=0)return 7;if(e.hurt>0)return 6;if(player){if(e.dodge>0)return 2;if(e.action){let a=e.action;if(a.type==='reload')return 0;if(a.type==='shoot')return 5;if(a.type==='heavy')return a.t<.35?4:3;return a.combo===3&&a.t<.105?4:3;}}else{if(e.state==='windup')return 4;if(e.state==='strike')return e.attackKind==='lunge'?5:3;}return e.moving?(Math.floor(e.walk/30)%2?2:1):0;}
function drawEntity(e,player=false){const x=e.x-camera,y=ground+e.y,h=player?PLAYER_HEIGHT:e.type==='pyramid'?247:e.type==='nurse'?181:165;if(x< -250||x>VW+250)return;shadow(x,y,player?34:e.type==='pyramid'?48:31,player?9:10);sprite(player?'james':e.type,actorFrame(e,player),x,y,h,e.face);if(player&&p.inv>0&&p.hp>0){ctx.strokeStyle='#e4dbb076';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(x,y+2,37,11,0,0,TAU);ctx.stroke();}if(!player&&e.hp>0&&e.hp<e.maxHp&&e.type!=='pyramid'){ctx.fillStyle='#101811';ctx.fillRect(x-22,y-h-15,44,4);ctx.fillStyle='#b6b99e';ctx.fillRect(x-22,y-h-15,44*e.hp/e.maxHp,4);}if(!player&&e.hp>0&&e.state==='windup'){ctx.fillStyle='#ecaa72';ctx.font='700 22px Silent';ctx.textAlign='center';ctx.fillText('!',x,y-h-23);}}
function drawTelegraph(e){if(e.state!=='windup'||e.hp<=0)return;let x=e.x-camera,y=ground+e.y,boss=e.type==='pyramid',reach=e.attackKind==='spit'?285:boss?160:96,w=reach;ctx.save();ctx.globalAlpha=.3+.25*(1-e.t/e.wind);ctx.fillStyle=boss?'#b94332':'#bf7c48';ctx.beginPath();ctx.ellipse(x+e.attackFace*reach*.48,y,w*.62,boss?60:32,0,0,TAU);ctx.fill();ctx.strokeStyle='#f0b385';ctx.lineWidth=1.2;ctx.stroke();ctx.restore();}
function drawWorld(){drawScene(chapter,camera,simTime);for(const e of enemies)drawTelegraph(e);const renderables=[...props.map(o=>({y:o.y,type:'prop',o})),...enemies.map(o=>({y:o.y,type:'enemy',o})),{y:p.y,type:'player',o:p}].sort((a,b)=>a.y-b.y);for(const item of renderables){if(item.type==='prop'){const o=item.o;shadow(o.x-camera,ground+o.y,35,8);sprite(chapters[chapter].id+'-prop',o.frame,o.x-camera,ground+o.y,108);}else drawEntity(item.o,item.type==='player');}
 for(const b of projectiles){let x=b.x-camera,y=ground+b.y-b.z;ctx.fillStyle='#a3b078';ctx.beginPath();ctx.ellipse(x,y,10,5,0,0,TAU);ctx.fill();ctx.fillStyle='#758258';ctx.beginPath();ctx.ellipse(x-Math.sign(b.dx)*10,y+2,7,3,0,0,TAU);ctx.fill();}
 for(const q of particles){ctx.save();ctx.globalAlpha=Math.min(1,q.life*6);ctx.fillStyle=q.color;if(q.type==='tracer'){ctx.strokeStyle=q.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(q.x-camera,ground+q.y-q.z);ctx.lineTo(q.end-camera,ground+q.y-q.z);ctx.stroke();ctx.beginPath();ctx.arc(q.x-camera,ground+q.y-q.z,5,0,TAU);ctx.fill();}else ctx.fillRect(q.x-camera,ground+q.y-q.z,3,3);ctx.restore();}
 ctx.textAlign='center';for(const q of floaters){ctx.globalAlpha=Math.min(1,q.life*2);ctx.fillStyle=q.color;ctx.font='700 '+(q.text.length>3?'12':'18')+'px Silent';ctx.fillText(q.text,q.x-camera,ground+q.y-q.z);}ctx.globalAlpha=1;
 if(!living().length&&p.hp>0){const xx=clamp((area+1)*AREA-45-camera,60,VW-70),yy=ground+82;ctx.fillStyle='#d2d6ab';ctx.font='700 39px Silent';ctx.fillText('→',xx+Math.sin(simTime*4)*6,yy);ctx.font='700 10px Silent';ctx.fillText(area===2?'EXIT':'CONTINUE',xx,yy+24);}
 if(chain>=3&&chainLife>0){ctx.textAlign='right';ctx.fillStyle='#d5d9ba';ctx.font='700 29px Silent';ctx.fillText(chain+' HITS',VW-30,185);ctx.font='9px Silent';ctx.fillText('KEEP THEM BACK',VW-30,205);}if(p.action&&p.action.type==='reload'){ctx.fillStyle='#0a150b';ctx.fillRect(p.x-camera-29,ground+p.y-209,58,5);ctx.fillStyle='#d0d4b2';ctx.fillRect(p.x-camera-29,ground+p.y-209,58*p.action.t/p.action.duration,5);}}
function drawHero(){const t=presentation,cam=90+Math.sin(t*.075)*70;drawScene(0,cam,t,true);const portrait=W/H<.8;let py=portrait?VH*.49:VH*.84,h=portrait?285:440,px=portrait?VW*.45:VW*.69;let ex=portrait?VW*.81:VW*.9,eh=portrait?330:486;shadow(ex,py-18,eh*.18,18);sprite('pyramid',0,ex,py-18,eh,-1);shadow(px,py,h*.19,20);sprite('james',0,px,py,h,-1);}
function draw(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.fillStyle='#101815';ctx.fillRect(0,0,W,H);ctx.scale(scale,scale);ctx.save();if(state==='play'&&shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake*.7);const hero=state==='main'||state==='help'&&helpOrigin==='main';if(hero)drawHero();else if(p)drawWorld();else drawHero();ctx.restore();}
function frame(now){const dt=Math.min((now-last)/1000||.016,.04);last=now;presentation+=dt;update(dt);draw();requestAnimationFrame(frame);}
async function loadAssets(){loadingError=false;ui.primary.disabled=true;const entries=Object.entries(ASSETS);let loaded=0;try{await Promise.all(entries.map(([name,meta])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[name]=im;loaded++;if(!loadingError)ui.label.textContent='LOADING '+Math.round(loaded/entries.length*100)+'%';$('loadBar').style.width=loaded/entries.length*100+'%';resolve();};im.onerror=()=>reject(new Error(name));im.src='assets/'+meta.file;})));await document.fonts.ready;ready=true;$('loadBar').style.display='none';showMenu('main');}catch{loadingError=true;ui.primary.disabled=false;ui.label.textContent='RETRY LOADING';$('menuDescription').textContent='Some artwork could not load. Check the connection and retry.';}}
showMenu('main');loadAssets();requestAnimationFrame(frame);
})();
