(function(root){
'use strict';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),AREA=1120,LANES={min:25,max:235};
const THEMES=[
 {id:'forest',name:'CASTOR WOODS',areas:['RANGER TRAIL','THE OLD ROAD','HUNTING GROUNDS'],brief:'Find a route out of the woods.',boss:'THE RAVAGER',bossType:'brute',bossHP:360,pattern:['swing','slam'],propHeight:74,color:'#17251b',enemies:[['biter','biter','viral'],['biter','biter','viral','biter'],['viral','biter','biter']]},
 {id:'town',name:'OLD TOWN',areas:['SILENT STREETS','MARKET SQUARE','MIDNIGHT CROSSING'],brief:'Cross the town before the infected close in.',boss:'NIGHT STALKER',bossType:'volatile',bossHP:400,pattern:['leap','swing','leap'],propHeight:104,color:'#16232c',enemies:[['biter','viral','biter','biter'],['viral','volatile','biter','viral'],['biter','viral','volatile']]},
 {id:'sawmill',name:'BLACKRIDGE MILL',areas:['LOGGING YARD','SAW HALL','THE LOADING BAY'],brief:'Cut through the abandoned sawmill.',boss:'THE FOREMAN',bossType:'brute',bossHP:480,pattern:['slam','swing','slam'],propHeight:94,color:'#29231b',enemies:[['viral','biter','brute','biter'],['brute','viral','biter','viral'],['viral','biter','volatile','biter']]},
 {id:'dam',name:'FLOODGATE',areas:['SERVICE ROAD','TURBINE DECK','THE SPILLWAY'],brief:'Secure the dam and reach the laboratory.',boss:'THE DROWNED',bossType:'volatile',bossHP:520,pattern:['leap','slam','swing'],propHeight:118,color:'#102c30',enemies:[['volatile','viral','biter','brute'],['viral','volatile','biter','viral','biter'],['brute','viral','volatile','biter']]},
 {id:'lab',name:'CONTAINMENT',areas:['QUARANTINE WING','TEST CHAMBERS','CONTAINMENT ZERO'],brief:'Break containment. Finish the hunt.',boss:'ALPHA SPECIMEN',bossType:'brute',bossHP:650,pattern:['slam','leap','swing','slam'],propHeight:85,color:'#111e26',enemies:[['viral','volatile','brute','biter'],['volatile','viral','brute','viral','biter'],['volatile','viral','biter','viral']]}
];
const TYPES={biter:{hp:75,speed:77,reach:88,wind:.85,recovery:1.15,damage:9,height:175},viral:{hp:65,speed:137,reach:92,wind:.64,recovery:1.12,damage:10,height:172},volatile:{hp:125,speed:118,reach:130,wind:.85,recovery:1.3,damage:14,height:198},brute:{hp:190,speed:62,reach:132,wind:1.05,recovery:1.6,damage:18,height:225}};
class Engine{
 constructor(){this.onEvent=()=>{};this.state='menu';this.chapter=0;this.player=this.newPlayer();this.enemies=[];this.props=[];this.pickups=[];this.areas=[];this.score=0;this.kills=0;this.combo=0;this.maxCombo=0;this.time=0;this.nextId=1;this.seed=4931;this.frontier=0;this.area=0;this.checkpoint=null;}
 emit(type,data={}){this.onEvent({type,...data});}
 rand(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296;}
 newPlayer(hp=100,rage=0){return{x:135,y:132,hp:clamp(hp,1,100),rage:clamp(rage,0,100),beast:0,face:1,action:'idle',timer:0,duration:0,moving:false,walk:0,invuln:0,dodgeCD:0,kickCD:0,comboStep:0,chain:0,queued:'',queueTime:0,hitDone:false};}
 start(save){const valid=save&&Number.isInteger(save.chapter)&&save.chapter>=0&&save.chapter<THEMES.length;this.chapter=valid?save.chapter:0;this.score=valid?Number(save.score)||0:0;this.kills=valid?Number(save.kills)||0:0;this.maxCombo=valid?Number(save.maxCombo)||0:0;this.loadChapter(valid?save.hp:100,valid?save.rage:0);}
 loadChapter(hp=100,rage=0){this.player=this.newPlayer(hp,rage);this.area=0;this.frontier=0;this.enemies=[];this.props=[];this.pickups=[];this.areas=THEMES[this.chapter].areas.map(()=>({spawned:false,cleared:false}));this.combo=0;this.comboTimer=0;this.time=0;this.state='play';this.seed=4931+this.chapter*337;this.nextId=1;this.inputX=this.inputY=0;this.checkpoint={chapter:this.chapter,hp:this.player.hp,rage:this.player.rage,score:this.score,kills:this.kills,maxCombo:this.maxCombo};for(let a=0;a<3;a++){[[370,210],[775,40],[1030,214]].forEach(([x,y],i)=>this.props.push({id:this.nextId++,x:x+a*AREA,y,hp:60,state:0,drop:i===1?'rage':'health',awarded:false,theme:THEMES[this.chapter].id}));}this.spawnArea(0);this.emit('checkpoint',{save:{...this.checkpoint}});this.emit('notice',{text:THEMES[this.chapter].brief,duration:3.2});}
 retry(){if(!this.checkpoint)return;const s={...this.checkpoint};this.chapter=s.chapter;this.score=s.score;this.kills=s.kills;this.maxCombo=s.maxCombo;this.loadChapter(s.hp,s.rage);}
 nextChapter(){if(this.state!=='chapter'||this.chapter>=4)return false;this.chapter++;this.loadChapter(Math.min(100,this.player.hp+40),this.player.rage);return true;}
 pause(){if(this.state==='play'){this.state='paused';return true;}return false;}
 resume(){if(this.state==='paused')this.state='play';}
 spawnArea(a){if(this.areas[a].spawned)return;this.areas[a].spawned=true;this.frontier=a;THEMES[this.chapter].enemies[a].forEach((type,i)=>this.spawnEnemy(type,a*AREA+510+(i%3)*180+Math.floor(i/3)*65,45+(i%3)*78,a));if(a===2)this.spawnEnemy(THEMES[this.chapter].bossType,a*AREA+940,130,a,true);}
 spawnEnemy(type,x,y,area,boss=false){const t=TYPES[type],hp=boss?THEMES[this.chapter].bossHP:Math.round(t.hp*(1+this.chapter*.045));this.enemies.push({id:this.nextId++,type,x,y,hp,maxHP:hp,boss,area,height:t.height*(boss?1.16:1),face:-1,action:'idle',timer:0,duration:0,cd:.5+this.rand(),walk:0,moving:false,attackCount:0,kind:'swing',hitDone:false,deadTime:0});}
 get upper(){return Math.min(3*AREA-35,(this.frontier+1)*AREA-(this.areas[this.frontier]?.cleared?0:65));}
 get remaining(){return this.enemies.filter(e=>e.hp>0).length;}
 get boss(){return this.enemies.find(e=>e.boss&&e.hp>0);}
 startAction(action,duration){const p=this.player;p.action=action;p.duration=p.timer=duration;p.moving=false;p.hitDone=false;}
 action(name){if(this.state!=='play')return false;const p=this.player;
  if(name==='beast'){if(p.rage<100||p.beast>0)return false;p.rage=0;p.beast=7.5;p.hp=Math.min(100,p.hp+15);p.invuln=Math.max(p.invuln,.55);p.action='idle';p.timer=0;this.emit('beast',{x:p.x,y:p.y});this.emit('sound',{name:'beast'});this.emit('notice',{text:'BEAST UNLEASHED',duration:1.4});return true;}
  if(name==='dodge'){if(p.dodgeCD>0||p.action==='dodge'||p.hp<=0)return false;p.dodgeCD=.9;p.invuln=Math.max(p.invuln,.39);const x=this.inputX||(!this.inputY?p.face:0),y=this.inputY||0,l=Math.hypot(x,y)||1;p.dodgeX=x/l;p.dodgeY=y/l;this.startAction('dodge',.3);this.emit('sound',{name:'dodge'});return true;}
  if(!['idle','walk'].includes(p.action)){if(name==='attack'&&p.action==='attack'&&p.timer<.2){p.queued='attack';p.queueTime=.28;}return false;}
  if(name==='attack'){p.comboStep=p.chain>0?p.comboStep%3+1:1;p.chain=.82;this.startAction('attack',p.beast>0?.28:p.comboStep===3?.48:.32);this.emit('sound',{name:'swing'});return true;}
  if(name==='kick'&&p.kickCD<=0){p.kickCD=.85;this.startAction('kick',.43);this.emit('sound',{name:'kick'});return true;}
  return false;
 }
 hitProp(prop,damage){if(prop.hp<=0)return;prop.hp=Math.max(0,prop.hp-damage);prop.state=prop.hp===0?2:1;this.emit('impact',{x:prop.x,y:prop.y,z:40,color:'#d6ab67',count:9});if(prop.hp===0&&!prop.awarded){prop.awarded=true;this.score+=60;this.pickups.push({id:this.nextId++,x:prop.x,y:prop.y,type:prop.drop});this.emit('sound',{name:'break'});}}
 hitEnemy(e,damage,kind,face){if(e.hp<=0)return;const p=this.player;e.hp=Math.max(0,e.hp-damage);const knock=kind==='kick'?92:kind==='finisher'?58:kind==='beast'?55:19;e.x=clamp(e.x+face*knock,35,this.upper);if(!e.boss||kind==='finisher'||kind==='beast'||kind==='kick'){e.action='hurt';e.timer=kind==='kick'?.64:.29;e.cd=Math.max(e.cd,e.timer+.32);}this.combo++;this.comboTimer=2.8;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=Math.round(damage*(1+Math.min(3,Math.floor(this.combo/7))*.25));if(p.beast<=0)p.rage=Math.min(100,p.rage+7);this.emit('impact',{x:e.x,y:e.y,z:e.height*.6,color:kind==='beast'?'#ffd387':'#dcb56f',count:kind==='beast'?15:8});this.emit('damage',{x:e.x,y:e.y,z:e.height+4,text:String(damage),color:'#ffe0a0'});this.emit('sound',{name:'hit'});this.emit('shake',{amount:kind==='kick'||kind==='finisher'||kind==='beast'?4:2});if(e.hp===0){e.action='dead';e.timer=0;e.deadTime=0;e.moving=false;this.kills++;this.score+=e.boss?1500:120;p.hp=Math.min(100,p.hp+3);if(p.beast<=0)p.rage=Math.min(100,p.rage+9);if(this.kills%5===0)this.pickups.push({id:this.nextId++,x:e.x,y:e.y,type:'health'});if(e.boss){this.emit('notice',{text:THEMES[this.chapter].boss+' DEFEATED',duration:2.3});this.emit('sound',{name:'boss'});}}}
 resolveHit(){const p=this.player,kick=p.action==='kick',beast=p.beast>0&&!kick,finish=p.comboStep===3&&!kick;const reach=kick?173:beast?182:finish?166:139,damage=kick?22:beast?62:finish?48:p.comboStep===2?34:28,kind=kick?'kick':beast?'beast':finish?'finisher':'melee';let hit=false;for(const e of this.enemies){const dx=(e.x-p.x)*p.face;if(e.hp>0&&dx>-26&&dx<reach&&Math.abs(e.y-p.y)<(beast?63:kick?50:49)){this.hitEnemy(e,damage,kind,p.face);hit=true;}}for(const prop of this.props){const dx=(prop.x-p.x)*p.face;if(prop.hp>0&&dx>-24&&dx<reach&&Math.abs(prop.y-p.y)<54){this.hitProp(prop,kick?33:damage);hit=true;}}if(finish&&hit&&!beast)this.emit('float',{x:p.x,y:p.y,z:208,text:'FINISHER',color:'#edb553'});}
 hurtPlayer(amount,e){const p=this.player;if(p.hp<=0||p.invuln>0)return false;amount=Math.round(amount*(p.beast>0?.5:1));p.hp=Math.max(0,p.hp-amount);p.invuln=.84;p.rage=Math.min(100,p.rage+amount*.9);p.x=clamp(p.x+(p.x<e.x?-22:22),35,this.upper);this.startAction('hurt',.23);this.combo=0;this.emit('hurt');this.emit('sound',{name:'hurt'});if(!p.hp){p.action='dead';this.state='dying';this.deathTimer=1.15;}return true;}
 updateEnemy(e,dt){if(e.hp<=0){e.deadTime+=dt;return;}const p=this.player,t=TYPES[e.type];e.moving=false;e.cd=Math.max(0,e.cd-dt);const dx=p.x-e.x,dy=p.y-e.y;if(!['windup','attack'].includes(e.action))e.face=dx>=0?1:-1;
  if(e.action==='hurt'){e.timer-=dt;if(e.timer<=0)e.action='idle';return;}
  if(e.action==='windup'){e.timer-=dt;if(e.timer<=0){e.action='attack';e.timer=e.kind==='leap'?.42:.33;e.hitDone=false;this.emit('sound',{name:'enemy'});}return;}
  if(e.action==='attack'){e.timer-=dt;if(e.kind==='leap'){e.x=clamp(e.x+e.face*420*dt,35,this.upper);e.y=clamp(e.y+(e.targetY-e.y)*Math.min(1,dt*5),LANES.min,LANES.max);if(!e.hitDone&&Math.abs(p.x-e.x)<95&&Math.abs(p.y-e.y)<43){e.hitDone=true;this.hurtPlayer(t.damage+(e.boss?4:0),e);}}else if(!e.hitDone){e.hitDone=true;if(e.kind==='slam'){this.emit('slam',{x:e.x,y:e.y});if(Math.abs(dx)<205&&Math.abs(dy)<91)this.hurtPlayer(t.damage+5,e);}else if(dx*e.face>-27&&Math.abs(dx)<t.reach+22&&Math.abs(dy)<48)this.hurtPlayer(t.damage+(e.boss?3:0),e);}if(e.timer<=0){e.action='idle';e.cd=t.recovery+this.rand()*.5;}return;}
  if(p.hp<=0)return;const pattern=THEMES[this.chapter].pattern,kind=e.boss?pattern[e.attackCount%pattern.length]:e.type==='volatile'&&e.attackCount%3===0?'leap':e.type==='brute'&&e.attackCount%3===1?'slam':'swing',reach=kind==='leap'?300:kind==='slam'?165:t.reach;
  if(e.cd<=0&&Math.abs(dx)<reach&&Math.abs(dy)<(kind==='slam'?70:45)&&this.enemies.filter(o=>o.hp>0&&['windup','attack'].includes(o.action)).length<2){e.attackCount++;e.kind=kind;e.action='windup';e.duration=e.timer=kind==='slam'?1.14:kind==='leap'?.98:t.wind;e.targetY=p.y;return;}
  const speed=t.speed*(e.boss?1.1:1),preferred=e.type==='brute'?95:68;let vx=Math.abs(dx)>preferred?Math.sign(dx)*speed:0,vy=Math.abs(dy)>10?Math.sign(dy)*speed*.68:0;if(e.cd>.2&&Math.abs(dx)<preferred+14)vx=0;for(const o of this.enemies){if(o===e||o.hp<=0)continue;const xx=e.x-o.x,yy=e.y-o.y;if(Math.abs(xx)<45&&Math.abs(yy)<29){vx+=Math.sign(xx||e.id-o.id)*20;vy+=Math.sign(yy||e.id-o.id)*23;}}const ox=e.x,oy=e.y;e.x=clamp(e.x+vx*dt,35,this.upper);e.y=clamp(e.y+vy*dt,LANES.min,LANES.max);const distance=Math.hypot(e.x-ox,e.y-oy);if(distance>.025){e.moving=true;e.walk+=distance;e.action='walk';}else e.action='idle';
 }
 step(dt,input={}){dt=clamp(dt,0,.04);if(this.state==='dying'){this.deathTimer-=dt;if(this.deathTimer<=0){this.state='dead';this.emit('defeat');}return;}if(this.state!=='play')return;this.time+=dt;const p=this.player;this.inputX=clamp(input.x||0,-1,1);this.inputY=clamp(input.y||0,-1,1);if(this.inputX&&['idle','walk'].includes(p.action))p.face=this.inputX>0?1:-1;for(const k of ['invuln','dodgeCD','kickCD','chain','queueTime'])p[k]=Math.max(0,p[k]-dt);if(!p.queueTime)p.queued='';p.beast=Math.max(0,p.beast-dt);this.comboTimer-=dt;if(this.comboTimer<=0)this.combo=0;
  if(input.actions)for(const a of input.actions)this.action(a);if(input.attack)this.action('attack');if(input.kick)this.action('kick');const ox=p.x,oy=p.y;p.moving=false;
  if(p.timer>0){p.timer-=dt;if(['attack','kick'].includes(p.action)&&!p.hitDone&&p.duration-p.timer>(p.action==='kick'?.14:p.beast>0?.08:p.comboStep===3?.17:.105)){p.hitDone=true;this.resolveHit();}if(p.action==='dodge'){p.x+=p.dodgeX*560*dt;p.y+=p.dodgeY*280*dt;}if(p.timer<=0){p.action='idle';if(p.queued){const a=p.queued;p.queued='';this.action(a);}}}
  if(['idle','walk'].includes(p.action)){const l=Math.max(1,Math.hypot(this.inputX,this.inputY));p.x+=this.inputX/l*(p.beast>0?266:225)*dt;p.y+=this.inputY/l*152*dt;}p.x=clamp(p.x,35,this.upper);p.y=clamp(p.y,LANES.min,LANES.max);const moved=Math.hypot(p.x-ox,p.y-oy);if(moved>.02){p.moving=true;p.walk+=moved;if(p.action==='idle')p.action='walk';}else if(p.action==='walk')p.action='idle';
  for(const e of this.enemies)this.updateEnemy(e,dt);
  for(const item of this.pickups){if(p.hp>0&&Math.abs(p.x-item.x)<46&&Math.abs(p.y-item.y)<39){if(item.type==='health'){p.hp=Math.min(100,p.hp+25);this.emit('float',{x:item.x,y:item.y,z:100,text:'+25 HEALTH',color:'#c0e8a4'});}else{p.rage=Math.min(100,p.rage+30);this.emit('float',{x:item.x,y:item.y,z:100,text:'+30 BEAST',color:'#f4c073'});}item.collected=true;this.emit('sound',{name:'pickup'});}}this.pickups=this.pickups.filter(i=>!i.collected);
  if(p.hp<=0)return;const current=this.areas[this.frontier];if(!current.cleared&&!this.enemies.some(e=>e.area===this.frontier&&e.hp>0)){current.cleared=true;this.score+=350;this.emit('notice',{text:'AREA CLEAR · MOVE RIGHT',duration:2.2});this.emit('sound',{name:'clear'});}if(current.cleared&&this.frontier<2&&p.x>(this.frontier+1)*AREA-270)this.spawnArea(this.frontier+1);const a=clamp(Math.floor(p.x/AREA),0,2);if(a!==this.area){this.area=a;this.emit('area',{area:a});this.emit('notice',{text:THEMES[this.chapter].areas[a],duration:1.8});}if(this.areas.every(a=>a.cleared)&&p.x>3*AREA-80){this.score+=1200;this.state=this.chapter===4?'win':'chapter';this.emit(this.state==='win'?'victory':'chapterComplete');}
 }
}
const api={Engine,THEMES,TYPES,AREA,LANES,clamp};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.BeastCore=api;
})(typeof window!=='undefined'?window:this);
