(function(){
'use strict';
const {Engine,THEMES,AREA,LANES,clamp}=window.BeastCore;
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false}),game=new Engine(),catalog=window.BEAST_ASSETS,images={},keys=new Set(),touched=new Set(),queued=[];
const SAVE='dying-light-the-beast-brawler-v1',moreURL='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
let width=1,height=1,dpr=1,zoom=1,camera=0,horizon=0,groundBase=0,laneScale=.72,loadDone=false,loadError=false,hero=true,menu='main',helpBack='main',last=0,heroTime=0,noticeTime=0,shake=0,hurtFlash=0,beastFlash=0,transition=null;
let effects=[],floats=[],rings=[],touchMode=false,stickPointer=null,stickX=0,stickY=0,audio=null,master=null,muted=false;
try{muted=localStorage.getItem(SAVE+'-mute')==='1';}catch{}
const touchButtons=[...document.querySelectorAll('.touch-action')];
document.querySelectorAll('.more').forEach(a=>a.href=moreURL);
function initAudio(){try{if(audio){if(audio.state==='suspended')audio.resume().catch(()=>{});return;}audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=muted?0:.23;master.connect(audio.destination);}catch{}}
function tone(f,d,v=.3,type='triangle',end){if(!audio||muted)return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(1,end),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start();o.stop(t+d+.01);}
function noise(d,v=.3,cutoff=1400){if(!audio||muted)return;const n=Math.floor(audio.sampleRate*d),b=audio.createBuffer(1,n,audio.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=cutoff;g.gain.value=v;s.connect(f);f.connect(g);g.connect(master);s.start();}
function sound(name){switch(name){case'swing':noise(.13,.16,3200);break;case'kick':noise(.17,.24,1200);break;case'hit':noise(.09,.3,1100);tone(100,.08,.35,'triangle',35);break;case'hurt':noise(.16,.3,550);tone(73,.19,.28,'sawtooth',30);break;case'dodge':noise(.15,.13,800);break;case'enemy':tone(70,.18,.11,'sawtooth',50);break;case'break':noise(.28,.3,1600);break;case'pickup':tone(520,.12,.14);tone(790,.17,.09);break;case'clear':tone(220,.32,.15);tone(330,.37,.1);break;case'beast':tone(55,.65,.45,'sawtooth',130);noise(.45,.3,700);break;case'boss':tone(68,.9,.3,'sawtooth',21);noise(.4,.3,850);break;case'slam':noise(.3,.36,450);tone(45,.23,.4,'sine',22);break;}}
function updateSound(){$('sound').classList.toggle('muted',muted);$('sound').setAttribute('aria-label',muted?'Unmute sound':'Mute sound');if(master)master.gain.value=muted?0:.23;}
function toggleSound(){muted=!muted;try{localStorage.setItem(SAVE+'-mute',muted?'1':'0');}catch{}initAudio();updateSound();}
function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE));return s&&Number.isInteger(s.chapter)&&s.chapter>=0&&s.chapter<5?s:null;}catch{return null;}}
function saveRun(s){try{localStorage.setItem(SAVE,JSON.stringify(s));}catch{}}
function showNotice(text,d=2){$('notice').textContent=text;noticeTime=d;$('notice').classList.add('show');}
function clearInput(){keys.clear();touched.clear();queued.length=0;stickX=stickY=0;stickPointer=null;$('stick-knob').style.transform='';touchButtons.forEach(b=>b.classList.remove('pressed'));}
function setPlayUI(on){$('hud').hidden=!on;$('pause').hidden=!on;$('keyboard-guide').hidden=!on||touchMode;$('touch-controls').hidden=!on||!touchMode;$('branding').hidden=on;$('menu-shade').hidden=on;}
function showMain(){if(game.state==='play')game.pause();hero=true;heroTime=0;menu='main';$('main-menu').hidden=false;$('overlay').hidden=true;setPlayUI(false);$('notice').classList.remove('show');clearInput();const saved=readSave();$('continue').hidden=!loadDone||(!saved&&game.state!=='paused');$('continue').textContent=game.state==='paused'?'RESUME GAME':saved?'CONTINUE · CHAPTER '+String(saved.chapter+1).padStart(2,'0'):'';}
function showPlay(){hero=false;menu='';$('main-menu').hidden=true;$('overlay').hidden=true;setPlayUI(true);clearInput();canvas.focus({preventScroll:true});updateHUD();}
function begin(saved){if(!loadDone)return;initAudio();effects=[];floats=[];rings=[];game.start(saved);camera=-50;showPlay();showNotice(THEMES[game.chapter].brief,3);}
function resumeRun(){if(game.state==='paused'){game.resume();showPlay();}else begin(readSave());}
function button(text,fn,primary=false){const b=document.createElement('button');b.className=primary?'button primary':'text-button';b.textContent=text;b.onclick=fn;return b;}
function moreButton(){const a=document.createElement('a');a.className='button more';a.textContent='MORE GAMES ↗';a.href=moreURL;a.target='_blank';a.rel='noopener noreferrer';return a;}
function panel(type,kicker,title,body,primary,secondary=[]){menu=type;clearInput();setPlayUI(false);$('main-menu').hidden=true;$('overlay').hidden=false;$('notice').classList.remove('show');$('panel-kicker').textContent=kicker;$('panel-title').textContent=title;$('panel-content').innerHTML=body;const links=document.createElement('div');links.className='secondary';links.append(...secondary);$('panel-actions').replaceChildren(primary,moreButton(),links);primary.focus({preventScroll:true});}
function pause(){if(transition||!game.pause())return;panel('pause','CHAPTER '+String(game.chapter+1).padStart(2,'0')+' / 05','CATCH YOUR BREATH.','<p>'+THEMES[game.chapter].name+' · '+THEMES[game.chapter].areas[game.area]+'</p>',button('RESUME',()=>{game.resume();showPlay();},true),[button('HOW TO PLAY',()=>help('pause')),button('MAIN MENU',showMain)]);}
function help(from){helpBack=from;const rows=[['WASD','MOVE','Arrow keys work too. Change lanes to evade.'],['J','MACHETE COMBO','Hold or tap: two cuts and a heavy finisher.'],['K','KNOCKBACK KICK','Create space and interrupt attacks.'],['SPACE','DODGE','Move through danger with a quick dash.'],['E / L','UNLEASH THE BEAST','Fill the amber meter by fighting.'],['ESC','PAUSE','Your current fight waits for you.']];panel('help','SURVIVE CASTOR WOODS','FIGHT. EVADE. UNLEASH.','<div class="controls-grid">'+rows.map(r=>'<div class="control-row"><kbd>'+r[0]+'</kbd><div><strong>'+r[1]+'</strong><small>'+r[2]+'</small></div></div>').join('')+'</div><p class="tip">Dodge red attack warnings. Break supplies for health and Beast charge. Clear each encounter, then move right. Cleared routes stay open behind you.</p>',button('BACK',()=>{if(helpBack==='pause'){game.resume();pause();}else showMain();},true));}
function stats(){return '<div class="stats"><div><span>SCORE</span><b>'+String(game.score).padStart(6,'0')+'</b></div><div><span>INFECTED</span><b>'+game.kills+'</b></div><div><span>BEST COMBO</span><b>'+game.maxCombo+'</b></div></div>';}
function result(win){hero=false;if(!win)saveRun({chapter:game.chapter+1,hp:Math.min(100,game.player.hp+40),rage:game.player.rage,score:game.score,kills:game.kills,maxCombo:game.maxCombo});const t=THEMES[game.chapter];panel(win?'victory':'chapter',win?'CAMPAIGN COMPLETE':'CHAPTER '+String(game.chapter+1).padStart(2,'0')+' COMPLETE',win?'THE BEAST IS FREE.':'THE WAY IS OPEN.','<p>'+(win?'Containment is broken. You made it out of Castor Woods.':t.boss+' has fallen. Your route to '+THEMES[game.chapter+1].name+' is clear.')+'</p>'+stats()+(win?'':'<p>Next chapter: recover 40 health.</p>'),button(win?'PLAY AGAIN':'NEXT CHAPTER',()=>win?begin():nextChapter(),true),[button('MAIN MENU',showMain)]);if(win)try{localStorage.removeItem(SAVE);}catch{}}
function defeat(){hero=false;panel('defeat','KYLE CRANE HAS FALLEN','ONE MORE CHANCE.','<p>Return to the opening checkpoint of '+THEMES[game.chapter].name+'. Your chapter-entry health, Beast charge, and score are restored.</p>',button('RETRY CHAPTER',()=>{effects=[];floats=[];rings=[];game.retry();camera=-50;showPlay();},true),[button('MAIN MENU',showMain)]);}
function nextChapter(){if(transition||game.state!=='chapter')return;clearInput();$('overlay').hidden=true;$('branding').hidden=true;const t=THEMES[game.chapter+1];$('transition-kicker').textContent='CHAPTER '+String(game.chapter+2).padStart(2,'0')+' / 05';$('transition-name').textContent=t.name;$('chapter-transition').hidden=false;requestAnimationFrame(()=>$('chapter-transition').classList.add('visible'));transition={time:0,loaded:false};menu='transition';}
function updateTransition(dt){if(!transition)return;transition.time+=dt;if(transition.time>.65&&!transition.loaded){game.nextChapter();game.state='transition';transition.loaded=true;camera=-50;effects=[];floats=[];rings=[];}if(transition.time>1.5)$('chapter-transition').classList.remove('visible');if(transition.time>2.08){transition=null;$('chapter-transition').hidden=true;game.state='play';showPlay();showNotice(THEMES[game.chapter].brief+'\n+40 HEALTH',3);}}
function spawnParticles(e){for(let i=0;i<(e.count||15);i++)effects.push({x:e.x,y:e.y,z:e.z||65,vx:(Math.random()-.5)*230,vy:(Math.random()-.5)*95,vz:90+Math.random()*170,life:.3+Math.random()*.25,color:e.color||'#ffc268',size:2+Math.random()*2});}
game.onEvent=e=>{switch(e.type){case'checkpoint':saveRun(e.save);break;case'notice':showNotice(e.text,e.duration);break;case'sound':sound(e.name);break;case'impact':spawnParticles(e);break;case'damage':case'float':floats.push({...e,life:e.type==='damage'?.65:1.1});break;case'shake':shake=Math.max(shake,e.amount);break;case'hurt':hurtFlash=.22;shake=4;break;case'beast':beastFlash=.3;shake=7;rings.push({x:e.x,y:e.y,r:10,max:270,life:.6,color:'#f5b854'});spawnParticles({...e,z:100,count:35});break;case'slam':sound('slam');shake=6;rings.push({x:e.x,y:e.y,r:20,max:210,life:.45,color:'#ef9763'});spawnParticles({...e,z:10,count:20,color:'#b8aa82'});break;case'chapterComplete':result(false);break;case'victory':result(true);break;case'defeat':defeat();break;}};
function resize(){width=canvas.clientWidth;height=canvas.clientHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);touchMode=matchMedia('(pointer:coarse)').matches||width<650||(height<550&&width<1000);zoom=height>width?clamp(width/610,.53,1.1):clamp(height/700,.45,1.55);if(game.state==='play')setPlayUI(true);ctx.imageSmoothingEnabled=false;}
function actorFrame(a){if(a===game.player){if(a.action==='dead')return 7;if(a.action==='hurt')return 6;if(a.action==='kick')return 5;if(a.action==='attack')return a.beast>0?8:a.comboStep===3?4:3;if(a.action==='dodge')return 1+Math.floor(a.walk/44)%2;}else{if(a.hp<=0)return 5;if(a.action==='hurt')return 4;if(a.action==='attack')return 3;}return a.moving?1+Math.floor(a.walk/(a.type==='brute'?58:45))%2:0;}
function sprite(key,frame,x,y,bodyHeight,face=1){const m=catalog.actors[key]||catalog.props[key],im=images[key];if(!m||!im)return;const f=m.frames[frame];if(!f)return;const r=f.rect,s=bodyHeight/m.bodyHeight,anchor=f.anchor;ctx.save();ctx.globalAlpha=1;ctx.translate(Math.round(x),Math.round(y));ctx.scale(face,1);ctx.drawImage(im,r[0],r[1],r[2],r[3],Math.round(-anchor[0]*s),Math.round(-anchor[1]*s),Math.round(r[2]*s),Math.round(r[3]*s));ctx.restore();}
function point(x,y){return{x:(x-camera)*zoom,y:groundBase+(y-125)*zoom*laneScale};}
function scenery(ch=game.chapter,cam=camera){
 const t=THEMES[ch],sceneHorizon=height>width?Math.min(horizon,height*.4):horizon;ctx.fillStyle=t.color;ctx.fillRect(0,0,width,height);
 // Size landmarks in the same world units as Crane (184 high), never by chapter length.
 const layers=[['far',.08,sceneHorizon+30*zoom,Math.max(330*zoom,sceneHorizon+30*zoom)],['mid',.29,sceneHorizon+15*zoom,Math.max(330*zoom,sceneHorizon+15*zoom)],['near',.62,sceneHorizon+36*zoom,Math.max(300*zoom,sceneHorizon+36*zoom)]].map(([name,factor,bottom,h])=>{
  const key=t.id+'-'+name,im=images[key];if(!im)return null;
  const w=Math.max(h*im.width/im.height,width+180*zoom);
  return{key,im,factor,bottom,w,h:w*im.height/im.width};
 }).filter(Boolean);
 const travel=Math.max(1,3*AREA-width/zoom+200)*zoom;
 // Fit camera motion into the available panorama; keep all depths moving at distinct rates.
 const motion=Math.min(1,...layers.map(l=>(l.w-width)/(travel*l.factor)));
 const progress=clamp((cam+100)*zoom,0,travel);
 const drawLayer=l=>{const span=travel*l.factor*motion,left=-(l.w-width-span)/2-progress*l.factor*motion,top=l.bottom-l.h;
  ctx.drawImage(l.im,Math.floor(left),Math.floor(top),Math.ceil(l.w)+1,Math.ceil(l.h)+1);
 };
 const far=layers.find(l=>l.key.endsWith('-far'));if(far)drawLayer(far);
 const floor=images[t.id+'-floor'];if(floor){
  const h=Math.max(280*zoom,height-sceneHorizon+5),w=h*floor.width/floor.height,offset=(cam+150)*zoom,first=Math.floor(offset/w);
  // Repeat terrain at its own scale; reflected edges meet without stretching rocks or floor panels.
  for(let i=first;i*w-offset<width;i++){const x=i*w-offset;ctx.save();ctx.translate(x+(i%2?w:0),sceneHorizon-1);ctx.scale(i%2?-1:1,1);ctx.drawImage(floor,0,0,w+1,h+2);ctx.restore();}
 }
 layers.filter(l=>!l.key.endsWith('-far')).forEach(drawLayer);
 const shade=ctx.createLinearGradient(0,sceneHorizon,0,height);shade.addColorStop(0,'#08170a00');shade.addColorStop(1,'#040f0bc0');ctx.fillStyle=shade;ctx.fillRect(0,sceneHorizon,width,height-sceneHorizon);
}
function shadow(p,w=38){ctx.fillStyle='#07120aa8';ctx.beginPath();ctx.ellipse(p.x,p.y,w*zoom,9*zoom,0,0,Math.PI*2);ctx.fill();}
function text(str,x,y,size=13,color='#f0d8a5',align='center'){ctx.font='700 '+Math.max(8,size)+'px Oxanium,Arial';ctx.textAlign=align;ctx.lineWidth=3;ctx.strokeStyle='#101b17de';ctx.strokeText(str,x,y);ctx.fillStyle=color;ctx.fillText(str,x,y);}
function drawActor(a){const p=point(a.x,a.y),isPlayer=a===game.player,h=isPlayer?184:a.height;if(p.x<-300*zoom||p.x>width+300*zoom)return;shadow(p,a.type==='brute'?55:37);if(!isPlayer&&a.hp>0&&a.action==='windup'){const progress=1-a.timer/a.duration,r=a.kind==='slam'?205:a.kind==='leap'?100:64;ctx.strokeStyle=a.kind==='swing'?'#eac583':'#fb7750';ctx.lineWidth=2*zoom;ctx.beginPath();ctx.ellipse(p.x,p.y,r*zoom,(a.kind==='slam'?91*laneScale:20)*zoom,0,-Math.PI/2,-Math.PI/2+Math.PI*2*progress);ctx.stroke();text(a.kind==='slam'?'DODGE':a.kind==='leap'?'LUNGE':'!',p.x,p.y-(h+16)*zoom,a.kind==='swing'?24*zoom:13*zoom,'#ffbf7b');}if(isPlayer&&a.beast>0){const g=ctx.createRadialGradient(p.x,p.y-90*zoom,10,p.x,p.y-90*zoom,140*zoom);g.addColorStop(0,'#ffaa3530');g.addColorStop(1,'#ffaa3500');ctx.fillStyle=g;ctx.fillRect(p.x-160*zoom,p.y-250*zoom,320*zoom,280*zoom);}sprite(isPlayer?'crane':a.type,actorFrame(a),p.x,p.y,h*zoom,a.face);if(!isPlayer&&a.hp>0&&a.hp<a.maxHP&&!a.boss){ctx.fillStyle='#0e1b14';ctx.fillRect(p.x-23*zoom,p.y-(h+8)*zoom,46*zoom,4*zoom);ctx.fillStyle='#d49454';ctx.fillRect(p.x-23*zoom,p.y-(h+8)*zoom,46*zoom*a.hp/a.maxHP,4*zoom);}if(isPlayer&&a.invuln>0){ctx.strokeStyle='#f8d398a0';ctx.lineWidth=1.4*zoom;ctx.beginPath();ctx.ellipse(p.x,p.y,41*zoom,10*zoom,0,0,Math.PI*2);ctx.stroke();}}
function drawProp(p){const q=point(p.x,p.y);if(q.x<-200*zoom||q.x>width+200*zoom)return;shadow(q,34);sprite(p.theme+'-prop',p.state,q.x,q.y,THEMES[game.chapter].propHeight*zoom);}
function drawPickup(item){const p=point(item.x,item.y),health=item.type==='health';const y=p.y-(31+Math.sin(game.time*4+item.id)*4)*zoom;ctx.fillStyle='#102519e8';ctx.strokeStyle=health?'#bdd790':'#edac53';ctx.lineWidth=1;ctx.fillRect(p.x-22*zoom,y-12*zoom,44*zoom,24*zoom);ctx.strokeRect(p.x-22*zoom,y-12*zoom,44*zoom,24*zoom);text(health?'+HP':'BEAST',p.x,y+4*zoom,10*zoom,health?'#d5eeb1':'#ffc775');}
function layout(dt){const portrait=height>width;horizon=height*(portrait?.49:.49);const back=horizon+(portrait?100:52)*zoom,front=Math.min(height-(touchMode?(portrait?168:91):51),height*.87);laneScale=clamp((front-back)/((LANES.max-LANES.min)*zoom),.4,.88);groundBase=back+(125-LANES.min)*laneScale*zoom;const view=width/zoom,target=clamp(game.player.x-view*.4,-100,3*AREA-view+100);camera+=(target-camera)*Math.min(1,dt*6);camera=clamp(camera,game.player.x-view+Math.min(110,view*.23),game.player.x-Math.min(110,view*.23));}
function renderHero(dt){heroTime+=dt;const portrait=height>width;horizon=height*(portrait?.60:.57);groundBase=height*.88;const cam=320+Math.sin(heroTime*.10)*55;scenery(0,cam);const hx=width*(portrait?.61:.61),hy=height*(portrait?.90:.855),hh=height*(portrait?.32:.50);ctx.save();ctx.fillStyle='#06110bab';ctx.beginPath();ctx.ellipse(hx,hy,hh*.25,hh*.045,0,0,Math.PI*2);ctx.fill();sprite('crane',0,hx,hy,hh,1);const ex=width*.875,eh=height*.31;if(!portrait){ctx.beginPath();ctx.ellipse(ex,hy-10*zoom,eh*.24,eh*.045,0,0,Math.PI*2);ctx.fill();sprite('volatile',0,ex,hy-10*zoom,eh,-1);}ctx.restore();}
function render(dt){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,width,height);if(hero){renderHero(dt);return;}layout(dt);ctx.save();if(shake>0&&game.state==='play')ctx.translate((Math.random()-.5)*shake*zoom,(Math.random()-.5)*shake*.5*zoom);scenery();const objects=[...game.props.map(p=>({y:p.y,draw:()=>drawProp(p)})),...game.enemies.filter(e=>e.hp>0||e.deadTime<4).map(a=>({y:a.y,draw:()=>drawActor(a)})),{y:game.player.y,draw:()=>drawActor(game.player)}];objects.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());game.pickups.forEach(drawPickup);for(const ring of rings){const p=point(ring.x,ring.y);ctx.strokeStyle=ring.color;ctx.globalAlpha=ring.life*1.5;ctx.lineWidth=3*zoom;ctx.beginPath();ctx.ellipse(p.x,p.y,ring.r*zoom,ring.r*zoom*.35,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}for(const e of effects){const p=point(e.x,e.y);ctx.globalAlpha=Math.min(1,e.life*3);ctx.fillStyle=e.color;ctx.fillRect(p.x,p.y-e.z*zoom,e.size*zoom,e.size*zoom);}ctx.globalAlpha=1;for(const f of floats){const p=point(f.x,f.y);ctx.globalAlpha=Math.min(1,f.life*2);text(f.text,p.x,p.y-f.z*zoom,12*zoom,f.color);}ctx.globalAlpha=1;
 const edge=(game.frontier+1)*AREA;const current=game.areas[game.frontier];if(current?.cleared||game.frontier>game.area){const x=Math.min(width-45*zoom,(edge-70-camera)*zoom);if(x>width*.2)text('GO →',x,horizon+85*zoom,16*zoom,'#eac77e');}else if(game.player.x>edge-250){const x=(edge-65-camera)*zoom;ctx.strokeStyle='#e7a96d80';ctx.setLineDash([7*zoom,8*zoom]);ctx.beginPath();ctx.moveTo(x,groundBase-110*zoom);ctx.lineTo(x,groundBase+100*zoom);ctx.stroke();ctx.setLineDash([]);text('CLEAR THE INFECTED',Math.min(width-85,x),groundBase-135*zoom,10*zoom,'#f1bc7e');}ctx.restore();if(hurtFlash>0){ctx.fillStyle='rgba(169,38,19,'+hurtFlash*.55+')';ctx.fillRect(0,0,width,height);}if(beastFlash>0){ctx.fillStyle='rgba(255,184,61,'+beastFlash*.65+')';ctx.fillRect(0,0,width,height);}}
function updateHUD(){const p=game.player,t=THEMES[game.chapter],b=game.boss;$('health-label').textContent=Math.ceil(p.hp)+' / 100';$('health-fill').style.width=p.hp+'%';$('health-fill').style.background=p.hp<30?'#d67c53':'#a9bb6c';$('rage-fill').style.width=(p.beast>0?p.beast/7.5*100:p.rage)+'%';$('rage-label').textContent=p.beast>0?'BEAST UNLEASHED':p.rage>=100?'BEAST READY · E':'BEAST';$('rage-value').textContent=p.beast>0?p.beast.toFixed(1)+'s':Math.floor(p.rage)+'%';$('chapter-label').textContent='CH. '+String(game.chapter+1).padStart(2,'0')+' / 05 · AREA '+String(game.area+1).padStart(2,'0')+' / 03';$('area-label').textContent=t.areas[game.area];$('objective-label').textContent=game.remaining?game.remaining+' INFECTED REMAINING':'AREA CLEAR · MOVE RIGHT';$('score').textContent=String(game.score).padStart(6,'0');$('boss-bar').hidden=!b;if(b){$('boss-name').textContent=t.boss;$('boss-hp').textContent=Math.ceil(b.hp)+' / '+b.maxHP;$('boss-fill').style.width=b.hp/b.maxHP*100+'%';}$('combo').hidden=game.combo<2;if(game.combo>=2)$('combo').querySelector('b').textContent=game.combo+'×';touchButtons.find(b=>b.dataset.action==='beast').classList.toggle('ready',p.rage>=100);}
function updateFX(dt){shake=Math.max(0,shake-dt*15);hurtFlash=Math.max(0,hurtFlash-dt);beastFlash=Math.max(0,beastFlash-dt);for(const e of effects){e.life-=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;e.z+=e.vz*dt;e.vz-=500*dt;}effects=effects.filter(e=>e.life>0);for(const f of floats){f.life-=dt;f.z+=dt*46;}floats=floats.filter(f=>f.life>0);for(const r of rings){r.life-=dt;r.r+=(r.max-r.r)*dt*9;}rings=rings.filter(r=>r.life>0);}
function tick(time){const dt=Math.min(.04,Math.max(0,(time-last)/1000||.016));last=time;if(!document.hidden){if(transition)updateTransition(dt);if(game.state==='play'){const x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stickX,y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stickY;game.step(dt,{x,y,attack:keys.has('KeyJ')||touched.has('attack'),kick:keys.has('KeyK')||touched.has('kick'),actions:queued.splice(0)});updateFX(dt);updateHUD();}else if(game.state==='dying'){game.step(dt);updateFX(dt);}if(noticeTime>0){noticeTime-=dt;if(noticeTime<=0)$('notice').classList.remove('show');}render(dt);}requestAnimationFrame(tick);}
function fullscreen(){if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>showNotice('FULLSCREEN IS UNAVAILABLE HERE',2));}
const mapped=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyJ','KeyK','KeyE','KeyL','Space','Escape','KeyP','KeyM','KeyF']);
window.addEventListener('keydown',e=>{if(!mapped.has(e.code))return;if(game.state==='play'||e.code==='Space')e.preventDefault();if(e.repeat)return;initAudio();if(e.code==='KeyM')toggleSound();else if(e.code==='KeyF')fullscreen();else if(e.code==='Escape'||e.code==='KeyP'){if(menu==='pause'){game.resume();showPlay();}else if(game.state==='play')pause();else if(menu==='help'){if(helpBack==='pause'){game.resume();pause();}else showMain();}}else if(game.state==='play'){keys.add(e.code);if(e.code==='KeyJ')queued.push('attack');if(e.code==='KeyK')queued.push('kick');if(e.code==='Space')queued.push('dodge');if(e.code==='KeyE'||e.code==='KeyL')queued.push('beast');}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();if(game.state==='play')pause();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden&&game.state==='play')pause();last=performance.now();});window.addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);document.addEventListener('fullscreenchange',resize);
const stick=$('joystick');function moveStick(e){const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.35,length=Math.hypot(dx,dy),scale=Math.min(1,max/Math.max(1,length));stickX=length<8?0:dx*scale/max;stickY=length<8?0:dy*scale/max;$('stick-knob').style.transform='translate('+dx*scale+'px,'+dy*scale+'px)';}
stick.addEventListener('pointerdown',e=>{if(stickPointer!==null)return;initAudio();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)moveStick(e);});function releaseStick(e){if(e.pointerId!==stickPointer)return;stickPointer=null;stickX=stickY=0;$('stick-knob').style.transform='';}['pointerup','pointercancel','lostpointercapture'].forEach(t=>stick.addEventListener(t,releaseStick));
touchButtons.forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();initAudio();b.setPointerCapture(e.pointerId);b.classList.add('pressed');const a=b.dataset.action;if(a==='attack'||a==='kick')touched.add(a);queued.push(a);});['pointerup','pointercancel','lostpointercapture'].forEach(t=>b.addEventListener(t,()=>{touched.delete(b.dataset.action);b.classList.remove('pressed');}));});
$('start').onclick=()=>loadError?loadAssets():begin();$('continue').onclick=resumeRun;$('help').onclick=()=>help('main');$('pause').onclick=pause;$('sound').onclick=toggleSound;$('fullscreen').onclick=fullscreen;
async function loadAssets(){loadError=false;loadDone=false;$('start').disabled=true;const entries=Object.entries(catalog.files),total=entries.length+1;let done=0;function progress(){const percent=Math.floor(++done/total*100);$('start-label').textContent='LOADING '+percent+'%';$('load-bar').style.transform='scaleX('+percent/100+')';}try{await Promise.all([...entries.map(([key,url])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[key]=im;progress();resolve();};im.onerror=()=>reject(new Error('Could not load '+url));im.src=url;})),document.fonts.load('700 16px Oxanium').then(progress)]);loadDone=true;$('start-label').textContent='START GAME';$('start').disabled=false;$('load-bar').style.transform='scaleX(1)';if(menu==='main')showMain();}catch(error){loadError=true;$('start-label').textContent='RETRY LOADING';$('start').disabled=false;showNotice('Some artwork did not load. Tap Retry Loading.',8);console.error(error);}}

resize();updateSound();loadAssets();requestAnimationFrame(tick);
})();
