(() => {
'use strict';
const $ = id => document.getElementById(id);
const canvas = $('game'), ctx = canvas.getContext('2d', {alpha:false});
const chapters = [
 {key:'jacinto',name:'JACINTO',areas:['HOSPITAL APPROACH','BROKEN BOULEVARD','EVACUATION LINE'],boss:'LOCUST CAPTAIN',bossType:'drone',color:'#8dafbc'},
 {key:'convoy',name:'LANDOWN',areas:['DERRICK YARD','CONVOY AMBUSH','THE DRILL SITE'],boss:'KANTUS HERALD',bossType:'kantus',color:'#deaa67'},
 {key:'hollow',name:'THE HOLLOW',areas:['FIRST DESCENT','CRYSTAL CAVERNS','DEEPWATER BRIDGE'],boss:'HOLLOW GUARDIAN',bossType:'drone',color:'#76c9d8'},
 {key:'nexus',name:'NEXUS',areas:['OUTER SANCTUM','LOCUST ALTAR','THE PALACE GATE'],boss:'HIGH PRIEST',bossType:'kantus',color:'#db746b'},
 {key:'sinkhole',name:'LAST STAND',areas:['FLOODED DISTRICT','COLLAPSING STREETS','SKORGE'],boss:'SKORGE',bossType:'skorge',color:'#b7d0c4'}
];
const images={}, meta=window.GAME_ART, keys=new Set(), touchKeys=new Set(), taps=new Set();
const files=['marcus','drone','kantus','skorge',...chapters.flatMap(c=>['far','mid','near','floor','prop'].map(d=>c.key+'-'+d))];
let W=1280,H=720,VW=1280,VH=720,S=1,DPR=1,portrait=false;
let mode='main',menuOrigin='main',loaded=false,loadFailed=false,active=false,chapter=0,area=0,camera=0;
let player, enemies=[], encounters=[], props=[], drops=[], particles=[], shots=[], corpses=[], time=0,ambient=0,shake=0,freeze=0;
let score=0,kills=0,comboHits=0,comboLife=0,chainIndex=0,chainLife=0,areaCleared=false,calloutLife=0;
let transitionTime=0,transitionDone=false,transitionTarget=0,entry={score:0,kills:0,reserve:72},nextId=1;
let saved=null,muted=false,audioContext=null,stickX=0,stickY=0,stickId=null,mouseAim=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a), len=(x,y)=>Math.hypot(x,y);
const num=v=>String(v).padStart(2,'0');
const currentArea=()=>player?Math.min(area,Math.floor((player.x+25)/1100)):area;
try {const q=JSON.parse(localStorage.getItem('g55-gears2-checkpoint'));if(q&&Number.isInteger(q.chapter)&&q.chapter>=0&&q.chapter<5&&Number.isFinite(q.score)&&Number.isFinite(q.kills)&&Number.isFinite(q.reserve))saved=q;muted=localStorage.getItem('g55-gears2-muted')==='1';}catch(e){}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);portrait=W/H<.75;VH=portrait?850:720;S=H/VH;VW=W/S;ctx.imageSmoothingEnabled=true;if(player)camera=clamp(player.x-VW*.4,0,Math.max(0,3300-VW));}
addEventListener('resize',resize);resize();
const isTouch=matchMedia('(pointer:coarse)').matches || navigator.maxTouchPoints>0;
document.body.classList.toggle('touch',isTouch);
$('more').href='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
function sound(kind){if(muted)return;try{if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const a=audioContext,t=a.currentTime,o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);const tones={hit:[125,42,.10,'triangle',.11],shot:[185,40,.09,'sawtooth',.065],saw:[82,135,.27,'sawtooth',.07],dodge:[180,55,.13,'sine',.05],pickup:[550,1050,.16,'sine',.08],alert:[145,120,.14,'square',.035],reload:[270,370,.12,'triangle',.05],clear:[380,760,.35,'triangle',.07]};const v=tones[kind]||tones.hit;o.type=v[3];o.frequency.setValueAtTime(v[0],t);o.frequency.exponentialRampToValueAtTime(v[1],t+v[2]);g.gain.setValueAtTime(v[4],t);g.gain.exponentialRampToValueAtTime(.001,t+v[2]);o.start(t);o.stop(t+v[2]);}catch(e){}}
function updateSound(){$('sound').textContent=muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound');}updateSound();
$('sound').onclick=()=>{muted=!muted;updateSound();try{localStorage.setItem('g55-gears2-muted',muted?'1':'0');}catch(e){}if(!muted)sound('pickup');};
$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{});};
function clearInput(){keys.clear();touchKeys.clear();taps.clear();stickX=stickY=0;stickId=null;$('stickKnob').style.transform='';document.querySelectorAll('[data-action]').forEach(b=>b.classList.remove('active'));}
function showMenu(which){mode=which;clearInput();document.body.classList.remove('playing');document.body.classList.toggle('submenu',which!=='main');$('menu').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('pause').hidden=true;$('heroTitle').hidden=which!=='main';$('genre').hidden=which!=='main';$('menuTitle').hidden=which==='main';$('help').hidden=which!=='help';$('main').hidden=which==='main';$('how').hidden=which==='help';$('continue').hidden=true;$('loadFill').style.display=loaded?'none':'block';$('primary').disabled=!loaded&&!loadFailed;
 let title='',text='',button='';
 if(which==='main'){button=loadFailed?'RETRY LOADING':loaded?'START GAME':'LOADING 0%';text='Take the fight underground.';$('eyebrow').textContent='DELTA SQUAD // JACINTO';$('continue').hidden=!(active||saved);$('continue').textContent=active?'CONTINUE RUN':saved?'CONTINUE · CHAPTER '+num(saved.chapter+1):'CONTINUE';}
 if(which==='pause'){title='HOLD YOUR POSITION';text=chapters[chapter].name+' · '+chapters[chapter].areas[currentArea()]+'\nYour campaign is paused.';button='RESUME';}
 if(which==='help'){title='HOW TO PLAY';button='BACK';text='';}
 if(which==='chapter'){title=chapters[chapter].name+' SECURED';text='Chapter '+num(chapter+1)+' complete.\nHealth and Lancer supplies restored at the next checkpoint.';button='NEXT CHAPTER';}
 if(which==='defeat'){title='SQUAD DOWN';text='Regroup at the chapter checkpoint.\nScore and supplies return to your chapter entry.';button='RETRY CHAPTER';}
 if(which==='victory'){title='DELTA PREVAILS';text='Five chapters cleared. Skorge defeated.\n'+kills+' Locust eliminated · '+String(score).padStart(6,'0')+' points';button='PLAY AGAIN';}
 if(which!=='main')$('eyebrow').textContent=which==='help'?'FIELD MANUAL':'GEARS OF WAR 2 · BEAT EM UP';
 $('menuTitle').textContent=title;$('menuText').textContent=text;$('menuText').hidden=which==='help';$('primaryText').textContent=button;$('main').textContent='MAIN MENU';
}
function resume(){if(!active)return;mode='play';clearInput();document.body.classList.add('playing');document.body.classList.remove('submenu');$('menu').hidden=true;$('hud').hidden=false;$('touch').hidden=!isTouch;$('pause').hidden=false;}
$('primary').onclick=()=>{sound('pickup');if(mode==='main'){if(loadFailed){loadAssets();return;}startGame(0);}else if(mode==='pause')resume();else if(mode==='help'){if(menuOrigin==='play')showMenu('pause');else showMenu(menuOrigin);}else if(mode==='chapter')beginChapter(chapter+1);else if(mode==='defeat')beginChapter(chapter,true);else if(mode==='victory')startGame(0);};
$('continue').onclick=()=>{sound('pickup');if(active)resume();else if(saved)startGame(saved.chapter,saved);};
$('how').onclick=()=>{menuOrigin=mode;showMenu('help');};$('main').onclick=()=>showMenu('main');$('pause').onclick=()=>{if(mode==='play')showMenu('pause');};
function pause(){if(mode==='play')showMenu('pause');else if(mode==='pause')resume();}
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyJ','KeyK','KeyL','KeyR','Escape','KeyP'].includes(e.code))e.preventDefault();if((e.code==='Escape'||e.code==='KeyP')&&!e.repeat){pause();return;}if(mode==='play'){keys.add(e.code);if(['KeyJ','KeyK','KeyL','KeyR','Space'].includes(e.code)&&!e.repeat)taps.add(e.code);}});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{clearInput();if(mode==='play')showMenu('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(mode==='play')showMenu('pause');}});
const actions={melee:'KeyJ',saw:'KeyK',shoot:'KeyL',reload:'KeyR',dodge:'Space'};
document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='play')return;b.setPointerCapture(e.pointerId);touchKeys.add(actions[b.dataset.action]);taps.add(actions[b.dataset.action]);b.classList.add('active');});for(const n of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(n,()=>{touchKeys.delete(actions[b.dataset.action]);b.classList.remove('active');});});
function moveStick(e){const r=$('stick').getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=r.width*.34,d=len(dx,dy),k=d>m?m/d:1;stickX=clamp(dx/m,-1,1);stickY=clamp(dy/m,-1,1);if(len(stickX,stickY)>.999){const h=len(stickX,stickY);stickX/=h;stickY/=h;}$('stickKnob').style.transform=`translate(${dx*k}px,${dy*k}px)`;}
$('stick').addEventListener('pointerdown',e=>{if(mode!=='play'||stickId!==null)return;stickId=e.pointerId;$('stick').setPointerCapture(e.pointerId);moveStick(e);});$('stick').addEventListener('pointermove',e=>{if(e.pointerId===stickId)moveStick(e);});for(const n of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(n,e=>{if(e.pointerId===stickId){stickId=null;stickX=stickY=0;$('stickKnob').style.transform='';}});
const pressed=c=>keys.has(c)||touchKeys.has(c)||taps.has(c);
function announce(t,d=2){$('callout').textContent=t;calloutLife=d;}
function checkpoint(){saved={chapter,score:entry.score,kills:entry.kills,reserve:entry.reserve};try{localStorage.setItem('g55-gears2-checkpoint',JSON.stringify(saved));}catch(e){}}
function startGame(c,s){score=s?s.score:0;kills=s?s.kills:0;entry={score,kills,reserve:s?s.reserve:72};active=true;beginChapter(c,true);}
function beginChapter(c,retry=false){clearInput();transitionTarget=c;transitionTime=1.7;transitionDone=false;mode='transition';$('transition').style.opacity='1';$('transitionNumber').textContent='CHAPTER '+num(c+1)+' / 05';$('transitionTitle').textContent=chapters[c].name;$('menu').hidden=true;$('hud').hidden=true;$('touch').hidden=true;$('pause').hidden=true;document.body.classList.add('playing');if(!retry)entry={score,kills,reserve:Math.max(60,player.reserve+24)};}
function initChapter(c){chapter=c;area=0;score=entry.score;kills=entry.kills;time=0;camera=0;enemies=[];props=[];drops=[];shots=[];corpses=[];particles=[];comboHits=0;comboLife=0;chainIndex=0;chainLife=0;areaCleared=false;player={x:180,y:535,face:1,hp:100,maxHp:100,fury:100,mag:12,reserve:entry.reserve,state:'idle',t:0,duration:0,hitDone:false,inv:1,walk:0,walkMove:false,shotCd:0,dodgeCd:0,frame:0};prepareChapter();checkpoint();spawnArea();updateHud();}
function spawnEnemy(type,x,y,boss=false,roster=enemies){const hp=boss?(type==='skorge'?330:210+chapter*20):(type==='kantus'?52+chapter*4:54+chapter*5);const e={id:nextId++,type,x,y,face:-1,hp,maxHp:hp,boss,height:type==='skorge'?222:type==='kantus'?180:162,state:'idle',t:rand(.4,1.5),cool:rand(.5,1.5),walk:0,walkMove:false,hit:0,frame:0,phase:0,targetX:0,targetY:0};if(boss)e.height*=1.15;roster.push(e);return e;}
function prepareChapter(){encounters=Array.from({length:3},()=>[]);for(let a=0;a<3;a++){const start=a*1100,count=3+Math.min(chapter,2)+(a===1?1:0);for(let i=0;i<count;i++){const type=chapter>0&&i%3===2?'kantus':'drone';spawnEnemy(type,start+510+i*100,455+(i%3)*68,false,encounters[a]);}if(a===2)spawnEnemy(chapters[chapter].bossType,start+930,525,true,encounters[a]);for(let i=0;i<3;i++)props.push({id:nextId++,x:start+370+i*295,y:460+(i%2)*138,hp:40,state:0,dropped:false,kind:chapters[chapter].key+'-prop'});}}
function spawnArea(){areaCleared=false;enemies=encounters[area];announce(area===0?'CHAPTER '+num(chapter+1)+' · '+chapters[chapter].name:chapters[chapter].areas[area],2.8);}
function emit(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:rand(-160,160),vy:rand(-210,20),t:rand(.18,.42),max:.42,color});}
function floating(x,y,text,color='#e3d8ba'){particles.push({x,y,vx:0,vy:-44,t:.8,max:.8,text,color});}
function autoFace(range=170){let target=null,dist=range;for(const e of enemies){let d=Math.abs(e.x-player.x);if(e.hp>0&&Math.abs(e.y-player.y)<53&&d<dist){target=e;dist=d;}}if(target)player.face=target.x<player.x?-1:1;}
function setAction(state,duration){player.state=state;player.t=duration;player.duration=duration;player.hitDone=false;}
function action(){if(player.state==='hurt'||player.state==='dead'||player.state==='dodge'||player.state==='saw')return;if(pressed('Space')&&player.dodgeCd<=0){setAction('dodge',.32);player.inv=.48;player.dodgeCd=.95;player.dodgeX=(pressed('KeyA')||pressed('ArrowLeft')?-1:pressed('KeyD')||pressed('ArrowRight')?1:stickX)||player.face;player.dodgeY=(pressed('KeyW')||pressed('ArrowUp')?-1:pressed('KeyS')||pressed('ArrowDown')?1:stickY);sound('dodge');return;}if(player.state!=='idle'&&player.state!=='walk')return;if(pressed('KeyR')&&player.mag<12&&player.reserve>0){setAction('reload',1.1);sound('reload');return;}if(pressed('KeyK')&&player.fury>=35){autoFace();player.fury-=35;setAction('saw',.7);player.inv=.38;sound('saw');return;}if(pressed('KeyJ')){autoFace();chainIndex=chainLife>0?(chainIndex+1)%3:0;chainLife=.9;setAction('melee',[.29,.33,.43][chainIndex]);return;}if(pressed('KeyL')&&player.shotCd<=0){if(player.mag>0){autoFace(600);player.mag--;player.shotCd=.22;setAction('shoot',.20);shootPlayer();}else if(player.reserve>0){setAction('reload',1.1);sound('reload');}else announce('BREAK SUPPLIES FOR AMMO',.8);}}
function damageEnemy(e,amount,knock=18){if(e.hp<=0)return;e.hp=Math.max(0,e.hp-amount);e.hit=.16;e.x=clamp(e.x+player.face*knock,35,(area+1)*1100-35);e.state='hurt';e.t=e.boss?.15:.32;e.cool=Math.max(e.cool,.32);score+=amount*4;comboHits++;comboLife=2.5;player.fury=Math.min(100,player.fury+5);emit(e.x,e.y-e.height*.52,'#e7b48a',6);floating(e.x,e.y-e.height,String(amount));shake=Math.max(shake,3);freeze=.026;sound('hit');if(e.hp===0){kills++;score+=e.boss?1000:150;e.state='dead';e.t=0;corpses.push({type:e.type,x:e.x,y:e.y,face:e.face,height:e.height,t:3});if(e.boss||kills%3===0)drops.push({x:e.x,y:e.y,kind:e.boss?'health':kills%2?'ammo':'health',t:0});}}
function hitProp(p,damage){if(p.hp<=0)return;p.hp=Math.max(0,p.hp-damage);p.state=p.hp<=0?2:1;emit(p.x,p.y-40,'#c7b397',7);if(p.hp===0&&!p.dropped){p.dropped=true;score+=75;drops.push({x:p.x,y:p.y,kind:p.id%2?'ammo':'health',t:0});sound('hit');}}
function meleeHit(saw=false){const reach=saw?147:chainIndex===2?132:109, damage=saw?67:[19,23,32][chainIndex];let hit=false;for(const e of enemies)if(e.hp>0&&Math.abs(e.y-player.y)<50&&Math.abs(e.x-player.x)<reach&&((e.x-player.x)*player.face>-26)){damageEnemy(e,damage,saw?35:chainIndex===2?36:15);hit=true;}for(const p of props)if(p.hp>0&&Math.abs(p.y-player.y)<55&&Math.abs(p.x-player.x)<reach&&(p.x-player.x)*player.face>-35)hitProp(p,saw?60:23);if(hit)shake=saw?8:4;else sound('dodge');}
function shootPlayer(){const front=enemies.filter(e=>e.hp>0&&Math.abs(e.y-player.y)<36&&(e.x-player.x)*player.face>0&&Math.abs(e.x-player.x)<680).sort((a,b)=>Math.abs(a.x-player.x)-Math.abs(b.x-player.x));const cover=props.filter(p=>p.hp>0&&Math.abs(p.y-player.y)<36&&(p.x-player.x)*player.face>0&&Math.abs(p.x-player.x)<680).sort((a,b)=>Math.abs(a.x-player.x)-Math.abs(b.x-player.x));const e=front[0],p=cover[0];let end=player.x+player.face*620;if(p&&(!e||Math.abs(p.x-player.x)<Math.abs(e.x-player.x))){hitProp(p,22);end=p.x;}else if(e){damageEnemy(e,18,7);end=e.x;}shots.push({x:player.x+player.face*50,y:player.y-89,x2:end,y2:player.y-86,t:.08,player:true});sound('shot');shake=Math.max(shake,1.8);}
function hurtPlayer(damage,sourceX){if(player.inv>0||player.hp<=0||mode!=='play')return;player.hp=Math.max(0,player.hp-damage);player.inv=.85;player.x=clamp(player.x+(sourceX<player.x?1:-1)*25,20,(area+1)*1100-36);setAction('hurt',.24);comboLife=0;comboHits=0;shake=8;emit(player.x,player.y-83,'#d55449');sound('hit');if(player.hp===0){setAction('dead',1.1);}}
function updatePlayer(dt){player.inv=Math.max(0,player.inv-dt);player.shotCd-=dt;player.dodgeCd-=dt;chainLife-=dt;player.fury=Math.min(100,player.fury+dt*1.8);player.walkMove=false;if(player.state==='dead'){player.t-=dt;if(player.t<=0){active=false;showMenu('defeat');}return;}action();taps.clear();let dx=(pressed('KeyD')||pressed('ArrowRight')?1:0)-(pressed('KeyA')||pressed('ArrowLeft')?1:0)+stickX,dy=(pressed('KeyS')||pressed('ArrowDown')?1:0)-(pressed('KeyW')||pressed('ArrowUp')?1:0)+stickY;let mag=len(dx,dy);if(mag>1){dx/=mag;dy/=mag;}const oldX=player.x,oldY=player.y;
 if(player.state==='dodge'){player.x+=player.dodgeX*550*dt;player.y+=player.dodgeY*220*dt;}else if(player.state==='idle'||player.state==='walk'){player.x+=dx*225*dt;player.y+=dy*154*dt;if(Math.abs(dx)>.08)player.face=dx>0?1:-1;}
 player.x=clamp(player.x,20,(area+1)*1100-(areaCleared?0:40));player.y=clamp(player.y,434,626);const moved=len(player.x-oldX,player.y-oldY);if(moved>.1){player.walk+=moved;player.walkMove=true;}
 if(player.state!=='idle'&&player.state!=='walk'){player.t-=dt;let elapsed=player.duration-player.t;if(player.state==='melee'&&!player.hitDone&&elapsed>[.10,.12,.16][chainIndex]){player.hitDone=true;meleeHit();}if(player.state==='saw'&&!player.hitDone&&elapsed>.18){player.hitDone=true;meleeHit(true);}if(player.t<=0){if(player.state==='reload'){const n=Math.min(12-player.mag,player.reserve);player.mag+=n;player.reserve-=n;sound('reload');}player.state='idle';}}else player.state=moved>.1?'walk':'idle';
 if(areaCleared&&player.x>=(area+1)*1100-25){if(area===2){active=false;if(chapter<4){saved={chapter:chapter+1,score,kills,reserve:Math.max(60,player.reserve+24)};try{localStorage.setItem('g55-gears2-checkpoint',JSON.stringify(saved));}catch(e){}}showMenu(chapter===4?'victory':'chapter');if(chapter===4){saved=null;try{localStorage.removeItem('g55-gears2-checkpoint');}catch(e){}}}else{area++;spawnArea();}}
}
function fireEnemy(e){const speed=e.boss?285:245,angle=Math.atan2(player.y-e.y,player.x-e.x);const angles=e.boss?[-.18,0,.18]:[0];for(const offset of angles)shots.push({x:e.x,y:e.y,dx:Math.cos(angle+offset)*speed,dy:Math.sin(angle+offset)*speed,t:3.8,player:false,damage:e.boss?13:9});sound('shot');}
function updateEnemy(e,dt){if(e.hp<=0)return;e.t-=dt;e.cool-=dt;e.hit=Math.max(0,e.hit-dt);e.walkMove=false;const dx=player.x-e.x,dy=player.y-e.y;e.face=dx<0?-1:1;let previousX=e.x,previousY=e.y;
 if(e.state==='hurt'){if(e.t<=0)e.state='idle';return;}
 if(e.state==='windup'){if(e.t<=0){e.state='attack';e.t=e.attackKind==='charge'?.56:.35;e.didHit=false;if(e.attackKind==='ranged')fireEnemy(e);else if(e.attackKind==='summon'){fireEnemy(e);if(enemies.filter(a=>a.hp>0).length<5)spawnEnemy('drone',clamp(e.x+e.face*120,50,(area+1)*1100-50),490);}}return;}
 if(e.state==='attack'){if(e.attackKind==='charge'){e.x+=e.chargeFace*(e.type==='skorge'?450:335)*dt;if(Math.abs(player.x-e.x)<70&&Math.abs(player.y-e.y)<48&&!e.didHit){hurtPlayer(e.boss?18:12,e.x);e.didHit=true;}}else if(e.attackKind==='slam'){if(!e.didHit&&e.t<.20){e.didHit=true;emit(e.x,e.y-10,'#bb9a8f',18);if(Math.abs(player.x-e.x)<150&&Math.abs(player.y-e.y)<78)hurtPlayer(20,e.x);shake=4;}}else if(e.attackKind==='melee'&&!e.didHit&&e.t<.22){e.didHit=true;if(Math.abs(player.x-e.x)<98&&Math.abs(player.y-e.y)<48)hurtPlayer(e.boss?17:10,e.x);}if(e.t<=0){e.state='recover';e.t=e.boss?.75:.6;e.cool=e.boss?.8:1.2;}e.x=clamp(e.x,35,(area+1)*1100-35);return;}
 if(e.state==='recover'){if(e.t<=0)e.state='idle';return;}
 const ranged=e.type==='kantus',visible=e.x>camera+10&&e.x<camera+VW-10;let attack=false;if(ranged){if(visible&&Math.abs(dx)<450&&Math.abs(dy)<110&&e.cool<=0){e.attackKind=e.boss&&chapter===3&&e.phase%3===2?'summon':'ranged';attack=true;}else{if(Math.abs(dx)>Math.min(275,VW*.58))e.x+=Math.sign(dx)*95*dt;else if(Math.abs(dx)<155)e.x-=Math.sign(dx)*72*dt;e.y+=clamp(dy,-1,1)*55*dt;}}
 else{if(visible&&e.boss&&e.cool<=0&&Math.abs(dx)<560&&Math.abs(dx)>135&&Math.abs(dy)<45){e.attackKind='charge';attack=true;}else if(Math.abs(dx)<87&&Math.abs(dy)<38&&e.cool<=0){e.attackKind=e.boss&&e.phase%3===2?'slam':'melee';attack=true;}else {const speed=e.boss?116:105;if(Math.abs(dx)>65)e.x+=Math.sign(dx)*speed*dt;if(Math.abs(dy)>12)e.y+=Math.sign(dy)*73*dt;}}
 if(attack){const busy=enemies.filter(a=>a!==e&&['windup','attack'].includes(a.state)).length;if(busy<2){e.state='windup';e.t=e.attackKind==='charge'?.75:e.attackKind==='slam'?.9:.67;e.chargeFace=e.face;e.targetY=player.y;e.targetX=player.x;e.phase++;sound('alert');}}
 if(e.state!=='windup'){for(const o of enemies)if(o!==e&&o.hp>0&&Math.abs(e.y-o.y)<24&&Math.abs(e.x-o.x)<48){e.x+=(e.x>=o.x?1:-1)*30*dt;e.y+=(e.id%2?1:-1)*16*dt;}}
 e.x=clamp(e.x,32,(area+1)*1100-32);e.y=clamp(e.y,435,626);let dist=len(e.x-previousX,e.y-previousY);if(dist>.1){e.walk+=dist;e.walkMove=true;}e.state=e.state==='windup'?'windup':e.walkMove?'walk':'idle';
}
function update(dt){time+=dt;if(mode==='transition'){transitionTime-=dt;if(transitionTime<1.12&&!transitionDone){transitionDone=true;initChapter(transitionTarget);active=true;}if(transitionTime<.6)$('transition').style.opacity='0';if(transitionTime<=0)resume();return;}if(mode!=='play')return;if(freeze>0){freeze-=dt;return;}updatePlayer(dt);if(mode!=='play')return;for(const e of enemies)updateEnemy(e,dt);enemies=enemies.filter(e=>e.hp>0);for(const b of shots){b.t-=dt;if(!b.player){b.x+=b.dx*dt;b.y+=b.dy*dt;if(len((b.x-player.x), (b.y-player.y)*1.5)<30){hurtPlayer(b.damage,b.x);b.t=0;}if(b.x<0||b.x>(area+1)*1100||b.y<410||b.y>650)b.t=0;}}shots=shots.filter(b=>b.t>0);for(const d of drops){d.t+=dt;if(Math.abs(d.x-player.x)<47&&Math.abs(d.y-player.y)<42){if(d.kind==='health'){player.hp=Math.min(100,player.hp+25);floating(d.x,d.y-110,'+25 HEALTH','#b6e1bc');}else{player.reserve=Math.min(180,player.reserve+24);floating(d.x,d.y-110,'+24 AMMO','#9adbe7');}d.dead=true;sound('pickup');}}drops=drops.filter(d=>!d.dead);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;if(!p.text)p.vy+=500*dt;p.t-=dt;}particles=particles.filter(p=>p.t>0);for(const b of corpses)b.t-=dt;corpses=corpses.filter(b=>b.t>0);comboLife-=dt;if(comboLife<=0)comboHits=0;calloutLife-=dt;shake=Math.max(0,shake-dt*25);const target=clamp(player.x-VW*.40,0,Math.max(0,3300-VW));camera+=(target-camera)*(1-Math.exp(-dt*7));if(enemies.length===0&&!areaCleared){areaCleared=true;score+=300;announce('AREA CLEAR · MOVE RIGHT',3);sound('clear');}updateHud();}
function updateHud(){const location=currentArea();$('hpText').textContent=Math.ceil(player.hp)+' / 100';$('hpFill').style.width=player.hp+'%';$('hpFill').style.background=player.hp<30?'#df5648':'#b6d3d7';$('furyFill').style.width=player.fury+'%';$('furyLabel').textContent='CHAINSAW '+Math.floor(player.fury)+'%';$('ammo').textContent=player.state==='reload'?'RELOADING…':'LANCER '+num(player.mag)+' / '+player.reserve;$('score').textContent=String(score).padStart(6,'0');$('chapterText').textContent='CH. '+num(chapter+1)+' / 05 · AREA '+num(location+1)+' / 03';$('areaText').textContent=chapters[chapter].areas[location];$('threatText').textContent=areaCleared?'CLEAR · ADVANCE RIGHT →':enemies.filter(e=>e.hp>0).length+' LOCUST REMAINING';const boss=enemies.find(e=>e.boss&&e.hp>0);$('bossHud').hidden=!boss;if(boss){$('bossName').textContent=chapters[chapter].boss;$('bossFill').style.width=(boss.hp/boss.maxHp*100)+'%';}$('combo').textContent=comboHits>1?comboHits+' HITS':'';$('callout').style.opacity=calloutLife>0?'1':'0';}
function drawLayer(key,height,base,factor,cam){const img=images[key];if(!img)return;const width=height*img.width/img.height;let offset=-(cam*factor)%width;for(let x=offset-width;x<VW+width;x+=width)ctx.drawImage(img,x,base-height,width+1,height);}
function background(theme,cam,hero=false){ctx.fillStyle='#101923';ctx.fillRect(0,0,VW,VH);let far=images[theme+'-far'];if(far){const h=Math.max(VH,520),width=Math.max(VW+300,h*far.width/far.height),hh=width*far.height/far.width;ctx.drawImage(far,-((cam*.08)%(Math.max(1,width-VW)))-30,0,width+60,Math.max(VH,hh));}drawLayer(theme+'-mid',475,445,.30,cam);drawLayer(theme+'-near',465,465,.62,cam);let floor=images[theme+'-floor'];if(floor){const fh=VH-430,fw=fh*floor.width/floor.height;let first=Math.floor(cam/fw)-1;for(let i=first;i*fw-cam<VW+fw;i++){let x=i*fw-cam;ctx.save();if(Math.abs(i)%2){ctx.translate(x+fw,430);ctx.scale(-1,1);ctx.drawImage(floor,0,0,fw+1,fh+2);}else ctx.drawImage(floor,x,430,fw+1,fh+2);ctx.restore();}}ctx.fillStyle='#07121b18';ctx.fillRect(0,430,VW,18);}
function artInfo(key){const im=images[key],a=meta[key]||{};return {cols:a.cols||((['marcus','drone','kantus','skorge'].includes(key))?4:key.endsWith('-prop')?3:1),rows:a.rows||(['marcus','drone','kantus','skorge'].includes(key)?2:1),anchorX:a.anchorX??.5,anchorY:a.anchorY??.94,bodyHeight:a.bodyHeight??.83,...a};}
function sprite(key,frame,x,y,height,face=1,flash=0){const img=images[key];if(!img)return;const a=artInfo(key),cw=img.width/a.cols,ch=img.height/a.rows,scale=height/(ch*a.bodyHeight),dw=cw*scale,dh=ch*scale;ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.globalAlpha=1;if(flash>0)ctx.filter='brightness(1.6)';ctx.drawImage(img,(frame%a.cols)*cw,Math.floor(frame/a.cols)*ch,cw,ch,-dw*a.anchorX,-dh*a.anchorY,dw,dh);ctx.restore();}
function shadow(x,y,w,h,alpha=.32){ctx.fillStyle=`rgba(0,0,0,${alpha})`;ctx.beginPath();ctx.ellipse(x,y+2,w,h,0,0,Math.PI*2);ctx.fill();}
function actorFrame(e,isPlayer=false){if(isPlayer){if(e.state==='dead')return e.t>.6?6:7;if(e.state==='hurt')return 5;if(e.state==='melee'||e.state==='saw')return 3;if(e.state==='shoot')return 4;if(e.state==='reload')return 0;if(e.state==='dodge')return 6;}else {if(e.state==='hurt')return 5;if(e.state==='attack')return ['ranged','summon'].includes(e.attackKind)?4:3;if(e.state==='windup')return 0;}return e.walkMove?1+(Math.floor(e.walk/39)%2):0;}
function drawActor(e,isPlayer=false){const x=e.x-camera,h=isPlayer?163:e.height;shadow(x,e.y,h*.22,9);if(e.state==='windup'){ctx.strokeStyle='#f5725b';ctx.lineWidth=2;ctx.fillStyle='#c9372926';ctx.beginPath();ctx.ellipse(x,e.y,60,19,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='800 25px Oxanium';ctx.textAlign='center';ctx.fillStyle='#ffae8f';ctx.fillText('!',x,e.y-h-17);if(e.attackKind==='charge'){ctx.fillStyle='#e9574329';ctx.fillRect(Math.min(x,e.targetX-camera),e.y-19,Math.abs(e.targetX-e.x)+50,38);}}
 sprite(isPlayer?'marcus':e.type,actorFrame(e,isPlayer),x,e.y,h,e.face,isPlayer?(e.inv>.1&&e.state==='hurt'?.2:0):e.hit);
 if(isPlayer&&e.state==='saw'){ctx.strokeStyle='#f3c888';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+e.face*70,e.y-73,50,-1.3,1.3);ctx.stroke();}
 if(!isPlayer&&e.hp<e.maxHp&&!e.boss){ctx.fillStyle='#10131b';ctx.fillRect(x-24,e.y-h-10,48,4);ctx.fillStyle='#d7786b';ctx.fillRect(x-24,e.y-h-10,48*e.hp/e.maxHp,4);}
 if(isPlayer&&e.state==='reload'){ctx.fillStyle='#152430';ctx.fillRect(x-26,e.y-h-18,52,4);ctx.fillStyle='#b2d5de';ctx.fillRect(x-26,e.y-h-18,52*(1-e.t/e.duration),4);}
}
function drawWorld(){background(chapters[chapter].key,camera);let sorted=[...props.map(p=>({kind:'prop',e:p,y:p.y})),...corpses.map(e=>({kind:'corpse',e,y:e.y})),...[...enemies,...encounters.slice(area+1).flat()].map(e=>({kind:'enemy',e,y:e.y})),{kind:'player',e:player,y:player.y},...drops.map(e=>({kind:'drop',e,y:e.y}))].sort((a,b)=>a.y-b.y);for(const item of sorted){const e=item.e,x=e.x-camera;if(x<-350||x>VW+350)continue;if(item.kind==='prop'){shadow(x,e.y,42,9,.25);sprite(e.kind,e.state,x,e.y,88);}else if(item.kind==='corpse'){ctx.save();sprite(e.type,e.t>2.5?6:7,x,e.y,e.height,e.face);ctx.restore();}else if(item.kind==='drop'){let bob=Math.sin(ambient*4)*3;shadow(x,e.y,15,5,.22);ctx.strokeStyle=e.kind==='health'?'#c5e7ad':'#8dcbdc';ctx.fillStyle='#13212d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,e.y-21+bob,15,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font='700 19px Oxanium';ctx.textAlign='center';ctx.fillText(e.kind==='health'?'+':'Ⅱ',x,e.y-14+bob);}else drawActor(e,item.kind==='player');}
 for(const b of shots){ctx.strokeStyle=b.player?'#ffe6a7':'#f58e67';ctx.fillStyle='#ffb376';ctx.lineWidth=b.player?2:4;ctx.beginPath();if(b.player){ctx.moveTo(b.x-camera,b.y);ctx.lineTo(b.x2-camera,b.y2);}else{ctx.moveTo(b.x-camera,b.y-82);ctx.lineTo(b.x-camera-b.dx*.04,b.y-82-b.dy*.04);}ctx.stroke();}
 for(const p of particles){ctx.save();ctx.globalAlpha=Math.min(1,p.t/p.max*2);ctx.fillStyle=p.color;if(p.text){ctx.font='700 17px Oxanium';ctx.textAlign='center';ctx.fillText(p.text,p.x-camera,p.y);}else ctx.fillRect(p.x-camera,p.y,4,3);ctx.restore();}
 if(areaCleared){const gx=(area+1)*1100-92-camera;ctx.font='800 33px Oxanium';ctx.textAlign='center';ctx.fillStyle='#d9e4d8';ctx.fillText('→',clamp(gx,VW*.70,VW-42),515+Math.sin(ambient*3)*5);ctx.font='600 11px Oxanium';ctx.fillText('ADVANCE',clamp(gx,VW*.70,VW-42),537+Math.sin(ambient*3)*5);}
}
function drawHero(){const drift=240+Math.sin(ambient*.10)*180;background('jacinto',drift,true);const left=VW*(portrait?.07:.51),right=VW*.97,gap=Math.max(18,VW*.025),h=Math.min(VH*(portrait?.25:.64),(right-left-gap)/(328/401+.84*453/386)),py=VH*(portrait?.875:.79),px=left+129/401*h,bx=left+328/401*h+gap+255/386*h*.84;shadow(px,py,h*.22,12);sprite('marcus',0,px,py,h,1);shadow(bx,py-8,h*.17,10);sprite('skorge',0,bx,py-10,h*.84,-1);}
function render(){ctx.setTransform(DPR*S,0,0,DPR*S,0,0);ctx.imageSmoothingEnabled=true;ctx.save();if(mode==='play'&&shake>0)ctx.translate(rand(-shake,shake),rand(-shake*.45,shake*.45));const hero=mode==='main'||(mode==='help'&&menuOrigin==='main')||!player;if(hero)drawHero();else drawWorld();ctx.restore();}
let previous=performance.now();function frame(now){const dt=Math.min((now-previous)/1000,.034);previous=now;ambient+=dt;update(dt);render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
async function loadAssets(){loaded=false;loadFailed=false;showMenu('main');let done=0;try{await Promise.all(files.map(key=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[key]=im;done++;const progress=Math.round(done/(files.length+1)*100);if(!loadFailed){$('primaryText').textContent='LOADING '+progress+'%';$('loadFill').style.width=progress+'%';}resolve();};im.onerror=()=>reject(new Error(key));im.src='assets/'+key+'.png';})));await document.fonts.load('700 16px Oxanium');loaded=true;$('loadFill').style.width='100%';showMenu('main');}catch(e){loadFailed=true;showMenu('main');$('menuText').textContent='Some artwork could not load.\nCheck your connection, then retry.';}}
const gameStatus=()=>({state:mode,chapter:chapter+1,area:currentArea()+1,encounterArea:area+1,location:chapters[chapter].areas[currentArea()],score,kills,remaining:enemies.filter(e=>e.hp>0).length,player:player?{x:Math.round(player.x),lane:Math.round(player.y),health:player.hp,fury:Math.floor(player.fury),magazine:player.mag,reserve:player.reserve,action:player.state}:null,visibleEnemies:player?enemies.filter(e=>e.x>camera&&e.x<camera+VW).map(e=>({type:e.type,boss:e.boss,x:Math.round(e.x),lane:Math.round(e.y),health:e.hp,action:e.state})):[]});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch(e){}};register({name:'game_status',title:'Read game status',description:'Read the current menu or arena, player supplies, and enemies visible in the arena.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>gameStatus()});register({name:'game_menu_action',title:'Use a game menu action',description:'Start a new campaign from the main menu, continue a run, pause, or resume. Starting a new campaign resets the current run.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','continue','pause','resume']}},required:['action'],additionalProperties:false},execute:({action})=>{if(action==='start'&&mode==='main'&&loaded)startGame(0);else if(action==='continue'&&mode==='main'&&(active||saved))$('continue').click();else if(action==='pause'&&mode==='play')showMenu('pause');else if(action==='resume'&&mode==='pause')resume();else throw new Error('That action is unavailable in the current game state.');return gameStatus();}});register({name:'game_input',title:'Move or fight',description:'Hold movement and one normal combat control for 50 to 2000 milliseconds in the active arena. Uses the same movement and attacks as the keyboard.',inputSchema:{type:'object',properties:{horizontal:{type:'integer',minimum:-1,maximum:1},vertical:{type:'integer',minimum:-1,maximum:1},action:{type:'string',enum:['none','melee','saw','shoot','reload','dodge']},milliseconds:{type:'integer',minimum:50,maximum:2000}},required:['horizontal','vertical','action','milliseconds'],additionalProperties:false},execute:async v=>{if(mode!=='play'||!Number.isInteger(v.horizontal)||Math.abs(v.horizontal)>1||!Number.isInteger(v.vertical)||Math.abs(v.vertical)>1||!Number.isInteger(v.milliseconds)||v.milliseconds<50||v.milliseconds>2000||!['none',...Object.keys(actions)].includes(v.action))throw new Error('Use valid controls while the game is running.');clearInput();if(v.horizontal)keys.add(v.horizontal>0?'KeyD':'KeyA');if(v.vertical)keys.add(v.vertical>0?'KeyS':'KeyW');if(actions[v.action])keys.add(actions[v.action]);await new Promise(r=>setTimeout(r,v.milliseconds));clearInput();return gameStatus();}});addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
loadAssets();
})();
