/* Doom Eternal: Platformer — self-contained HTML5 platformer. */
(() => {
'use strict';
const $ = id => document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const TAU=Math.PI*2,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rnd=(a,b)=>a+Math.random()*(b-a),lerp=(a,b,t)=>a+(b-a)*t;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const THEMES=[
 {name:'HELL ON EARTH',color:'#e95629',sky:'#442a2b',ground:'#252026',hazard:'fire',width:5200,prop:'SHATTERED STREETS'},
 {name:'EXULTIA',color:'#de9d50',sky:'#463040',ground:'#342727',hazard:'crush',width:5450,prop:'THE FALLEN KINGDOM'},
 {name:'CULTIST BASE',color:'#79d1e3',sky:'#314652',ground:'#232c36',hazard:'laser',width:5600,prop:'BENEATH THE ICE'},
 {name:'SUPER GORE NEST',color:'#f26363',sky:'#491e2b',ground:'#321923',hazard:'acid',width:5800,prop:'THE LIVING CITY'},
 {name:'NEKRAVOL',color:'#f7a544',sky:'#402029',ground:'#242023',hazard:'fire',width:6200,prop:'THE END OF THE LINE'}
];
const WEAPONS=[{name:'SUPER SHOTGUN',short:'SHELLS',cool:.52,damage:14,pellets:6,speed:1450,color:'#ffd87b',life:.47},
 {name:'PLASMA RIFLE',short:'CELLS',cool:.095,damage:16,pellets:1,speed:1170,color:'#81edff',life:1.1},
 {name:'ROCKET LAUNCHER',short:'ROCKETS',cool:.85,damage:110,pellets:1,speed:760,color:'#ffa953',life:2.0}];
const ENEMIES={imp:{hp:84,speed:100,w:38,h:67,draw:114,damage:10,score:100},knight:{hp:250,speed:105,w:58,h:96,draw:153,damage:20,score:300},caco:{hp:125,speed:90,w:69,h:66,draw:110,damage:12,score:200}};
const imageKeys=['slayer','imp','knight','caco','health','ammo','armor','rune','portal','fireball','plasma','barrel','explosion'];
for(let i=0;i<5;i++)imageKeys.push(`bg-far-${i}`,`bg-mid-${i}`,`bg-near-${i}`,`tile-${i}`,`prop-${i}`);
const art={},assets={};
let state='menu',assetsReady=false,level=0,world=null,p=null,camera={x:0,y:0},view={w:1280,h:760,scale:1,dpr:1},clock=0,last=0,accum=0;
let enemies=[],shots=[],particles=[],floating=[],drops=[],props=[],seals=[],hazards=[];
let score=0,kills=0,totalKills=0,combo=0,comboTimer=0,levelTime=0,runTime=0,shake=0,flash=0,noticeTimer=0,introTimer=0,deathTimer=0,checkpoint=0,checkpointSeen=false;
let weapon=0,ammo=[Infinity,150,10],unlocked=1,gateOpen=false,menuTime=0,musicTimer=0,muted=false,audioCtx=null,hudTimer=0,gateLabel='',checkpointSeals=[];
let input={left:false,right:false,fire:false},pressed=new Set(),aim={x:0,y:0,active:false},touchMode=matchMedia('(pointer:coarse)').matches;
let save=null;try{save=JSON.parse(localStorage.getItem('doom-hellbound-save-v1')||'null');muted=localStorage.getItem('doom-hellbound-muted')==='1'}catch{}
const atlas={slayer:{cols:3,rows:2},imp:{cols:3,rows:2},knight:{cols:3,rows:2},caco:{cols:2,rows:2}};
function seedRandom(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
function resize(){const w=innerWidth,h=innerHeight;view.dpr=Math.min(devicePixelRatio||1,2);view.scale=w/h<.85?w/660:h/760;view.w=w/view.scale;view.h=h/view.scale;canvas.width=Math.round(w*view.dpr);canvas.height=Math.round(h*view.dpr);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';if(p)trackCamera(true)}
addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);
function showScreen(next){state=next;$('menu').classList.toggle('hidden',next!=='menu');$('hud').classList.toggle('hidden',!['playing','paused','dead','clear','victory'].includes(next));$('overlay').classList.toggle('hidden',!['paused','dead','clear','victory'].includes(next));input.left=input.right=input.fire=false;pressed.clear();document.querySelectorAll('.pressed').forEach(n=>n.classList.remove('pressed'));canvas.style.cursor=next==='playing'&&!touchMode?'none':'default';if(next==='menu'){$('continue').classList.toggle('hidden',!assetsReady||!save||save.level<1);$('continue-level').textContent=String((save?.level||0)+1).padStart(2,'0')}}
function notify(text,time=2.7){$('notice').textContent=text;noticeTimer=time;$('notice').style.opacity=1}
function sound(type){if(muted)return;try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const now=audioCtx.currentTime;const params={shot:[110,.09,'sawtooth',.09],plasma:[640,.045,'square',.045],rocket:[65,.2,'sawtooth',.09],jump:[260,.09,'triangle',.07],dash:[190,.12,'sawtooth',.065],hit:[70,.06,'square',.045],kill:[95,.14,'sawtooth',.06],pickup:[720,.15,'sine',.1],glory:[52,.32,'sawtooth',.12],seal:[140,.5,'triangle',.12],hurt:[85,.14,'square',.1],click:[440,.05,'square',.04]};const [f,d,w,v]=params[type]||params.shot;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=w;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(type==='pickup'?f*1.7:Math.max(20,f*.2),now+d);g.gain.setValueAtTime(v,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+d)}catch{}}
function ambience(dt){if(muted||!audioCtx)return;musicTimer-=dt;if(musicTimer>0)return;musicTimer=.24;const beat=Math.floor(clock/.24)%16;const note=[55,55,55,65.4,55,55,82.4,55,55,55,73.4,55,65.4,55,49,49][beat];try{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type='sawtooth';o.frequency.value=note;g.gain.setValueAtTime(.018,t);g.gain.exponentialRampToValueAtTime(.0001,t+.2);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.2)}catch{}}
function updateSound(){document.querySelectorAll('.sound-button').forEach(b=>b.textContent=muted?'SOUND OFF':'SOUND ON');try{localStorage.setItem('doom-hellbound-muted',muted?'1':'0')}catch{}}
function rectHits(a,b){return a.x+a.w/2>b.x&&a.x-a.w/2<b.x+b.w&&a.y>b.y&&a.y-a.h<b.y+b.h}
function platform(x,y,w,h=24,ground=false){return {x,y,w,h,ground}}
function startLevel(n,fromCheckpoint=false){
 level=clamp(n,0,4);const t=THEMES[level],rng=seedRandom(741+level*537);levelTime=0;combo=0;comboTimer=0;kills=0;deathTimer=0;gateOpen=false;gateLabel='';checkpointSeen=fromCheckpoint;checkpoint=fromCheckpoint?Math.floor(t.width*.46):0;if(!fromCheckpoint)checkpointSeals=[];
 enemies=[];shots=[];particles=[];floating=[];drops=[];props=[];seals=[];hazards=[];world={width:t.width,height:1700,platforms:[],theme:t};
 // Continuous world coordinates keep terrain fixed to physics at every camera size.
 const pits=[{x:1760+level*35,w:200+level*9},{x:3550+level*65,w:200+level*8}];
 let gx=0;for(const pit of pits){world.platforms.push(platform(gx,620,pit.x-gx,1200,true));hazards.push({x:pit.x,y:639,w:pit.w,h:900,type:t.hazard,pit:true});gx=pit.x+pit.w}world.platforms.push(platform(gx,620,t.width-gx,1200,true));
 const groups=[400,1050,2170,2740,3950,4600];
 groups.forEach((base,g)=>{const shift=level*13*(g%2),rise=level===2?18:0;world.platforms.push(platform(base+shift,500-rise,240,27));world.platforms.push(platform(base+200+shift,385-rise-(g%2)*15,210,26));if(g%2===1)world.platforms.push(platform(base+410+shift,485-rise,210,26))});
 pits.forEach((pit,i)=>world.platforms.push(platform(pit.x+pit.w/2-75,455-(i%2)*30,150,25)));
 if(level===3)world.platforms.push(platform(5050,475,250,28));if(level===4)world.platforms.push(platform(5450,485,240,28));
 const sealSpots=[{x:1270+level*13,y:319},{x:2950+level*13,y:320},{x:4240+level*13,y:321}];
 sealSpots.forEach((a,i)=>seals.push({...a,hp:100,maxHp:100,index:i,broken:fromCheckpoint&&checkpointSeals.includes(i)}));
 for(let i=0;i<22+level*4;i++){const x=700+i*(t.width-1050)/(22+level*4)+rng()*110;if(pits.some(q=>x>q.x-30&&x<q.x+q.w+30))continue;const type=i%5===3?'caco':i%4===2?'knight':'imp';let groundY=620;if(i%4===1){const pl=world.platforms.filter(q=>!q.ground&&q.x<x&&q.x+q.w>x).sort((a,b)=>a.y-b.y)[0];if(pl)groundY=pl.y}spawnEnemy(type,x,type==='caco'?340+rng()*70:groundY)}
 if(level===4)spawnEnemy('knight',t.width-450,620,true);
 const propXs=[580,920,1550,2100,2510,3300,4080,4780];propXs.forEach((x,i)=>{x+=level*18;if(!pits.some(q=>x>q.x&&x<q.x+q.w))props.push({x,y:620,hp:55,maxHp:55,frame:0,w:57,h:83})});
 for(const x of [900,2340,3900]){drops.push({x:x+level*17,y:565,type:'health',life:Infinity,vy:0,fixed:true});drops.push({x:x+140+level*17,y:568,type:'ammo',life:Infinity,vy:0,fixed:true})}
 drops.push({x:720,y:450,type:'armor',life:Infinity,vy:0,fixed:true});
 if(level===0){drops.push({x:2120,y:565,type:'weapon1',life:Infinity,vy:0,fixed:true});drops.push({x:3850,y:565,type:'weapon2',life:Infinity,vy:0,fixed:true})}
 for(let i=0;i<3+level;i++){const x=1480+i*840;if(x<t.width-500&&!pits.some(q=>x>q.x-50&&x<q.x+q.w))hazards.push({x,y:596,w:level===2?85:65,h:24,type:t.hazard,phase:i*1.2,pit:false})}
 p={x:fromCheckpoint?checkpoint:180,y:620,w:34,h:77,vx:0,vy:0,hp:100,armor:50,face:1,ground:true,jumps:0,coyote:0,jumpBuffer:0,dash:0,dashCool:0,invul:1,shotCool:0,frame:0,stride:0,fireAnim:0,hurt:0,gloryCool:0};
 if(!fromCheckpoint){ammo=[Infinity,150,10];weapon=0}unlocked=Math.max(unlocked,level>0?3:1);
 $('intro-number').textContent=`SECTOR ${String(level+1).padStart(2,'0')} / 05`;$('intro-name').textContent=t.name;introTimer=3.4;$('level-intro').style.opacity=1;
 $('sector').textContent=`${String(level+1).padStart(2,'0')} / 05 · ${t.name}`;if(!fromCheckpoint)notify(level===0?'KEEP MOVING. BREAK ALL THREE SEALS.':'BREAK THE SEALS. REACH THE PORTAL.',3.5);else notify('CHECKPOINT RESTORED');
 trackCamera(true);showScreen('playing');updateHUD();
}
function spawnEnemy(type,x,y,boss=false){const d=ENEMIES[type];enemies.push({...d,type,x,y,baseY:y,vx:0,vy:0,hp:d.hp*(boss?4.8:1)*(1+level*.09),maxHp:d.hp*(boss?4.8:1)*(1+level*.09),face:-1,stride:0,ground:true,attack:rnd(.6,2),hurt:0,stagger:0,dead:0,phase:rnd(0,TAU),charge:0,telegraph:0,boss,score:d.score*(boss?5:1)})}
function moveBody(b,dt){b.ground=false;let px=b.x,py=b.y;b.x+=b.vx*dt;
 for(const q of world.platforms){if(q.ground&&rectHits(b,q)&&py>q.y+7){if(b.vx>0)b.x=q.x-b.w/2;else if(b.vx<0)b.x=q.x+q.w+b.w/2;b.vx=0}}
 b.y+=b.vy*dt;
 for(const q of world.platforms){if(b.x+b.w/2>q.x&&b.x-b.w/2<q.x+q.w&&py<=q.y+5&&b.y>=q.y&&b.vy>=0){b.y=q.y;b.vy=0;b.ground=true}}
 b.x=clamp(b.x,b.w/2,world.width-b.w/2);b.stride+=Math.abs(b.x-px);return {dx:b.x-px,dy:b.y-py};
}
function jump(){if(state!=='playing')return;p.jumpBuffer=.13;tryJump()}
function tryJump(){if(p.jumpBuffer>0&&(p.ground||p.coyote>0||p.jumps<2)){p.vy=p.jumps===1?-630:-705;p.jumps++;p.ground=false;p.coyote=0;p.jumpBuffer=0;sound('jump');burst(p.x,p.y,9,'#a79783',130,0.35);return true}return false}
function dash(){if(state!=='playing'||p.dashCool>0)return;p.dash=.18;p.dashCool=1.05;p.invul=Math.max(p.invul,.23);p.vy=0;p.vx=p.face*1050;shake=3;sound('dash');burst(p.x,p.y-35,14,'#ffa565',150,.3)}
function chooseWeapon(n){if(n<0||n>=unlocked){notify('FIND THE WEAPON PICKUP');return}weapon=n;notify(WEAPONS[n].name,1.2);sound('click');updateHUD()}
function fire(){if(p.shotCool>0||state!=='playing')return;if(weapon>0&&ammo[weapon]<=0){chooseWeapon(0);notify('OUT OF AMMO · SHOTGUN READY');return}const w=WEAPONS[weapon];if(weapon>0)ammo[weapon]--;p.shotCool=w.cool;p.fireAnim=.13;
 const start={x:p.x+p.face*40,y:p.y-48};let angle=p.face===1?0:Math.PI;
 if(aim.active&&!touchMode){const dx=aim.x+camera.x-start.x,dy=aim.y+camera.y-start.y;angle=Math.atan2(dy,dx);p.face=dx>=0?1:-1;start.x=p.x+p.face*40}
 else{let candidates=[...enemies.filter(e=>!e.dead),...seals.filter(s=>!s.broken).map(s=>({...s,isSeal:true}))].filter(e=>Math.abs(e.x-p.x)<780&&(e.x-p.x)*p.face>0&&Math.abs((e.isSeal?e.y:e.y-e.h*.55)-start.y)<230);candidates.sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x));if(candidates.length){const e=candidates[0];angle=Math.atan2((e.isSeal?e.y:e.y-e.h*.55)-start.y,e.x-start.x)}}
 for(let i=0;i<w.pellets;i++){const spread=weapon===0?(i-(w.pellets-1)/2)*.051:rnd(-.013,.013);shots.push({x:start.x,y:start.y,px:start.x,py:start.y,vx:Math.cos(angle+spread)*w.speed,vy:Math.sin(angle+spread)*w.speed,damage:w.damage,life:w.life,friendly:true,type:weapon,color:w.color,r:weapon===2?8:weapon===1?5:3})}
 shake=Math.max(shake,weapon===2?7:weapon===0?4:1.5);sound(weapon===0?'shot':weapon===1?'plasma':'rocket')}
function burst(x,y,count,color,speed=170,life=.6){for(let i=0;i<count;i++){if(particles.length>400)break;particles.push({x,y,vx:rnd(-speed,speed),vy:rnd(-speed,speed*.4),life:rnd(life*.5,life),max:life,color,size:rnd(2,6)})}}
function floatText(x,y,text,color='#ffd78b'){floating.push({x,y,text,color,life:1.0})}
function killEnemy(e,glory=false){if(e.dead)return;e.dead=.75;e.hp=0;e.stagger=0;kills++;totalKills++;combo++;comboTimer=4.0;const mult=1+Math.floor(Math.min(combo,12)/3);score+=e.score*mult*(glory?2:1);floatText(e.x,e.y-e.h,`+${e.score*mult*(glory?2:1)}`);burst(e.x,e.y-e.h/2,glory?28:14,e.type==='knight'?'#ceb6a7':'#d15436',glory?330:190,.7);sound(glory?'glory':'kill');
 if(glory){p.hp=Math.min(100,p.hp+35);p.armor=Math.min(100,p.armor+10);ammo[1]+=15;ammo[2]+=1;p.invul=.9;notify('GLORY KILL · +35 HEALTH',1.7);shake=13;flash=.12}else if(Math.random()<.45)drops.push({x:e.x,y:e.y-20,type:Math.random()<.45?'health':'ammo',life:18,vy:-180,fixed:false});
 if(e.boss){notify('THE CHAMPION HAS FALLEN',3);shake=22;score+=2000}updateHUD()}
function hitEnemy(e,damage){if(e.dead)return;e.hp-=damage;e.hurt=.13;if(e.hp<=0){killEnemy(e);return}if(e.hp<=e.maxHp*.28&&!e.boss)e.stagger=4.5;sound('hit')}
function glory(){if(state!=='playing'||p.gloryCool>0)return;const targets=enemies.filter(e=>!e.dead&&e.stagger>0&&Math.hypot(e.x-p.x,(e.y-e.h*.5)-(p.y-p.h*.5))<145);targets.sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x));if(!targets.length){notify('STAGGER A DEMON, THEN GET CLOSE',1.6);return}const e=targets[0];p.face=e.x>=p.x?1:-1;p.gloryCool=.4;killEnemy(e,true)}
function hurtPlayer(damage,sourceX){if(p.invul>0||state!=='playing')return;const blocked=Math.min(p.armor,Math.ceil(damage*.6));p.armor-=blocked;p.hp-=damage-blocked;p.invul=.6;p.hurt=.2;shake=7;flash=.1;combo=0;if(sourceX!==undefined)p.vx=(p.x>sourceX?1:-1)*190;sound('hurt');if(p.hp<=0){p.hp=0;die()}updateHUD()}
function die(){if(state!=='playing')return;sound('glory');showDialog('dead');burst(p.x,p.y-40,40,'#ee6743',330,1.2)}
function breakSeal(s){if(s.broken)return;s.broken=true;score+=500;shake=16;flash=.16;burst(s.x,s.y,45,'#ffae50',360,.9);sound('seal');floatText(s.x,s.y,'SEAL DESTROYED');spawnEnemy('imp',s.x+230,620);if(level>0)spawnEnemy('caco',s.x-150,350);notify(`${seals.filter(s=>s.broken).length} / 3 SEALS DESTROYED`);updateGate()}
function updateGate(){const bossAlive=enemies.some(e=>e.boss&&!e.dead);const all=seals.every(s=>s.broken);if(all&&!bossAlive&&!gateOpen){gateOpen=true;notify('PORTAL OPEN · KEEP MOVING RIGHT',4);sound('pickup')}const remaining=seals.filter(s=>!s.broken).length,label=gateOpen?'REACH THE EXIT PORTAL':all?'DESTROY THE CHAMPION':'BREAK THE DEMON SEALS';if(gateLabel!==label+remaining){gateLabel=label+remaining;$('objective').textContent=label;$('seal-count').textContent=gateOpen?'EXIT →':`${3-remaining} / 3`}}
function explode(x,y,damage,friendly=true){burst(x,y,40,'#ff9a3e',370,.7);particles.push({x,y,vx:0,vy:0,life:.35,max:.35,color:'#ffe1a3',size:140,explosion:true});shake=12;sound('rocket');if(friendly){for(const e of enemies)if(!e.dead&&Math.hypot(e.x-x,e.y-e.h/2-y)<155)hitEnemy(e,damage*(1-Math.min(.65,dist({x,y},{x:e.x,y:e.y-e.h/2})/210)));for(const s of seals)if(!s.broken&&dist(s,{x,y})<150){s.hp-=damage;if(s.hp<=0)breakSeal(s)}for(const a of props)if(a.hp>0&&dist({x:a.x,y:a.y-35},{x,y})<160){a.hp-=damage;a.frame=a.hp<=0?2:1}}else if(dist({x:p.x,y:p.y-35},{x,y})<130)hurtPlayer(22,x)}
function enemyShoot(e){const from={x:e.x+e.face*25,y:e.y-e.h*.6};let a=Math.atan2(p.y-35-from.y,p.x+clamp(p.vx*.18,-60,60)-from.x);const n=e.type==='caco'&&level>=2?3:1;for(let i=0;i<n;i++){const angle=a+(i-(n-1)/2)*.19,velocity=280+level*27;shots.push({x:from.x,y:from.y,px:from.x,py:from.y,vx:Math.cos(angle)*velocity,vy:Math.sin(angle)*velocity,damage:e.damage,life:4.5,friendly:false,type:'fire',color:'#ff8647',r:11})}e.hurt=-.2}
function updateEnemies(dt){for(const e of enemies){if(e.dead){e.dead-=dt;if(e.dead<=0)e.dead=-1;continue}if(Math.abs(e.x-p.x)>view.w+1100)continue;e.hurt=e.hurt>0?Math.max(0,e.hurt-dt):Math.min(0,e.hurt+dt);e.attack-=dt;e.stagger=Math.max(0,e.stagger-dt);e.face=p.x>=e.x?1:-1;
 if(e.type==='caco'){e.x+=e.face*e.speed*dt*(Math.abs(p.x-e.x)>360?1:-.35);e.y=lerp(e.y,clamp(p.y-180,220,450)+Math.sin(clock*2+e.phase)*45,dt*1.5);if(e.attack<0&&Math.abs(e.x-p.x)<960&&!e.stagger){enemyShoot(e);e.attack=2.5-level*.16}continue}
 e.vy=Math.min(950,e.vy+1950*dt);const dx=Math.abs(p.x-e.x);if(e.stagger){e.vx=0;e.charge=0;e.telegraph=0}else if(e.telegraph>0){e.telegraph-=dt;e.vx=0;if(e.telegraph<=0){e.charge=.36;e.vx=e.face*(e.boss?690:600)}}else if(e.charge>0){e.charge-=dt;e.vx=e.face*(e.boss?690:600)}else if(e.type==='knight'&&dx<400&&dx>120&&e.attack<=0&&e.ground){e.telegraph=.66;e.attack=e.boss?2.4:3.3;e.vx=0}else{e.vx=e.face*e.speed*(dx<e.w*.7?0:1);if(e.type==='imp'&&dx<600&&dx>250){e.vx=e.face*e.speed*.2;if(e.attack<=0){enemyShoot(e);e.attack=1.8+Math.random()*.6-level*.12}}}
 const oldground=e.ground,dxmove=moveBody(e,dt);if(oldground&&!e.stagger){const ahead=e.x+e.face*70;const hasFloor=world.platforms.some(q=>ahead>=q.x&&ahead<=q.x+q.w&&q.y>=e.y-5&&q.y<e.y+45);if((!hasFloor||Math.abs(dxmove.dx)<.01||p.y<e.y-100&&dx<200)&&e.vy===0){e.vy=-650;e.ground=false}}
 if(e.y>1100){e.hp=0;e.dead=.2;continue}if(Math.abs(e.x-p.x)<(p.w+e.w)/2&&Math.abs(e.y-p.y)<Math.max(60,e.h*.7)&&!e.stagger)hurtPlayer(e.damage+(e.charge>0?8:0),e.x);
 }enemies=enemies.filter(e=>e.dead!==-1)}
function pointBox(x,y,b){return x>b.x-b.w/2&&x<b.x+b.w/2&&y>b.y-b.h&&y<b.y}
function updateShots(dt){for(const s of shots){s.life-=dt;if(s.life<=0)continue;s.px=s.x;s.py=s.y;const steps=Math.max(1,Math.ceil(Math.hypot(s.vx,s.vy)*dt/12));for(let i=0;i<steps;i++){s.x+=s.vx*dt/steps;s.y+=s.vy*dt/steps;let hit=false;
 if(s.friendly){for(const e of enemies){if(!e.dead&&pointBox(s.x,s.y,e)){if(s.type===2)explode(s.x,s.y,s.damage);else hitEnemy(e,s.damage);hit=true;break}}if(!hit)for(const seal of seals){if(!seal.broken&&Math.hypot(s.x-seal.x,s.y-seal.y)<39){seal.hp-=s.damage;burst(s.x,s.y,3,'#ffb552',70,.3);if(seal.hp<=0)breakSeal(seal);hit=true;break}}if(!hit)for(const a of props){if(a.hp>0&&pointBox(s.x,s.y,a)){a.hp-=s.damage;a.frame=a.hp<=0?2:a.hp<a.maxHp*.6?1:0;burst(s.x,s.y,4,'#ab876c',100,.35);if(a.hp<=0){score+=25;if(Math.random()<.6)drops.push({x:a.x,y:a.y-25,type:'ammo',life:20,vy:-140,fixed:false})}if(s.type===2)explode(s.x,s.y,s.damage);hit=true;break}}}
 else if(pointBox(s.x,s.y,p)){hurtPlayer(s.damage,s.x);hit=true}
 if(!hit)for(const q of world.platforms){if(s.x>q.x&&s.x<q.x+q.w&&s.y>q.y+7&&s.y<q.y+q.h){if(s.type===2)explode(s.x,s.y,s.damage);else burst(s.x,s.y,3,'#bb9670',80,.2);hit=true;break}}
 if(hit){s.life=0;break}}
 }shots=shots.filter(s=>s.life>0&&s.x>-100&&s.x<world.width+100)}
function getPickup(d){if(d.type==='health'){if(p.hp>=100)return false;p.hp=Math.min(100,p.hp+25);floatText(d.x,d.y,'+25 HEALTH','#b5df7b')}else if(d.type==='armor'){if(p.armor>=100)return false;p.armor=Math.min(100,p.armor+35);floatText(d.x,d.y,'+35 ARMOR','#82daec')}else if(d.type==='ammo'){ammo[1]=Math.min(400,ammo[1]+35);ammo[2]=Math.min(35,ammo[2]+3);floatText(d.x,d.y,'+AMMO')}else if(d.type.startsWith('weapon')){const n=Number(d.type.at(-1));unlocked=Math.max(unlocked,n+1);weapon=n;notify(`${WEAPONS[n].name} ACQUIRED · PRESS ${n+1}`,4);shake=3}sound('pickup');return true}
function updateDrops(dt){for(const d of drops){d.life-=dt;if(!d.fixed){const py=d.y;d.vy+=850*dt;d.y+=d.vy*dt;for(const q of world.platforms)if(d.x>q.x&&d.x<q.x+q.w&&py<q.y-10&&d.y>=q.y-10){d.y=q.y-10;d.vy=0;d.fixed=true}}if(Math.abs(d.x-p.x)<48&&Math.abs(d.y-(p.y-35))<62&&getPickup(d))d.life=0}drops=drops.filter(d=>d.life>0&&d.y<1000)}
function trackCamera(snap=false){if(!p||!world)return;const tx=clamp(p.x-view.w*.38+p.face*45,0,Math.max(0,world.width-view.w));const ty=clamp(p.y-view.h*.66,-Math.max(140,view.h-790),90);camera.x=snap?tx:lerp(camera.x,tx,.09);camera.y=snap?ty:lerp(camera.y,ty,.085)}
function update(dt){clock+=dt;if(state==='menu'){menuTime+=dt;return}if(state!=='playing'){updateParticles(dt);return}levelTime+=dt;runTime+=dt;ambience(dt);p.shotCool=Math.max(0,p.shotCool-dt);p.fireAnim=Math.max(0,p.fireAnim-dt);p.hurt=Math.max(0,p.hurt-dt);p.invul=Math.max(0,p.invul-dt);p.dashCool=Math.max(0,p.dashCool-dt);p.gloryCool=Math.max(0,p.gloryCool-dt);p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);p.coyote=Math.max(0,p.coyote-dt);comboTimer-=dt;if(comboTimer<=0)combo=0;
 const axis=(input.right?1:0)-(input.left?1:0);if(p.dash>0){p.dash-=dt;p.vx=p.face*1050;p.vy=0;if(Math.random()>.4)burst(p.x-p.face*22,p.y-38,2,'#ffa662',60,.24)}else{p.vx=lerp(p.vx,axis*365,Math.min(1,dt*(p.ground?20:12)));p.vy=Math.min(1100,p.vy+1950*dt);if(aim.active&&!touchMode)p.face=aim.x+camera.x>=p.x?1:-1;else if(axis)p.face=axis}
 const wasground=p.ground;moveBody(p,dt);if(p.ground){p.jumps=0;p.coyote=.1;tryJump()}else if(wasground&&p.jumps===0)p.jumps=1;
 if(input.fire)fire();if(p.y>1050){p.hp=0;die()}
 updateEnemies(dt);updateShots(dt);updateDrops(dt);updateParticles(dt);
 for(const h of hazards){if(h.pit)continue;h.active=Math.sin(clock*1.7+h.phase)>.35;if(h.active&&p.dash<=0&&p.x>h.x-p.w/2&&p.x<h.x+h.w+p.w/2&&p.y>h.y-10&&p.y-p.h<h.y+h.h)hurtPlayer(14,h.x+h.w/2)}
 if(!checkpointSeen&&p.x>world.width*.46){checkpointSeen=true;checkpoint=Math.floor(world.width*.46);checkpointSeals=seals.filter(s=>s.broken).map(s=>s.index);p.hp=Math.min(100,p.hp+25);notify('CHECKPOINT · +25 HEALTH',2.7);sound('pickup')}
 updateGate();if(gateOpen&&p.x>world.width-200&&p.y>440)finishLevel();
 trackCamera();noticeTimer-=dt;if(noticeTimer<=0)$('notice').style.opacity=0;introTimer-=dt;if(introTimer<.6)$('level-intro').style.opacity=clamp(introTimer/.6,0,1);shake=Math.max(0,shake-dt*30);flash=Math.max(0,flash-dt);hudTimer-=dt;if(hudTimer<=0){updateHUD();hudTimer=1/20}}
function updateParticles(dt){for(const a of particles){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=500*dt}particles=particles.filter(a=>a.life>0);for(const a of floating){a.life-=dt;a.y-=35*dt}floating=floating.filter(a=>a.life>0)}
function updateHUD(){if(!p)return;$('health-value').textContent=Math.ceil(p.hp);$('health-meter').style.width=p.hp+'%';$('armor-value').textContent=Math.ceil(p.armor);$('armor-meter').style.width=p.armor+'%';$('weapon-name').textContent=WEAPONS[weapon].name;$('ammo-value').textContent=weapon===0?'∞':ammo[weapon];$('ammo-label').textContent=' '+WEAPONS[weapon].short;$('weapon-hint').textContent=unlocked===1?'1 SHOTGUN · FIND MORE WEAPONS':'1 SHOTGUN · 2 PLASMA · 3 ROCKET';$('dash-meter').style.width=((1-clamp(p.dashCool/1.05,0,1))*100)+'%';$('dash-label').textContent=p.dashCool>0?'RECHARGING':'DASH READY';$('score-value').textContent=String(score).padStart(5,'0');$('combo').textContent=combo>=3?`×${1+Math.floor(Math.min(combo,12)/3)} · ${combo} KILL STREAK`:'RIP & TEAR';$('kill-value').textContent=kills+' DEMONS SLAIN';const boss=enemies.find(e=>e.boss&&!e.dead);$('boss-hud').classList.toggle('hidden',!boss||Math.abs(boss.x-p.x)>1200);if(boss)$('boss-meter').style.width=100*boss.hp/boss.maxHp+'%'}
function formatTime(t){return `${Math.floor(t/60)}:${String(Math.floor(t)%60).padStart(2,'0')}`}
function finishLevel(){if(state!=='playing')return;score+=1000+Math.max(0,1200-Math.floor(levelTime*4));if(level<4){save={level:level+1,score,totalKills,runTime};try{localStorage.setItem('doom-hellbound-save-v1',JSON.stringify(save))}catch{}showDialog('clear')}else{save=null;try{localStorage.removeItem('doom-hellbound-save-v1')}catch{}showDialog('victory')}sound('seal')}
function showDialog(kind){showScreen(kind);const data={paused:['TAKE A BREATH','PAUSED','Hell can wait.','RESUME'],dead:['THE FIGHT ISN’T OVER','YOU DIED',checkpointSeen?'Rise again at the checkpoint.':'The Slayer gets back up.','TRY AGAIN'],clear:['SECTOR PURGED','GATE BREACHED',`Next: ${THEMES[Math.min(4,level+1)].name}`,'ENTER NEXT SECTOR'],victory:['ALL FIVE SECTORS PURGED','HELL IS SILENT','Until they hear your footsteps again.','PLAY AGAIN']}[kind];$('dialog-kicker').textContent=data[0];$('dialog-title').textContent=data[1];$('dialog-copy').textContent=data[2];$('dialog-primary').innerHTML=data[3]+' <span>›</span>';$('pause-help').classList.toggle('hidden',kind!=='paused');$('result-stats').classList.toggle('hidden',kind==='paused'||kind==='dead');$('result-stats').innerHTML=`<div><strong>${score.toLocaleString()}</strong><span>SCORE</span></div><div><strong>${kind==='victory'?totalKills:kills}</strong><span>DEMONS SLAIN</span></div><div><strong>${formatTime(kind==='victory'?runTime:levelTime)}</strong><span>TIME</span></div>`;$('restart').classList.toggle('hidden',kind==='victory');$('dialog-primary').focus({preventScroll:true})}
function startRun(continued=false){if(!assetsReady)return;sound('click');if(continued&&save){score=save.score||0;totalKills=save.totalKills||0;runTime=save.runTime||0;unlocked=3;startLevel(save.level)}else{score=0;totalKills=0;runTime=0;unlocked=1;startLevel(0)}canvas.focus({preventScroll:true})}
function sprite(key,frame,x,y,w,h,face=1,opacity=1){const im=art[key];if(!im)return;const a=atlas[key]||{cols:1,rows:1},sw=im.width/a.cols,sh=im.height/a.rows;ctx.save();ctx.globalAlpha=opacity;ctx.translate(Math.round(x),Math.round(y));ctx.scale(face,1);ctx.drawImage(im,(frame%a.cols)*sw,Math.floor(frame/a.cols)*sh,sw,sh,-w/2,-h,w,h);ctx.restore()}
function drawAsset(key,x,y,w,h,opacity=1){const im=art[key];if(!im)return;ctx.save();ctx.globalAlpha=opacity;ctx.drawImage(im,x,y,w,h);ctx.restore()}
function repeatLayer(key,factor,top,height,camX,center=false){const im=art[key];if(!im)return;const width=height*(im.width/im.height),offset=camX*factor+(center?width*.5-view.w*.7:0);const start=Math.floor(offset/width);ctx.save();ctx.globalAlpha=1;for(let n=start-1;n<=start+Math.ceil(view.w/width)+1;n++){const x=Math.round(n*width-offset);if(Math.abs(n%2)===1){ctx.save();ctx.translate(x+width,top);ctx.scale(-1,1);ctx.drawImage(im,0,0,width+1,height);ctx.restore()}else ctx.drawImage(im,x,top,width+1,height)}ctx.restore()}
function drawBackground(idx,camX,camY,menu=false){const t=THEMES[idx];ctx.globalAlpha=1;ctx.fillStyle=t.sky;ctx.fillRect(0,0,view.w,view.h);const base=menu?view.h*.98:670-camY,farHeight=Math.max(720,base+30);
 // Solid layer artwork is opaque; native PNG alpha preserves the open sky.
 repeatLayer(`bg-far-${idx}`,.08,base-farHeight,farHeight,camX,true);
 repeatLayer(`bg-mid-${idx}`,.30,base-450,450,camX);
 repeatLayer(`bg-near-${idx}`,.62,base-300,300,camX);
 // Sparse glowing embers are gameplay atmosphere, not a flattened background.
 ctx.fillStyle=idx===2?'#9bd9e888':'#f88d4866';for(let i=0;i<28;i++){const x=((i*173.7-clock*(8+i%4*4)-camX*.12)%view.w+view.w)%view.w,y=((i*71.8-clock*(6+i%7))%view.h+view.h)%view.h;ctx.fillRect(x,y,2+i%2,2+i%2)}
}
function drawTerrain(){const im=art[`tile-${level}`];for(const q of world.platforms){if(q.x+q.w<camera.x-50||q.x>camera.x+view.w+50)continue;const x=q.x-camera.x,y=q.y-camera.y;
 ctx.fillStyle=world.theme.ground;ctx.fillRect(Math.floor(x),Math.floor(y),Math.ceil(q.w),Math.min(q.h,view.h+Math.abs(y)));
 if(im){ctx.save();ctx.beginPath();ctx.rect(x,y,q.w,q.ground?Math.min(q.h,view.h-y+1):q.h);ctx.clip();const tileSize=q.ground?120:100;const sx=Math.max(q.x,Math.floor(camera.x/tileSize)*tileSize);for(let wx=Math.floor(sx/tileSize)*tileSize;wx<Math.min(q.x+q.w,camera.x+view.w+tileSize);wx+=tileSize){ctx.drawImage(im,wx-camera.x,y,tileSize,tileSize);if(q.ground&&y+tileSize<view.h){ctx.fillStyle=world.theme.ground;ctx.fillRect(wx-camera.x,y+tileSize,tileSize+1,view.h-y-tileSize)}}ctx.restore()}
 ctx.fillStyle='#100f16';ctx.fillRect(Math.floor(x),Math.floor(y+q.h-5),q.w,5);ctx.fillStyle=world.theme.color;ctx.fillRect(Math.floor(x),Math.floor(y),q.w,3);ctx.fillStyle='#ffc99d50';ctx.fillRect(Math.floor(x),Math.floor(y+3),q.w,2)}
}
function drawProp(a){const im=art[`prop-${level}`];if(!im)return;const size=107;ctx.drawImage(im,a.frame*im.width/3,0,im.width/3,im.height,a.x-camera.x-size/2,a.y-camera.y-size*.9,size,size)}
function drawHazards(){for(const h of hazards){if(h.x+h.w<camera.x||h.x>camera.x+view.w)continue;const x=h.x-camera.x,y=h.y-camera.y;const col=h.type==='acid'?'#b4de59':h.type==='laser'?'#89e7ff':'#ff7237';ctx.save();if(h.pit){ctx.fillStyle=world.theme.ground;ctx.fillRect(x,y,h.w,view.h-y);ctx.fillStyle=col;ctx.fillRect(x,y+Math.sin(clock*3)*4,h.w,9);ctx.fillStyle='#ffe094';for(let j=0;j<h.w;j+=30)ctx.fillRect(x+j,y+Math.sin(clock*4+j)*3,18,3)}else{drawAsset('barrel',x+10,y-42,45,59);ctx.fillStyle='#120f15';ctx.fillRect(x,y,h.w,25);ctx.fillStyle=h.active?col:'#735039';ctx.fillRect(x,y,h.w,5);if(h.active){ctx.globalAlpha=.75;for(let i=0;i<4;i++){const z=(Math.sin(clock*18+i*4)+1)*14;ctx.fillStyle=col;ctx.fillRect(x+8+i*(h.w-10)/4,y-17-z,5,18+z)}ctx.globalAlpha=1}else{ctx.fillStyle='#faba69';ctx.font='800 11px Oxanium';ctx.textAlign='center';ctx.fillText('!',x+h.w/2,y-18)}}ctx.restore()}}
function drawSeals(){for(const s of seals){if(s.broken)continue;const x=s.x-camera.x,y=s.y-camera.y,bob=Math.sin(clock*3+s.index)*5;ctx.save();ctx.strokeStyle='#ffb962';ctx.lineWidth=3;ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(x,y,48+Math.sin(clock*4)*3,0,TAU);ctx.stroke();ctx.globalAlpha=1;drawAsset('rune',x-39,y-39+bob,78,78);ctx.strokeStyle='#ff7039';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,48,-Math.PI/2,-Math.PI/2+TAU*s.hp/s.maxHp);ctx.stroke();ctx.font='800 10px Oxanium';ctx.textAlign='center';ctx.fillStyle='#ffe1b1';ctx.fillText('DEMON SEAL',x,y-64);ctx.restore()}}
function drawEnemy(e){const x=e.x-camera.x,y=e.y-camera.y;if(x<-200||x>view.w+200)return;let frame=e.type==='caco'?0:e.stagger||e.hurt>0?4:e.hurt<0||e.telegraph>0||e.charge>0?3:Math.abs(e.vx)>4?1+Math.floor(e.stride/42)%2:0;if(e.type==='caco')frame=e.dead?3:e.hurt>0||e.stagger?2:e.hurt<0?1:0;else if(e.dead)frame=5;
 const size=e.draw*(e.boss?1.32:1);ctx.save();if(e.telegraph>0){ctx.strokeStyle='#ffb456';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y-e.h*.5,size*.52,0,TAU*clamp(1-e.telegraph/.66,0,1));ctx.stroke()}
 if(e.stagger){ctx.fillStyle='#f9c66a';ctx.font='800 13px Oxanium';ctx.textAlign='center';ctx.fillText(touchMode?'GLORY KILL':'[E] GLORY KILL',x,y-e.h-27);ctx.strokeStyle='#ffd575';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y-e.h/2,size*.43,clock*3,clock*3+Math.PI*1.5);ctx.stroke()}
 sprite(e.type,frame,x,y+size*.1,size,size,e.face,e.dead?clamp(e.dead/.75,0,1):1);
 if(e.hp<e.maxHp&&!e.dead&&!e.boss){ctx.fillStyle='#100f14';ctx.fillRect(x-25,y-e.h-15,50,4);ctx.fillStyle=e.stagger?'#ffce73':'#e55c40';ctx.fillRect(x-25,y-e.h-15,50*e.hp/e.maxHp,4)}ctx.restore()}
function drawPlayer(){let frame=p.hurt>0?5:p.fireAnim>0?4:!p.ground?3:Math.abs(p.vx)>20?1+Math.floor(p.stride/42)%2:0;const size=128,x=p.x-camera.x,y=p.y-camera.y;if(p.dash>0){sprite('slayer',frame,x-p.face*54,y+size*.1,size,size,p.face,.18);sprite('slayer',frame,x-p.face*27,y+size*.1,size,size,p.face,.35)}sprite('slayer',frame,x,y+size*.1,size,size,p.face);if(p.invul>0&&Math.floor(clock*12)%2===0){ctx.strokeStyle='#ffe3a5';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y-39,45,52,0,Math.PI*.12,Math.PI*.75);ctx.stroke()}}
function drawDrops(){for(const d of drops){const x=d.x-camera.x,y=d.y-camera.y+Math.sin(clock*3+d.x)*4,weaponDrop=d.type.startsWith('weapon');const key=weaponDrop?'ammo':d.type;const size=weaponDrop?48:34;drawAsset(key,x-size/2,y-size/2,size,size);if(weaponDrop){ctx.font='800 12px Oxanium';ctx.textAlign='center';ctx.fillStyle=d.type==='weapon1'?'#8decff':'#ffc587';ctx.fillText(d.type==='weapon1'?'PLASMA RIFLE':'ROCKET LAUNCHER',x,y-38);ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=2;ctx.strokeRect(x-size/2-5,y-size/2-5,size+10,size+10)}}}
function drawProjectiles(){for(const s of shots){const x=s.x-camera.x,y=s.y-camera.y;ctx.save();ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=s.type===0?3:4;if(s.friendly&&s.type===0){ctx.beginPath();ctx.moveTo(s.px-camera.x,y);ctx.lineTo(x,y);ctx.stroke()}else{const key=s.friendly?s.type===2?'fireball':'plasma':'fireball';ctx.translate(x,y);ctx.rotate(Math.atan2(s.vy,s.vx));drawAsset(key,-s.r*1.6,-s.r*1.6,s.r*3.2,s.r*3.2)}ctx.restore()}}
function drawParticles(){ctx.save();for(const a of particles){ctx.globalAlpha=clamp(a.life/a.max,0,1);if(a.explosion){const size=a.size*(1.2-a.life/a.max*.4);drawAsset('explosion',a.x-camera.x-size/2,a.y-camera.y-size/2,size,size,ctx.globalAlpha)}else{ctx.fillStyle=a.color;ctx.fillRect(a.x-camera.x,a.y-camera.y,a.size,a.size)}}ctx.textAlign='center';ctx.font='800 17px Oxanium';for(const a of floating){ctx.globalAlpha=Math.min(1,a.life*2);ctx.fillStyle='#0d0d12';ctx.fillText(a.text,a.x-camera.x+2,a.y-camera.y+2);ctx.fillStyle=a.color;ctx.fillText(a.text,a.x-camera.x,a.y-camera.y)}ctx.restore()}
function drawGate(){const x=world.width-140-camera.x,y=620-camera.y;ctx.save();if(gateOpen){ctx.globalAlpha=.3+Math.sin(clock*4)*.1;ctx.fillStyle='#ffb651';ctx.beginPath();ctx.ellipse(x,y-90,82,108,0,0,TAU);ctx.fill();ctx.globalAlpha=1;drawAsset('portal',x-70,y-166.5,140,185)}else{drawAsset('portal',x-65,y-155.7,130,173,.32);ctx.strokeStyle='#a34b38';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-30,y-105);ctx.lineTo(x+30,y-45);ctx.moveTo(x+30,y-105);ctx.lineTo(x-30,y-45);ctx.stroke()}ctx.fillStyle=gateOpen?'#ffd59d':'#cb9b85';ctx.font='800 13px Oxanium';ctx.textAlign='center';ctx.fillText(gateOpen?'EXIT →':'SEALED',x,y-190);ctx.restore()}
function drawCrosshair(){if(!aim.active||touchMode||state!=='playing')return;const {x,y}=aim;ctx.strokeStyle='#fff0d5';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,7,0,TAU);ctx.moveTo(x-14,y);ctx.lineTo(x-10,y);ctx.moveTo(x+10,y);ctx.lineTo(x+14,y);ctx.moveTo(x,y-14);ctx.lineTo(x,y-10);ctx.moveTo(x,y+10);ctx.lineTo(x,y+14);ctx.stroke();ctx.fillStyle='#ff6742';ctx.fillRect(x-1.5,y-1.5,3,3)}
function render(){ctx.setTransform(view.scale*view.dpr,0,0,view.scale*view.dpr,0,0);ctx.globalAlpha=1;ctx.clearRect(0,0,view.w,view.h);if(state==='menu'){drawBackground(0,menuTime*14,0,true);const size=view.w<900?view.h*.65:Math.min(view.h*.93,790),x=view.w<900?view.w*.78:view.w*.77,y=view.h*.91;sprite('slayer',4,x,y+size*.1,size,size,-1);return}
 if(!world||!p)return;drawBackground(level,camera.x,camera.y);ctx.save();if(shake>0)ctx.translate(rnd(-shake,shake),rnd(-shake*.6,shake*.6));drawTerrain();drawHazards();for(const a of props)drawProp(a);drawGate();drawSeals();drawDrops();for(const e of enemies)drawEnemy(e);drawPlayer();drawProjectiles();drawParticles();ctx.restore();
 if(flash>0){ctx.fillStyle=`rgba(236,81,42,${flash*.8})`;ctx.fillRect(0,0,view.w,view.h)}if(p.hp<25&&state==='playing'){ctx.strokeStyle=`rgba(210,28,24,${.3+Math.sin(clock*5)*.14})`;ctx.lineWidth=15;ctx.strokeRect(0,0,view.w,view.h)}drawCrosshair()}
function frame(now){if(!last)last=now;const dt=Math.min(.05,(now-last)/1000);last=now;accum+=dt;let loops=0;while(accum>=1/120&&loops++<7){update(1/120);accum-=1/120}render();requestAnimationFrame(frame)}
function pause(){if(state==='playing')showDialog('paused');else if(state==='paused'){showScreen('playing');canvas.focus({preventScroll:true})}}
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&state==='playing')e.preventDefault();if(['KeyA','ArrowLeft'].includes(e.code))input.left=true;if(['KeyD','ArrowRight'].includes(e.code))input.right=true;if(['KeyJ','KeyZ'].includes(e.code))input.fire=true;if(e.repeat)return;pressed.add(e.code);
 if(['Escape','KeyP'].includes(e.code))pause();if(e.code==='KeyM'){muted=!muted;updateSound()}if(e.code==='Enter'&&state==='menu')startRun(false);if(state!=='playing')return;if(['Space','KeyW','ArrowUp'].includes(e.code))jump();if(['ShiftLeft','ShiftRight','KeyK','KeyX'].includes(e.code))dash();if(['KeyE','KeyL','KeyC'].includes(e.code))glory();if(['Digit1','Digit2','Digit3'].includes(e.code))chooseWeapon(Number(e.code.at(-1))-1)});
addEventListener('keyup',e=>{pressed.delete(e.code);if(['KeyA','ArrowLeft'].includes(e.code))input.left=false;if(['KeyD','ArrowRight'].includes(e.code))input.right=false;if(['KeyJ','KeyZ'].includes(e.code))input.fire=false;if(['Space','KeyW','ArrowUp'].includes(e.code)&&p&&p.vy< -270)p.vy*=.62});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=canvas.getBoundingClientRect();aim.x=(e.clientX-r.left)/view.scale;aim.y=(e.clientY-r.top)/view.scale;aim.active=true});
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;if(e.pointerType!=='touch'){input.fire=true;const r=canvas.getBoundingClientRect();aim.x=(e.clientX-r.left)/view.scale;aim.y=(e.clientY-r.top)/view.scale;aim.active=true}else aim.active=false;e.preventDefault();canvas.focus({preventScroll:true});sound('click')});
addEventListener('pointerup',e=>{if(e.pointerType!=='touch')input.fire=false});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerleave',()=>{aim.active=false;input.fire=false});
for(const b of document.querySelectorAll('[data-hold],[data-action]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);b.classList.add('pressed');aim.active=false;if(b.dataset.hold)input[b.dataset.hold]=true;else({jump,dash,glory,weapon:()=>chooseWeapon((weapon+1)%unlocked)})[b.dataset.action]?.()});const release=e=>{e.preventDefault();b.classList.remove('pressed');if(b.dataset.hold)input[b.dataset.hold]=false};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',()=>{b.classList.remove('pressed');if(b.dataset.hold)input[b.dataset.hold]=false})}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});addEventListener('blur',()=>{input.left=input.right=input.fire=false;if(state==='playing')pause()});
$('play').onclick=()=>startRun(false);$('continue').onclick=()=>startRun(true);$('pause').onclick=pause;$('dialog-primary').onclick=()=>{sound('click');if(state==='paused')pause();else if(state==='dead')startLevel(level,checkpointSeen);else if(state==='clear')startLevel(level+1);else startRun(false)};$('restart').onclick=()=>{sound('click');startLevel(level)};$('back-menu').onclick=()=>{sound('click');showScreen('menu')};
document.querySelectorAll('.sound-button').forEach(b=>b.onclick=()=>{muted=!muted;updateSound();sound('click')});document.querySelectorAll('.fullscreen-button').forEach(b=>b.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}catch{}});
for(const a of document.querySelectorAll('.more-games'))a.href='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
async function load(){resize();updateSound();showScreen('menu');let loaded=0;const total=imageKeys.length+1,play=$('play'),percent=$('menu-load-percent'),fill=$('menu-load-fill');const progress=()=>{loaded++;const n=Math.round(loaded/total*100);percent.textContent=n+'%';fill.style.width=n+'%'};try{
 await Promise.all([...imageKeys.map(key=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{art[key]=im;assets[key]={width:im.width,height:im.height};progress();resolve()};im.onerror=()=>reject(new Error('Artwork did not load: '+key));im.src='assets/'+key+'.png'})),document.fonts.load('800 24px Oxanium').then(progress)]);
 assetsReady=true;play.disabled=false;play.classList.remove('preload-action');play.innerHTML='RIP &amp; TEAR <span>›</span>';showScreen('menu');registerTools();
 }catch(e){play.disabled=false;play.classList.add('load-error');play.innerHTML='<span class="preload-label">LOAD FAILED · RETRY</span><span>↻</span>';play.onclick=()=>location.reload();console.error(e)}}
function registerTools(){const mc=document.modelContext;if(!mc?.registerTool)return;const controller=new AbortController();const definitions=[{name:'get_game_status',description:'Read the current sector, player health, weapons, score, and game state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>getStatus()},{name:'start_game',description:'Start a new game or continue the locally saved campaign from the main menu.',inputSchema:{type:'object',properties:{continueSaved:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false},execute:args=>{if(state!=='menu')throw Error('Return to the main menu first');if(!args||typeof args!=='object'||Object.keys(args).some(k=>k!=='continueSaved')||(args.continueSaved!==undefined&&typeof args.continueSaved!=='boolean'))throw Error('Invalid start options');if(args.continueSaved&&!save)throw Error('No saved campaign');startRun(!!args.continueSaved);return getStatus()}},{name:'set_game_paused',description:'Pause or resume the current game.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},annotations:{readOnlyHint:false},execute:args=>{if(typeof args?.paused!=='boolean'||Object.keys(args).length!==1)throw Error('paused must be boolean');if(!['playing','paused'].includes(state))throw Error('No active game');if(args.paused&&state==='playing'||!args.paused&&state==='paused')pause();return getStatus()}}];for(const tool of definitions)try{Promise.resolve(mc.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}addEventListener('pagehide',()=>controller.abort(),{once:true})}
function getStatus(){return {state,sector:level+1,sectorName:THEMES[level].name,health:p?.hp??null,armor:p?.armor??null,sealsDestroyed:seals.filter(s=>s.broken).length,score,weapon:WEAPONS[weapon].name,gateOpen}}
// A read-only status accessor also makes embeds easy to diagnose.
window.Hellbound={getStatus};
load();requestAnimationFrame(frame);
})();
