/* Half-Life 2: Platformer — self-contained HTML5 game. */
(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('world'), ctx=canvas.getContext('2d',{alpha:false});
const ROOT=$('game'), MENU=$('menu'), MC=$('menuContent'), A={}, keys=new Set(), taps=new Set();
const TITLE='Half-Life 2: Platformer', MORE='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(TITLE);
const THEMES=[
 {id:'city',name:'CITY 17',subtitle:'Follow the lambda. Find the resistance.',objective:'REACH THE RESISTANCE OUTPOST',sky:['#9eb0ad','#d3d0b1'],fog:'#627d83',accent:'#efae57',ground:'#28363b',length:4800,gaps:[[1020,1170],[2210,2390],[3690,3860]],platforms:[[400,424,200],[720,342,165],[1300,418,190],[1560,336,160],[2010,415,140],[2660,418,230],[3050,334,190],[3440,417,140],[4050,407,190]],spawns:[[680,'combine'],[1430,'combine'],[1950,'headcrab'],[2610,'combine'],[2870,'headcrab'],[3280,'combine'],[4090,'combine'],[4380,'combine']],props:[560,1370,1750,2530,3180,4080],cache:[820,1620,2790,3130],end:'The resistance has a route through the canals.'},
 {id:'canal',name:'ROUTE KANAL',subtitle:'Keep moving. Stay out of the water.',objective:'CROSS THE DRAINAGE NETWORK',sky:['#718e8c','#d4bd85'],fog:'#588584',accent:'#b6cb68',ground:'#344745',length:5050,gaps:[[860,1050],[1800,2000],[2940,3150],[3940,4140]],platforms:[[440,415,170],[1100,414,210],[1480,345,160],[2160,415,200],[2590,360,200],[3230,416,180],[3560,340,160],[4220,413,180],[4550,350,160]],spawns:[[660,'headcrab'],[1260,'combine'],[1660,'headcrab'],[2380,'combine'],[2680,'combine'],[3360,'headcrab'],[3760,'combine'],[4360,'combine'],[4750,'combine']],props:[520,1210,1650,2250,3440,4310],cache:[530,1550,2690,3640],end:'A hidden tunnel leads into the old mining town.'},
 {id:'raven',name:'RAVENHOLM',subtitle:'We don’t go to Ravenholm.',objective:'ESCAPE THROUGH THE OLD QUARTER',sky:['#182c48','#657180'],fog:'#3e4d67',accent:'#d6a562',ground:'#293541',length:4950,gaps:[[1130,1300],[2270,2450],[3520,3730]],platforms:[[470,420,170],[780,339,190],[1350,418,170],[1660,334,150],[2030,414,150],[2630,418,200],[2980,336,160],[3300,418,150],[3840,415,180],[4200,334,160]],spawns:[[650,'zombie'],[1000,'headcrab'],[1510,'zombie'],[1830,'headcrab'],[2180,'zombie'],[2750,'zombie'],[3070,'headcrab'],[3410,'zombie'],[3930,'zombie'],[4320,'headcrab'],[4570,'zombie']],props:[550,1460,1970,2810,3280,3990,4520],cache:[880,1730,3060,4290],end:'The coast is clear. Nova Prospekt is next.'},
 {id:'prison',name:'NOVA PROSPEKT',subtitle:'Break their defenses. Open the way.',objective:'BREACH THE COMBINE PRISON',sky:['#647d79','#adb7a0'],fog:'#52716b',accent:'#97d2bd',ground:'#2b3c3b',length:5100,gaps:[[990,1150],[2410,2620],[3860,4050]],platforms:[[440,420,200],[760,340,160],[1320,415,190],[1690,330,170],[2100,416,180],[2710,415,220],[3130,333,160],[3510,415,150],[4150,410,210],[4480,334,180]],spawns:[[710,'combine'],[1280,'combine'],[1560,'headcrab'],[1930,'combine'],[2270,'combine'],[2850,'combine'],[3090,'headcrab'],[3350,'combine'],[3660,'combine'],[4290,'combine'],[4780,'combine']],props:[560,1370,1810,2190,2790,3390,4300,4740],cache:[860,1790,3220,4590],end:'The Citadel is exposed. End the occupation.'},
 {id:'citadel',name:'OUR BENEFACTORS',subtitle:'One last push. Bring it down.',objective:'DESTROY THE COMBINE STRIDER',sky:['#132e40','#527e8b'],fog:'#2b5b6d',accent:'#8fefff',ground:'#18313e',length:5350,gaps:[[1000,1180],[2170,2370],[3310,3490]],platforms:[[460,420,200],[770,336,160],[1300,415,190],[1650,333,160],[1950,415,140],[2500,415,230],[2870,333,150],[3560,415,180],[3930,350,180],[4310,420,170]],spawns:[[680,'combine'],[1450,'combine'],[1860,'headcrab'],[2630,'combine'],[3070,'combine'],[3660,'combine'],[4070,'combine'],[4800,'strider']],props:[580,1370,1910,2560,2990,3620,4420,4620],cache:[880,1730,2960,4020],end:'The uprising has only just begun.'}
];
const actorMeta={gordon:{cols:3,rows:3,h:102},combine:{cols:3,rows:2,h:103},zombie:{cols:3,rows:2,h:111},headcrab:{cols:3,rows:2,h:42},strider:{cols:3,rows:2,h:290}};
let W=1280,H=720,DPR=1,VW=1280,VH=720,scale=1,realTime=0,phase='loading',menuOrigin='main',ready=false,loadError=false,assetDone=0,loadedPercent=0,muted=false,ac=null,master=null,saveData=null,toastTime=0,introTime=0,transition=null;
let state=null,checkpoint=null,cam={x:0,y:0},shake=0,hitFlash=0,anim=0,loadingPromise=null;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rectHit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const playerRect=p=>({x:p.x-16,y:p.y-77,w:32,h:77});
const enemyRect=e=>({x:e.x-e.w/2,y:e.y-e.h,w:e.w,h:e.h});
function touchUI(){return matchMedia('(pointer:coarse)').matches||W<700||H<500;}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);VH=W/H<.8?1000:720;scale=H/VH;VW=W/scale;ROOT.classList.toggle('touch-ui',touchUI());if(phase==='playing')$('touchControls').hidden=!touchUI();if(state)cam.x=clamp(cam.x,0,Math.max(0,THEMES[state.chapter].length-VW));}
addEventListener('resize',resize);resize();
try{saveData=JSON.parse(localStorage.getItem('hl2-platformer-v1')||'null');if(!saveData||saveData.chapter<0||saveData.chapter>4)saveData=null;muted=localStorage.getItem('hl2-muted')==='1';}catch{}
function persist(){if(!state)return;try{saveData={chapter:state.chapter,score:checkpoint?.score||state.score};localStorage.setItem('hl2-platformer-v1',JSON.stringify(saveData));}catch{}}
function sound(type){if(muted)return;try{if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.17;master.connect(ac.destination);}if(ac.state==='suspended')ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(master);const t=ac.currentTime;let f=220,to=80,d=.12,vol=.32,wave='triangle';if(type==='none'){vol=0;d=.01;}if(type==='shot'){f=170;to=45;d=.075;wave='sawtooth';vol=.18;}if(type==='hit'){f=130;to=40;d=.1;wave='square';vol=.15;}if(type==='jump'){f=180;to=360;d=.11;vol=.1;}if(type==='gravity'){f=75;to=600;d=.28;wave='sawtooth';vol=.2;}if(type==='pickup'){f=660;to=990;d=.16;vol=.17;}if(type==='reload'){f=450;to=290;d=.065;vol=.15;}if(type==='checkpoint'){f=520;to=1040;d=.3;vol=.15;}o.type=wave;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(to,t+d);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.start(t);o.stop(t+d+.01);}catch{}}
function clearInput(){keys.clear();taps.clear();document.querySelectorAll('.active').forEach(e=>e.classList.remove('active'));}
const keyMap={KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',Space:'jump',KeyW:'jump',ArrowUp:'jump',KeyJ:'melee',KeyZ:'melee',KeyK:'shoot',KeyX:'shoot',KeyL:'gravity',KeyC:'gravity',KeyE:'gravity',KeyR:'reload'};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape'].includes(e.code))e.preventDefault();if(e.repeat&&['Escape','KeyP','KeyM','KeyF'].includes(e.code))return;if(e.code==='Escape'||e.code==='KeyP'){if(phase==='playing')showMenu('pause');else if(phase==='pause')resume();else if(phase==='help')showMenu(menuOrigin);return;}if(e.code==='KeyM'){toggleMute();return;}if(e.code==='KeyF'){fullscreen();return;}const k=keyMap[e.code];if(k&&phase==='playing'){e.preventDefault();if(!keys.has(k))taps.add(k);keys.add(k);}});
addEventListener('keyup',e=>{const k=keyMap[e.code];if(k){keys.delete(k);if(k==='jump'&&state?.p.vy< -260)state.p.vy=-260;}});
addEventListener('blur',()=>{clearInput();if(phase==='playing')showMenu('pause');});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(phase==='playing')showMenu('pause');}});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(phase!=='playing')return;b.setPointerCapture(e.pointerId);const k=b.dataset.key;if(!keys.has(k))taps.add(k);keys.add(k);b.classList.add('active');sound('none');});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>{e.preventDefault();keys.delete(b.dataset.key);b.classList.remove('active');if(b.dataset.key==='jump'&&state?.p.vy< -260)state.p.vy=-260;});});
function toggleMute(){muted=!muted;$('mute').textContent=muted?'♪':'♫';$('mute').style.opacity=muted?'.5':'1';$('mute').setAttribute('aria-label',muted?'Enable sound':'Mute sound');try{localStorage.setItem('hl2-muted',String(+muted));}catch{}}
$('mute').textContent=muted?'♪':'♫';$('mute').onclick=toggleMute;
function fullscreen(){if(document.fullscreenElement){document.exitFullscreen?.();return;}if(ROOT.requestFullscreen)ROOT.requestFullscreen().catch(()=>toast('FULLSCREEN IS UNAVAILABLE'));else toast('FULLSCREEN IS UNAVAILABLE');}
$('fullscreen').onclick=fullscreen;$('pause').onclick=()=>showMenu('pause');document.querySelector('.ammo').onclick=()=>{if(phase==='playing')reload();};
const moreButton=()=>`<a class="more-games" href="${MORE}" target="_blank" rel="noopener noreferrer">MORE GAMES <span aria-hidden="true">↗</span></a>`;
const primary=(text,action,disabled='')=>`<button class="primary" data-action="${action}" ${disabled}>${text}<span aria-hidden="true">→</span></button>`;
const textButton=(text,action)=>`<button class="text-action" data-action="${action}">${text}</button>`;
function showMenu(next){clearInput();phase=next;ROOT.classList.remove('playing');MENU.hidden=false;$('hud').hidden=true;$('touchControls').hidden=true;$('bossHud').hidden=true;$('chapterIntro').classList.remove('show');$('toast').classList.remove('show');MC.className=next;let html='';
 if(next==='main'||next==='loading'){
  html=`<p class="eyebrow">THE RIGHT MAN. THE WRONG PLACE.</p><h1>HALF-LIFE<sup>2</sup></h1><p class="genre">PLATFORMER</p><p class="menu-description">Rise against the Combine.<br>Five chapters. One crowbar.</p><div class="menu-actions">${primary(loadError?'RETRY LOADING':ready?'START GAME':`LOADING ${loadedPercent}%`,loadError?'retryLoad':'start',!ready&&!loadError?'disabled':'')}${moreButton()}</div><div class="secondary-actions">${ready&&(state||saveData)?textButton('CONTINUE','continue'):''}${textButton('HOW TO PLAY','help')}</div>${loadError?'<p class="error-note">Artwork could not load. Check your connection and retry.</p>':''}<div class="chapter-tag"><small>CHAPTER 01 / 05</small> CITY 17</div>`;
 }else if(next==='help'){
  html=`<p class="eyebrow">HEV TRAINING</p><h2 class="panel-title">STAY <em>ALIVE.</em></h2><div class="help-grid"><div><b>A / D · ARROWS</b><span>Move</span></div><div><b>SPACE / W / ↑</b><span>Jump · hold for height</span></div><div><b>J / Z</b><span>Crowbar</span></div><div><b>K / X</b><span>Fire SMG · R to reload</span></div><div><b>L / C / E</b><span>Gravity pulse · grab / throw prop</span></div><div><b>ESC / P</b><span>Pause</span></div></div><p class="help-note">Follow the orange lambda marks. Break supplies for health. Touch a checkpoint to save your position. On touchscreens, tap the SMG counter to reload.</p><div class="menu-actions">${primary('BACK','back')}${moreButton()}</div>`;
 }else if(next==='pause'){
  html=`<p class="eyebrow">HEV SYSTEMS ON STANDBY</p><h2 class="panel-title">GAME<br><em>PAUSED.</em></h2><p class="menu-description">Chapter ${state.chapter+1} / 5 · ${THEMES[state.chapter].name}</p><div class="menu-actions">${primary('RESUME','resume')}${moreButton()}</div><div class="secondary-actions">${textButton('HOW TO PLAY','help')}${textButton('RETRY CHECKPOINT','retry')}${textButton('MAIN MENU','main')}</div>`;
 }else if(next==='defeat'){
  html=`<p class="eyebrow">VITAL SIGNS CRITICAL</p><h2 class="panel-title">RISE<br><em>AGAIN.</em></h2><p class="menu-description">Your checkpoint is ready.<br>The resistance still needs you.</p><div class="menu-actions">${primary('RETRY CHECKPOINT','retry')}${moreButton()}</div><div class="secondary-actions">${textButton('MAIN MENU','main')}</div>`;
 }else if(next==='chapter'||next==='victory'){
  const final=next==='victory';html=`<p class="eyebrow">${final?'THE FREE MAN':'CHAPTER '+String(state.chapter+1).padStart(2,'0')+' COMPLETE'}</p><h2 class="panel-title">${final?'RISE AND<br><em>SHINE.</em>':'KEEP<br><em>MOVING.</em>'}</h2><p class="menu-description">${THEMES[state.chapter].end}</p><div class="stat-row"><div><strong>${String(state.score).padStart(6,'0')}</strong><span>SCORE</span></div><div><strong>${state.kills}</strong><span>HOSTILES DOWN</span></div><div><strong>${Math.ceil(state.p.hp)}%</strong><span>HEALTH</span></div></div><div class="menu-actions">${primary(final?'PLAY AGAIN':'NEXT CHAPTER',final?'start':'next')}${moreButton()}</div><div class="secondary-actions">${textButton('MAIN MENU','main')}</div>`;
 }
 MC.innerHTML=html;MC.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.action)));}
function act(action){sound('none');if(action==='start'){if(ready)startTransition(()=>startChapter(0,0));}else if(action==='continue'){if(state){if(state.p.hp<=0){startTransition(restoreCheckpoint);return;}if(state.complete)showMenu(state.chapter===4?'victory':'chapter');else resume();}else if(saveData)startTransition(()=>startChapter(saveData.chapter,saveData.score));}else if(action==='resume')resume();else if(action==='main')showMenu('main');else if(action==='help'){menuOrigin=(phase==='loading'||phase==='main')?'main':phase;showMenu('help');}else if(action==='back')showMenu(menuOrigin);else if(action==='retry')startTransition(restoreCheckpoint);else if(action==='next')startTransition(()=>startChapter(state.chapter+1,state.score));else if(action==='retryLoad')loadAssets();}
function resume(){if(!state)return;clearInput();phase='playing';MENU.hidden=true;ROOT.classList.add('playing');$('hud').hidden=false;$('touchControls').hidden=!touchUI();updateHud();}
function startTransition(fn){clearInput();phase='transition';MENU.hidden=true;ROOT.classList.remove('playing');$('hud').hidden=true;$('touchControls').hidden=true;$('transition').classList.add('black');transition={t:0,fn,done:false};}
function makeEnemy(x,type,i){const m={combine:[62,34,79],zombie:[86,40,81],headcrab:[33,42,27],strider:[1500,146,226]}[type];return {id:i,x,y:540,vx:0,vy:0,grounded:true,type,hp:m[0],maxHp:m[0],w:m[1],h:m[2],dir:-1,home:x,walk:0,cd:.7+i*.15,wind:0,attack:0,hurt:0,dead:0,stun:0,phase:0,shot:false};}
function startChapter(chapter,score){const t=THEMES[chapter];let plats=[];let last=0;t.gaps.forEach(g=>{plats.push({x:last,y:540,w:g[0]-last,h:900,ground:true});last=g[1];});plats.push({x:last,y:540,w:t.length-last,h:900,ground:true});t.platforms.forEach(p=>plats.push({x:p[0],y:p[1],w:p[2],h:30,ground:false}));
 state={chapter,score,kills:0,time:0,complete:false,p:{x:120,y:540,vx:0,vy:0,dir:1,hp:100,energy:100,ammo:30,reloading:0,grounded:true,coyote:.1,buffer:0,walk:0,invul:0,shot:0,melee:0,meleeHit:false,meleeCd:0,combo:0,comboTime:0,grav:0,hurt:0,held:null},platforms:plats,enemies:t.spawns.map((e,i)=>makeEnemy(e[0],e[1],i)),props:t.props.map((x,i)=>({id:i,x,y:540,vx:0,vy:0,hp:2,state:0,held:false,thrown:false,drop:false,angle:0})),bullets:[],fx:[],texts:[],pickups:[],checkpoints:[1720,3370].map(x=>({x:t.gaps.some(g=>x>g[0]-40&&x<g[1]+40)?t.gaps.find(g=>x>g[0]-40&&x<g[1]+40)[1]+130:x,on:false})),caches:t.cache.map((x,i)=>({x,y:t.platforms.find(p=>x>=p[0]&&x<=p[0]+p[2])?.[1]-28||400,taken:false})),exit:t.length-150};
 cam={x:0,y:540-VH*.77};shake=0;hitFlash=0;checkpoint=JSON.parse(JSON.stringify({s:state,score:state.score}));persist();resume();introTime=3.5;$('introNumber').textContent='CHAPTER '+String(chapter+1).padStart(2,'0')+' / 05';$('introTitle').textContent=t.name;$('introText').textContent=t.subtitle;$('chapterIntro').classList.add('show');toastTime=0;
}
function restoreCheckpoint(){if(!checkpoint){startChapter(state?.chapter||0,state?.score||0);return;}state=JSON.parse(JSON.stringify(checkpoint.s));Object.assign(state.p,{hp:100,energy:100,ammo:30,invul:1.4,vx:0,vy:0,shot:0,melee:0,reloading:0,held:null});state.bullets=[];state.fx=[];state.texts=[];state.complete=false;cam={x:clamp(state.p.x-VW*.32,0,THEMES[state.chapter].length-VW),y:540-VH*.77};hitFlash=0;shake=0;resume();toast('CHECKPOINT RESTORED');}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastTime=2.1;}
function puff(x,y,color,n=8,power=140){for(let i=0;i<n;i++)state.fx.push({x,y,vx:rand(-power,power),vy:rand(-power,power*.2),life:rand(.2,.5),max:.5,color,size:rand(2,5)});}
function floatText(x,y,text,color='#ffbf69'){state.texts.push({x,y,text,color,life:.8});}
function damagePlayer(n,dir=0){const p=state.p;if(p.invul>0||p.hp<=0||phase!=='playing')return;p.hp=Math.max(0,p.hp-n);p.invul=1.05;p.hurt=.25;p.vx=dir*180;p.vy=Math.min(p.vy,-150);hitFlash=.2;shake=5;puff(p.x,p.y-43,'#eca159',8);sound('hit');if(p.hp<=0){p.hurt=1;showMenu('defeat');}updateHud();}
function damageEnemy(e,n,kick=0){if(e.hp<=0)return;e.hp-=n;e.hurt=.18;if(e.type!=='strider'){e.stun=.14;e.vx=kick;e.wind=0;e.attack=0;e.cd=Math.max(e.cd,.5);}puff(e.x,e.y-e.h*.55,e.type==='headcrab'||e.type==='zombie'?'#d2b365':'#a4e1e4',7);if(e.hp<=0){e.hp=0;e.dead=1.3;state.kills++;state.score+=e.type==='strider'?2500:e.type==='headcrab'?120:200;floatText(e.x,e.y-e.h,'+'+(e.type==='strider'?2500:e.type==='headcrab'?120:200));sound('hit');if(e.type==='strider'){shake=12;puff(e.x,e.y-120,'#93efff',55,300);toast('STRIDER DOWN · REACH THE EXIT');state.pickups.push({x:e.x-90,y:480,vy:-190,type:'health',taken:false});}else if(e.id%3===1)state.pickups.push({x:e.x,y:e.y-25,vy:-160,type:'health',taken:false});}}
function propHit(o,n=1){if(o.hp<=0)return;o.hp-=n;o.state=o.hp<=0?2:1;puff(o.x,o.y-30,THEMES[state.chapter].accent,9);sound('hit');if(o.hp<=0&&!o.drop){o.drop=true;o.held=false;o.thrown=false;o.angle=0;o.vx=0;o.vy=0;state.score+=50;state.pickups.push({x:o.x,y:o.y-35,vy:-190,type:'health',taken:false});state.pickups.push({x:o.x+18,y:o.y-30,vy:-230,type:'energy',taken:false});if(state.p.held===o.id)state.p.held=null;}}
function reload(){const p=state.p;if(p.ammo>=30||p.reloading>0)return;p.reloading=1.1;sound('reload');toast('RELOADING');}
function shoot(){const p=state.p;if(p.shot>0||p.reloading>0)return;if(p.ammo<=0){reload();return;}p.ammo--;p.shot=.12;state.bullets.push({x:p.x+p.dir*38,y:p.y-54,vx:p.dir*830,vy:0,life:.8,enemy:false,damage:23,color:'#ffd28a',r:3});sound('shot');if(p.ammo<=0)toast('R · RELOAD');}
function melee(){const p=state.p;if(p.meleeCd>0)return;p.combo=p.comboTime>0?(p.combo+1)%3:0;p.comboTime=.8;p.melee=.23;p.meleeCd=.32;p.meleeHit=false;sound('hit');}
function gravity(){const p=state.p;if(p.grav>0||p.energy<30)return;p.grav=.42;p.energy-=30;sound('gravity');shake=3;const held=state.props.find(o=>o.id===p.held);if(held){held.held=false;held.thrown=true;held.vx=p.dir*680;held.vy=-85;p.held=null;toast('PROP LAUNCHED');return;}const target=state.props.find(o=>o.hp>0&&!o.thrown&&!o.held&&(o.x-p.x)*p.dir>-15&&(o.x-p.x)*p.dir<190&&Math.abs(o.y-p.y)<65);if(target){target.held=true;p.held=target.id;toast('L · THROW');return;}const cone={x:p.x+(p.dir>0?0:-250),y:p.y-135,w:250,h:145};for(const e of state.enemies)if(e.hp>0&&rectHit(cone,enemyRect(e))){damageEnemy(e,e.type==='strider'?95:65,p.dir*440);if(e.type!=='strider')e.vy=-190;}for(const b of state.bullets)if(b.enemy&&Math.abs(b.x-p.x)<210&&Math.abs(b.y-(p.y-40))<120){b.enemy=false;b.vx=p.dir*Math.max(650,Math.abs(b.vx));b.vy=0;b.damage=70;b.color='#87ebff';}puff(p.x+p.dir*80,p.y-50,'#7de9ff',17,230);}
function physics(body,dt,h=77,w=32){const oldY=body.y;body.vy=Math.min(900,body.vy+1500*dt);body.x+=body.vx*dt;body.y+=body.vy*dt;body.grounded=false;for(const q of state.platforms){if(body.x+w/2>q.x&&body.x-w/2<q.x+q.w&&oldY<=q.y+2&&body.y>=q.y&&body.vy>=0){body.y=q.y;body.vy=0;body.grounded=true;break;}}}
function walkEdge(e,dir){return state.platforms.some(q=>e.x+dir*(e.w/2+18)>=q.x&&e.x+dir*(e.w/2+18)<=q.x+q.w&&Math.abs(e.y-q.y)<9);}
function update(dt){if(!state||phase!=='playing')return;const s=state,p=s.p,t=THEMES[s.chapter];s.time+=dt;p.invul=Math.max(0,p.invul-dt);p.hurt=Math.max(0,p.hurt-dt);p.shot=Math.max(0,p.shot-dt);p.grav=Math.max(0,p.grav-dt);p.meleeCd=Math.max(0,p.meleeCd-dt);p.comboTime=Math.max(0,p.comboTime-dt);p.energy=Math.min(100,p.energy+15*dt);
 if(p.reloading>0){p.reloading-=dt;if(p.reloading<=0){p.ammo=30;sound('reload');}}
 if(taps.has('reload'))reload();if(taps.has('jump'))p.buffer=.12;else p.buffer=Math.max(0,p.buffer-dt);p.coyote=p.grounded?.11:Math.max(0,p.coyote-dt);
 let move=(keys.has('right')?1:0)-(keys.has('left')?1:0);if(p.hurt<=0){const target=move*290,change=dt*(move?2400:2800);p.vx+=clamp(target-p.vx,-change,change);if(move)p.dir=move;}
 if(p.buffer>0&&p.coyote>0){p.vy=-675;p.grounded=false;p.coyote=0;p.buffer=0;sound('jump');}
 if(keys.has('shoot')||taps.has('shoot'))shoot();if(keys.has('melee')||taps.has('melee'))melee();if(taps.has('gravity'))gravity();taps.clear();
 const ox=p.x;physics(p,dt);p.x=clamp(p.x,20,t.length-35);p.walk+=Math.abs(p.x-ox);if(p.y>950){p.hp=0;showMenu('defeat');return;}
 if(p.melee>0){p.melee-=dt;if(p.melee<.13&&!p.meleeHit){p.meleeHit=true;const hit={x:p.x+(p.dir>0?5:-103),y:p.y-95,w:105,h:98};for(const e of s.enemies)if(e.hp>0&&rectHit(hit,enemyRect(e)))damageEnemy(e,p.combo===2?58:40,p.dir*260);for(const o of s.props)if(o.hp>0&&!o.held&&rectHit(hit,{x:o.x-25,y:o.y-68,w:50,h:68}))propHit(o,1);}}
 for(const e of s.enemies){if(e.hp<=0){e.dead=Math.max(0,e.dead-dt);continue;}if(Math.abs(e.x-p.x)>1100)continue;e.hurt=Math.max(0,e.hurt-dt);e.stun=Math.max(0,e.stun-dt);e.cd-=dt;const dx=p.x-e.x,dy=p.y-e.y,dist=Math.abs(dx);e.dir=dx>=0?1:-1;const oldX=e.x;
  if(e.type==='strider'){e.vx=0;if(dist<800){if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.attack=.35;e.phase++;e.cd=e.hp<350?1.15:1.7;for(let i=-1;i<=1;i++){const x=e.x-68,y=e.y-166,angle=Math.atan2(p.y-42-y,p.x-x)+i*.115;s.bullets.push({x,y,vx:Math.cos(angle)*390,vy:Math.sin(angle)*390,life:3,enemy:true,damage:18,color:'#80e6ff',r:8});}if(e.phase%3===0)s.bullets.push({x:e.x-35,y:532,vx:-370,vy:0,life:3,enemy:true,damage:22,color:'#95f4ff',r:13});sound('gravity');}}else if(e.cd<=0){e.wind=.78;}}e.attack=Math.max(0,e.attack-dt);continue;}
  if(e.stun>0){e.vx*=.97;}else if(e.wind>0){e.vx=0;e.wind-=dt;if(e.wind<=0){e.attack=e.type==='headcrab'?.6:.3;e.shot=false;if(e.type==='headcrab'){e.vx=e.dir*330;e.vy=-330;}else if(e.type==='combine'){const angle=Math.atan2(dy,p.x-e.x);s.bullets.push({x:e.x+e.dir*29,y:e.y-55,vx:Math.cos(angle)*e.dir*0+e.dir*430,vy:clamp(dy*.7,-200,200),life:1.5,enemy:true,damage:12,color:'#abedf6',r:4});sound('shot');}else{e.vx=e.dir*150;}}}
  else if(e.attack>0){e.attack-=dt;if(e.type==='zombie'&&dist<64&&Math.abs(dy)<80)damagePlayer(17,e.dir);if(e.type==='headcrab'&&rectHit(enemyRect(e),playerRect(p)))damagePlayer(14,e.dir);if(e.attack<=0){e.cd=e.type==='combine'?1.4:1.2;e.vx=0;}}
  else if(e.cd<=0&&dist<(e.type==='combine'?440:e.type==='headcrab'?240:95)&&Math.abs(dy)<(e.type==='combine'?170:80)){e.wind=e.type==='combine'?.6:e.type==='headcrab'?.38:.45;e.vx=0;}
  else{const speed=e.type==='zombie'?65:e.type==='headcrab'?88:62;e.vx=dist<(e.type==='combine'?320:44)?0:e.dir*speed;if(dist>530)e.vx=Math.sin(s.time*.5+e.id)>0?speed*.4:-speed*.4;if(e.grounded&&!walkEdge(e,Math.sign(e.vx)))e.vx=0;}
  physics(e,dt,e.h,e.w);e.walk+=Math.abs(e.x-oldX);if(e.y>950)damageEnemy(e,999);if(rectHit(enemyRect(e),playerRect(p))&&e.type!=='combine')damagePlayer(10,e.dir);
 }
 for(const o of s.props){if(o.held){o.x=p.x+p.dir*73;o.y=p.y-29+Math.sin(s.time*5)*3;o.angle=0;continue;}if(o.thrown){const oldY=o.y;o.vy+=950*dt;o.x+=o.vx*dt;o.y+=o.vy*dt;o.angle+=dt*8;let impacted=false;for(const e of s.enemies)if(e.hp>0&&rectHit({x:o.x-28,y:o.y-60,w:56,h:60},enemyRect(e))){damageEnemy(e,180,Math.sign(o.vx)*500);impacted=true;}if(o.y>=540&&oldY<=540)impacted=true;if(impacted){for(const e of s.enemies)if(e.hp>0&&Math.abs(e.x-o.x)<130&&Math.abs(e.y-o.y)<150)damageEnemy(e,75,Math.sign(o.vx)*240);o.y=540;propHit(o,99);shake=5;}if(o.x<0||o.x>t.length||o.y>900)propHit(o,99);}}
 for(const b of s.bullets){if(b.life<=0)continue;const steps=Math.max(1,Math.ceil(Math.abs(b.vx*dt)/12));for(let step=0;step<steps&&b.life>0;step++){b.x+=b.vx*dt/steps;b.y+=b.vy*dt/steps;if(b.enemy){if(rectHit({x:b.x-b.r,y:b.y-b.r,w:b.r*2,h:b.r*2},playerRect(p))){damagePlayer(b.damage,Math.sign(b.vx));b.life=0;}}else{for(const e of s.enemies)if(e.hp>0&&rectHit({x:b.x-b.r,y:b.y-b.r,w:b.r*2,h:b.r*2},enemyRect(e))){damageEnemy(e,b.damage,Math.sign(b.vx)*55);b.life=0;break;}if(b.life>0)for(const o of s.props)if(o.hp>0&&!o.held&&!o.thrown&&Math.abs(b.x-o.x)<26&&b.y>o.y-66&&b.y<o.y){propHit(o,1);b.life=0;break;}}if(b.life>0&&s.platforms.some(q=>b.x>q.x&&b.x<q.x+q.w&&b.y>q.y&&b.y<q.y+q.h)){puff(b.x,b.y,t.accent,3,80);b.life=0;}}b.life-=dt;}
 s.bullets=s.bullets.filter(b=>b.life>0);
 for(const pick of s.pickups){if(pick.taken)continue;pick.vy+=850*dt;pick.y+=pick.vy*dt;const support=s.platforms.find(q=>pick.x>=q.x&&pick.x<=q.x+q.w&&pick.y>=q.y-16&&pick.y<q.y+80);if(support){pick.y=support.y-16;pick.vy=0;}if(Math.abs(pick.x-p.x)<35&&Math.abs(pick.y-(p.y-35))<65){pick.taken=true;if(pick.type==='health'){p.hp=Math.min(100,p.hp+22);floatText(p.x,p.y-95,'+22 HEALTH');}else{p.energy=Math.min(100,p.energy+35);floatText(p.x,p.y-110,'+35 ENERGY','#9aeeff');}sound('pickup');}}
 for(const c of s.caches)if(!c.taken&&Math.abs(c.x-p.x)<35&&Math.abs(c.y-(p.y-45))<60){c.taken=true;s.score+=250;p.hp=Math.min(100,p.hp+10);p.energy=100;floatText(c.x,c.y,'+250');sound('pickup');}
 for(const c of s.checkpoints)if(!c.on&&Math.abs(p.x-c.x)<37&&p.grounded&&Math.abs(p.y-540)<5){c.on=true;p.hp=Math.min(100,p.hp+25);p.ammo=30;p.energy=100;const held=s.props.find(o=>o.id===p.held);if(held){held.held=false;held.x=p.x-75;held.y=540;p.held=null;}checkpoint=JSON.parse(JSON.stringify({s,score:s.score}));checkpoint.s.bullets=[];checkpoint.s.fx=[];persist();toast('CHECKPOINT · HEALTH +25 · AMMO REFILLED');sound('checkpoint');}
 const boss=s.enemies.find(e=>e.type==='strider'&&e.hp>0);if(p.x>=s.exit-25&&p.y>=480&&!boss){s.complete=true;s.score+=500+Math.ceil(p.hp*5);persist();showMenu(s.chapter===4?'victory':'chapter');return;}if(p.x>s.exit-150&&boss)toastTime<=0&&toast('DESTROY THE STRIDER');
 for(const f of s.fx){f.life-=dt;f.vy+=380*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}s.fx=s.fx.filter(f=>f.life>0);for(const text of s.texts){text.life-=dt;text.y-=35*dt;}s.texts=s.texts.filter(f=>f.life>0);shake=Math.max(0,shake-dt*20);hitFlash=Math.max(0,hitFlash-dt);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');}if(introTime>0){introTime-=dt;if(introTime<.5)$('chapterIntro').classList.remove('show');}
 const aim=clamp(p.x-VW*.35+p.dir*35,0,Math.max(0,t.length-VW));cam.x+=(aim-cam.x)*Math.min(1,dt*5);cam.y=540-VH*.77;updateHud();
}
function updateHud(){if(!state)return;const p=state.p;$('hpNumber').textContent=Math.ceil(p.hp);$('hpBar').style.width=p.hp+'%';$('hpBar').style.background=p.hp<30?'#ec7053':'#f7a03a';$('energyBar').style.width=p.energy+'%';$('gravityNumber').textContent=Math.floor(p.energy)+'%';$('ammoCount').textContent=p.reloading>0?'··':p.ammo;$('reloadHint').textContent=p.reloading>0?'RELOADING':'R · RELOAD';$('chapterLabel').textContent='CHAPTER '+String(state.chapter+1).padStart(2,'0')+' / 05';$('chapterName').textContent=THEMES[state.chapter].name;$('objective').textContent=THEMES[state.chapter].objective;const boss=state.enemies.find(e=>e.type==='strider'&&e.hp>0&&Math.abs(e.x-p.x)<900);$('bossHud').hidden=!boss||phase!=='playing';if(boss)$('bossBar').style.width=boss.hp/boss.maxHp*100+'%';}
function sprite(name,frame,x,y,height,dir=1,angle=0){const img=A[name];if(!img)return;const m=window.HL2_ASSETS?.[name]||actorMeta[name]||{cols:3,rows:1};const fw=img.width/m.cols,fh=img.height/m.rows,ratio=height/(m.bodyHeight||fh),anchor=m.anchor||[fw/2,fh];ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(dir,1);ctx.drawImage(img,(frame%m.cols)*fw,Math.floor(frame/m.cols)*fh,fw,fh,-anchor[0]*ratio,-anchor[1]*ratio,fw*ratio,fh*ratio);ctx.restore();}
function backdrop(theme,cx,cy,hero=false,heroGround=VH*.85){const t=THEMES[theme];let g=ctx.createLinearGradient(0,0,0,VH);g.addColorStop(0,t.sky[0]);g.addColorStop(1,t.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,VW,VH);const ground=hero?heroGround:540-cy;
 for(const [suffix,rate,hh,bottom] of [['far',.08,470,ground+45],['mid',.30,420,ground+45],['near',.62,300,ground+45]]){const img=A[t.id+'-'+suffix];if(!img)continue;const h=suffix==='far'?Math.max(hh,bottom):hh*(hero?1.18:1),w=h*img.width/img.height;const off=((cx*rate)%w+w)%w;for(let x=-off-w;x<VW+w;x+=w){if(suffix==='far'&&bottom-h>0)ctx.drawImage(img,0,0,img.width,2,x,0,w,bottom-h+1);ctx.drawImage(img,x,bottom-h,w,h);}}
 if(theme===4){ctx.globalAlpha=.15+.06*Math.sin(realTime);ctx.fillStyle='#66d9f3';ctx.fillRect(VW*.68,0,5,VH);ctx.globalAlpha=1;}
}
function platform(q,t){if(q.x+q.w<cam.x-10||q.x>cam.x+VW+10)return;const x=q.x-cam.x,y=q.y-cam.y;ctx.fillStyle=t.ground;ctx.fillRect(x,y,q.w,q.h);const img=A.terrain;if(img){ctx.save();ctx.beginPath();ctx.rect(x,y,q.w,q.h);ctx.clip();const th=q.ground?145:36,tw=th*img.width/img.height;for(let dx=x;dx<x+q.w;dx+=tw)ctx.drawImage(img,dx,y,tw,th);ctx.restore();}ctx.fillStyle=t.accent;ctx.globalAlpha=.8;ctx.fillRect(x,y,q.w,3);ctx.globalAlpha=1;if(!q.ground){ctx.fillStyle='#07182290';ctx.fillRect(x,y+q.h-7,q.w,7);}}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function shadow(x,y,w=35){ctx.fillStyle='#05141860';ctx.beginPath();ctx.ellipse(x,y,w,5,0,0,Math.PI*2);ctx.fill();}
function groundShadow(x,y,w){const floors=state.platforms.filter(q=>x>=q.x&&x<=q.x+q.w&&q.y>=y-4);if(!floors.length)return;const floor=Math.min(...floors.map(q=>q.y)),fade=clamp(1-(floor-y)/230,.15,1);ctx.globalAlpha=fade;shadow(x-cam.x,floor-cam.y,w*(.6+.4*fade));ctx.globalAlpha=1;}
function renderWorld(){const s=state,t=THEMES[s.chapter];backdrop(s.chapter,cam.x,cam.y);ctx.save();ctx.translate(shake?Math.sin(s.time*120)*shake:0,shake?Math.cos(s.time*92)*shake*.45:0);
 for(const gap of t.gaps){let x=gap[0]-cam.x,y=556-cam.y;if(x>VW||x+gap[1]-gap[0]<0)continue;ctx.fillStyle=s.chapter===1?'#648f66':'#0b2730';ctx.fillRect(x,y,gap[1]-gap[0],VH);if(s.chapter===1){ctx.strokeStyle='#b5c770';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<gap[1]-gap[0];i+=5){let py=y+Math.sin(i*.045+s.time*3)*3;i?ctx.lineTo(x+i,py):ctx.moveTo(x,py);}ctx.stroke();}}
 for(const q of s.platforms)platform(q,t);
 for(const c of s.checkpoints){const x=c.x-cam.x,y=540-cam.y;if(x< -80||x>VW+80)continue;ctx.fillStyle='#152c35';ctx.fillRect(x-5,y-68,10,68);ctx.fillStyle=c.on?'#8bdbe0':'#e9a85b';ctx.fillRect(x-17,y-87,34,27);ctx.fillStyle='#18333e';ctx.font='700 25px HEV';ctx.textAlign='center';ctx.fillText('λ',x,y-65);ctx.fillStyle=c.on?'#93e0dd':'#efad62';ctx.font='700 10px HEV';ctx.fillText(c.on?'SAVED':'CHECKPOINT',x,y+19);}
 const ex=s.exit-cam.x,ey=540-cam.y;if(ex<VW+90){ctx.fillStyle='#a5e4e1';ctx.globalAlpha=.1+Math.sin(s.time*3)*.035;ctx.fillRect(ex-35,ey-140,70,140);ctx.globalAlpha=1;ctx.strokeStyle='#a5e4e1';ctx.lineWidth=3;ctx.strokeRect(ex-29,ey-138,58,138);ctx.fillStyle='#bff9e6';ctx.font='700 35px HEV';ctx.textAlign='center';ctx.fillText('λ',ex,ey-86);ctx.font='700 12px HEV';ctx.fillText('EXIT →',ex,ey-153);}
 for(const c of s.caches)if(!c.taken){const x=c.x-cam.x,y=c.y-cam.y+Math.sin(s.time*3)*3;ctx.strokeStyle='#ffbd65';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,16,0,Math.PI*2);ctx.stroke();ctx.font='700 27px HEV';ctx.fillStyle='#ffbf6b';ctx.textAlign='center';ctx.fillText('λ',x,y+8);}
 for(const o of s.props){if(o.x<cam.x-120||o.x>cam.x+VW+120)continue;groundShadow(o.x,o.y,26);sprite(t.id+'-prop',o.state,o.x-cam.x,o.y-cam.y+2,[73,81,125,124,86][s.chapter],1,o.angle);if(o.held){ctx.strokeStyle='#9aeeff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(o.x-cam.x,o.y-cam.y-35,48+s.p.grav*20,0,Math.PI*2);ctx.stroke();}}
 for(const e of s.enemies){if(e.x<cam.x-180||e.x>cam.x+VW+200||e.hp<=0&&e.dead<=0)continue;const x=e.x-cam.x,y=e.y-cam.y;groundShadow(e.x,e.y,e.type==='strider'?80:e.w*.7);let f=e.hp<=0?5:e.hurt>0?4:e.attack>0||e.wind>0&&e.type==='strider'?3:Math.abs(e.vx)>5?1+Math.floor(e.walk/31)%2:0;if(e.type==='strider'&&e.hp>0)f=e.hurt>0?4:e.attack>0||e.wind>0?3:0;sprite(e.type,f,x,y+2,actorMeta[e.type].h,e.dir);if(e.wind>0){ctx.fillStyle='#ffc370';ctx.font='700 26px HEV';ctx.textAlign='center';ctx.fillText('!',x,y-e.h-25);if(e.type==='strider'){ctx.strokeStyle='#94edfa99';ctx.lineWidth=1;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(x-65,y-165);ctx.lineTo(s.p.x-cam.x,s.p.y-cam.y-40);ctx.stroke();ctx.setLineDash([]);}}if(e.hp>0&&e.hp<e.maxHp&&e.type!=='strider'){ctx.fillStyle='#0b1e24';ctx.fillRect(x-21,y-e.h-17,42,4);ctx.fillStyle='#e8a251';ctx.fillRect(x-21,y-e.h-17,42*e.hp/e.maxHp,4);}}
 const p=s.p,px=p.x-cam.x,py=p.y-cam.y;groundShadow(p.x,p.y,27);let frame=p.hp<=0?8:p.hurt>0?7:p.grav>.1?6:p.melee>0?5:p.shot>0?4:!p.grounded?3:Math.abs(p.vx)>15?1+Math.floor(p.walk/34)%2:0;ctx.save();if(p.invul>0&&Math.floor(s.time*15)%2===0){ctx.filter='brightness(1.5)';}sprite('gordon',frame,px,py+2,actorMeta.gordon.h,p.dir);ctx.restore();
 if(p.grav>.07&&!p.held){ctx.strokeStyle='#9af0ffa8';ctx.lineWidth=3;ctx.beginPath();ctx.arc(px+p.dir*57,py-52,35+(1-p.grav/.42)*140,p.dir>0?-1.0:Math.PI-1,p.dir>0?1:Math.PI+1);ctx.stroke();}
 if(p.melee>.09){ctx.strokeStyle='#ffdb9aaa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(px+p.dir*20,py-48,61,p.dir>0?-1.4:Math.PI-1.4,p.dir>0?.65:Math.PI+.65);ctx.stroke();}
 for(const pick of s.pickups)if(!pick.taken){const x=pick.x-cam.x,y=pick.y-cam.y;ctx.fillStyle='#12272e';ctx.fillRect(x-10,y-10,20,19);ctx.strokeStyle=pick.type==='health'?'#ecb670':'#9ef0f5';ctx.lineWidth=1;ctx.strokeRect(x-10,y-10,20,19);ctx.fillStyle=pick.type==='health'?'#ecb670':'#9ef0f5';ctx.font='700 19px HEV';ctx.textAlign='center';ctx.fillText(pick.type==='health'?'+':'ϟ',x,y+6);}
 for(const b of s.bullets){ctx.strokeStyle=b.color;ctx.lineWidth=b.r*1.4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(b.x-cam.x-b.vx*.014,b.y-cam.y-b.vy*.014);ctx.lineTo(b.x-cam.x,b.y-cam.y);ctx.stroke();if(b.r>7)circle(b.x-cam.x,b.y-cam.y,b.r,b.color);}ctx.lineCap='butt';
 for(const f of s.fx){ctx.globalAlpha=clamp(f.life/f.max,0,1);ctx.fillStyle=f.color;ctx.fillRect(f.x-cam.x,f.y-cam.y,f.size,f.size);}ctx.globalAlpha=1;for(const tx of s.texts){ctx.globalAlpha=clamp(tx.life*2,0,1);ctx.fillStyle=tx.color;ctx.font='700 16px HEV';ctx.textAlign='center';ctx.fillText(tx.text,tx.x-cam.x,tx.y-cam.y);}ctx.globalAlpha=1;
 ctx.restore();let shade=ctx.createLinearGradient(0,0,0,130);shade.addColorStop(0,'#071722e6');shade.addColorStop(1,'#07172200');ctx.fillStyle=shade;ctx.fillRect(0,0,VW,130);if(hitFlash>0){ctx.fillStyle=`rgba(218,80,30,${hitFlash*.55})`;ctx.fillRect(0,0,VW,VH);}
}
function renderHero(){const mx=realTime*10,portrait=W/H<.8,ground=portrait?VH*.64:VH*.91;backdrop(0,mx,0,true,ground);ctx.fillStyle='#203039';ctx.fillRect(0,ground,VW,VH-ground);if(A.terrain){const ht=180,wt=ht*A.terrain.width/A.terrain.height;for(let x=0;x<VW;x+=wt)ctx.drawImage(A.terrain,x,ground,wt,ht);}const heroX=portrait?VW*.74:VW*.72,heroY=ground+2,heroH=portrait?Math.min(445,VH*.445):Math.min(605,VH*.79);shadow(heroX,heroY,heroH*.19);if(!portrait)sprite('combine',0,VW*.90,ground+2,heroH*.71,-1);sprite('gordon',0,heroX,heroY,heroH,-1);if(!portrait){sprite('city-prop',0,VW*.55,ground+6,heroH*.28);}}
function render(){ctx.setTransform(DPR*scale,0,0,DPR*scale,0,0);ctx.imageSmoothingEnabled=true;const hero=phase==='main'||phase==='loading'||phase==='help'&&menuOrigin==='main'||!state;if(hero)renderHero();else renderWorld();}
const assetNames=['gordon','combine','zombie','headcrab','strider','terrain',...THEMES.flatMap(t=>[t.id+'-far',t.id+'-mid',t.id+'-near',t.id+'-prop'])];
function loadAssets(){if(loadingPromise)return loadingPromise;loadError=false;loadedPercent=0;assetDone=0;showMenu('loading');loadingPromise=(async()=>{const loads=assetNames.map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{A[name]=img;assetDone++;loadedPercent=Math.round(assetDone/(assetNames.length+1)*100);if(phase==='loading'||phase==='main')showMenu('loading');resolve();};img.onerror=()=>reject(new Error(name));img.src='./assets/'+name+'.png';}));loads.push(document.fonts.load('700 24px HEV').then(()=>{assetDone++;loadedPercent=Math.round(assetDone/(assetNames.length+1)*100);}));const results=await Promise.allSettled(loads);loadError=results.some(r=>r.status==='rejected');ready=!loadError;loadedPercent=ready?100:loadedPercent;if(phase==='loading'||phase==='main')showMenu('main');})();loadingPromise.finally(()=>loadingPromise=null);return loadingPromise;}
let last=0,acc=0;function loop(stamp){let dt=Math.min(.1,(stamp-last)/1000||0);last=stamp;realTime+=dt;if(transition){transition.t+=dt;if(transition.t>=.42&&!transition.done){transition.done=true;transition.fn();phase='transition';ROOT.classList.remove('playing');MENU.hidden=true;$('hud').hidden=true;$('touchControls').hidden=true;$('transition').classList.remove('black');}if(transition.t>=.84){transition=null;resume();}}else if(phase==='playing'){acc+=dt;let safety=0;while(acc>=1/120&&safety++<16){update(1/120);acc-=1/120;}}else acc=0;render();requestAnimationFrame(loop);}
showMenu('loading');loadAssets();requestAnimationFrame(loop);
})();
