(function(root){
'use strict';
const AREA=1120,LANES={min:24,max:224};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const THEMES=[
 {id:'citadel',name:'THE FALLEN CITADEL',label:'CITADEL',areas:['THE SIEGE GATE','ASHEN COURTYARD','THE BROKEN RAMPART'],boss:'HELL KNIGHT · GATEKEEPER',bossHP:420,bossPattern:['melee','melee','stomp'],prop:'MUNITIONS CHEST',propHeight:80,background:'#24291d',brief:'Break the siege. Fight through the citadel.',encounters:[['imp','imp','cultist','imp'],['imp','cultist','imp','knight','imp'],['imp','cultist','imp','cultist']]},
 {id:'marsh',name:'THE FORSAKEN MARSH',label:'MARSH',areas:['DROWNED PASSAGE','THE SOUL GARDEN','BONE ALTAR'],boss:'HELL KNIGHT · SOUL WARDEN',bossHP:530,bossPattern:['melee','volley','stomp','volley'],volleyCount:3,volleySpread:.27,volleySpeed:320,volleyDamage:13,volleyColor:'#b7dc73',prop:'SOUL URN',propHeight:90,background:'#122e27',brief:'Cross the marsh. Silence the soul altar.',encounters:[['imp','imp','cultist','imp','imp'],['imp','cultist','imp','knight','imp','imp'],['imp','cultist','imp','cultist','imp']]},
 {id:'forge',name:'THE INFERNAL FORGE',label:'FORGE',areas:['IRON APPROACH','THE FURNACE','HEART OF THE FORGE'],boss:'HELL KNIGHT · IRON TYRANT',bossHP:700,bossPattern:['melee','stomp'],prop:'FURNACE CYLINDER',propHeight:106,background:'#321d16',brief:'Break the Iron Tyrant. Open the road beyond the forge.',encounters:[['imp','imp','cultist','imp','imp','knight'],['imp','cultist','imp','knight','imp','imp','knight'],['imp','cultist','imp','cultist','imp','knight']]},
 {id:'necropolis',name:'THE FROZEN NECROPOLIS',label:'NECROPOLIS',areas:['THE FROSTBOUND ROAD','CRYPT OF KINGS','THE GLACIAL THRONE'],boss:'HELL KNIGHT · FROST REAVER',bossHP:790,bossPattern:['volley','melee','stomp','volley'],volleyCount:5,volleySpread:.18,volleySpeed:310,volleyDamage:14,volleyColor:'#92deef',prop:'FROZEN OBELISK',propHeight:112,background:'#142335',brief:'Cross the frozen tombs. Shatter the Frost Reaver.',encounters:[['imp','cultist','imp','knight','cultist','imp'],['knight','imp','cultist','imp','knight','cultist','imp'],['cultist','imp','knight','cultist','imp','knight']]},
 {id:'abyss',name:'THE ABYSSAL CATHEDRAL',label:'ABYSS',areas:['THE VOID BRIDGE','SANCTUM OF CHAINS','THE ECLIPSE ALTAR'],boss:'HELL KNIGHT · ABYSS LORD',bossHP:940,bossPattern:['melee','volley','stomp','volley','stomp'],volleyCount:3,volleySpread:.34,volleySpeed:370,volleyDamage:16,volleyColor:'#d4a2ff',stompReach:196,stompLane:94,prop:'RITUAL CAGE',propHeight:98,background:'#24152f',brief:'Enter the cathedral. Seal the abyss and end the invasion.',victory:'The Abyss Lord has fallen. The gate is sealed. All five chapters are complete.',encounters:[['knight','imp','cultist','imp','knight','cultist','imp'],['cultist','knight','imp','cultist','knight','imp','imp'],['knight','cultist','imp','knight','cultist','imp','imp']]}
];
const ENEMIES={imp:{hp:62,speed:115,reach:88,damage:9,wind:.65,recovery:1.1,height:145},cultist:{hp:76,speed:68,reach:430,damage:12,wind:.95,recovery:1.7,height:167},knight:{hp:145,speed:65,reach:122,damage:17,wind:.92,recovery:1.45,height:208}};
class Engine{
 constructor(seed=74219){this.seed=seed;this.onEvent=()=>{};this.hasRun=false;this.reset();this.state='menu';}
 rand(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296;}
 emit(type,data={}){this.onEvent({type,...data});}
 reset(){this.chapter=0;this.area=0;this.score=0;this.kills=0;this.time=0;this.combo=0;this.comboTimer=0;this.maxCombo=0;this.parries=0;this.nextId=1;this.clear=false;this.projectiles=[];this.props=[];this.pickups=[];this.enemies=[];this.saw=null;this.inputX=0;this.inputY=0;this.player={x:210,y:125,hp:100,maxHP:100,shells:12,guard:100,face:1,action:'idle',timer:0,duration:0,hitDone:false,invuln:0,dashCD:0,fireCD:0,sawCD:0,parryWindow:0,guardBreak:0,walk:0,moving:false,comboStep:0,chainWindow:0};this.spawnArea();this.checkpoint=this.snapshot();}
 snapshot(){const p=this.player;return{chapter:this.chapter,score:this.score,kills:this.kills,hp:p.hp,shells:p.shells,maxCombo:this.maxCombo,parries:this.parries};}
 start(saved){this.reset();this.hasRun=true;if(saved&&Number.isInteger(saved.chapter)&&saved.chapter>=0&&saved.chapter<THEMES.length){this.chapter=saved.chapter;this.score=Math.max(0,Number(saved.score)||0);this.kills=Math.max(0,Number(saved.kills)||0);this.maxCombo=Math.max(0,Number(saved.maxCombo)||0);this.parries=Math.max(0,Number(saved.parries)||0);const p=this.player;p.hp=clamp(Number(saved.hp)||100,25,100);p.shells=clamp(Number(saved.shells)||0,0,24);this.enemies=[];this.props=[];this.spawnArea();}this.checkpoint=this.snapshot();this.state='play';this.emit('checkpoint',{save:this.checkpoint});this.emit('notice',{text:THEMES[this.chapter].brief,duration:3});}
 retry(){this.start({...this.checkpoint});}
 pause(){if(this.state==='play'){this.state='pause';this.emit('pause');}}
 resume(){if(this.state==='pause')this.state='play';}
 returnToMenu(){this.state='menu';}
 enterChapter(){if(this.chapter>=THEMES.length-1)return;this.chapter++;this.area=0;this.clear=false;this.enemies=[];this.props=[];this.pickups=[];this.projectiles=[];this.saw=null;const p=this.player;Object.assign(p,{x:210,y:125,hp:Math.min(100,p.hp+40),shells:Math.min(24,p.shells+10),guard:100,action:'idle',timer:0,invuln:1,dashCD:0,fireCD:0,sawCD:0,parryWindow:0,guardBreak:0,comboStep:0});this.combo=0;this.comboTimer=0;this.spawnArea();this.checkpoint=this.snapshot();this.state='play';this.emit('checkpoint',{save:this.checkpoint});}
 spawnArea(){const off=this.area*AREA,theme=THEMES[this.chapter];this.clear=false;const roster=theme.encounters[this.area];roster.forEach((kind,i)=>this.spawnEnemy(kind,off+515+(i%3)*155+Math.floor(i/3)*65,47+(i%3)*70+(Math.floor(i/3)%2)*12));if(this.area===theme.areas.length-1)this.spawnEnemy('knight',off+1000,125,true);[[370,206],[665,35],[995,202]].forEach(([x,y],i)=>this.props.push({id:this.nextId++,x:x+off,y,hp:60,maxHP:60,state:0,theme:theme.id,drop:i===1?'ammo':'health',awarded:false,flash:0}));this.emit('area',{chapter:this.chapter,area:this.area});}
 spawnEnemy(type,x,y,boss=false){const s=ENEMIES[type],hp=boss?THEMES[this.chapter].bossHP:Math.round(s.hp*(1+this.chapter*.07));this.enemies.push({id:this.nextId++,type,x,y:clamp(y,LANES.min,LANES.max),hp,maxHP:hp,boss,face:-1,action:'idle',timer:0,duration:0,cd:.7+this.rand()*.8,walk:0,moving:false,hitDone:false,attackCount:0,height:s.height*(boss?1.18:1),stomp:false});}
 startAction(name,duration){const p=this.player;p.action=name;p.timer=duration;p.duration=duration;p.hitDone=false;p.moving=false;}
 action(name){if(this.state!=='play')return false;const p=this.player;
  if(name==='guard'){if(this.saw||p.guardBreak>0||p.guard<8||!['idle','walk','guard'].includes(p.action))return false;if(p.action!=='guard'){p.parryWindow=.22;this.emit('sound',{sound:'guard'});}p.action='guard';p.timer=0;return true;}
  if(name==='dash'){if(p.dashCD>0||p.action==='dash'||p.action==='hurt')return false;p.dashCD=1.15;p.invuln=Math.max(p.invuln,.38);this.startAction('dash',.32);let dx=this.inputX||p.face,dy=this.inputY||0,l=Math.hypot(dx,dy)||1;p.dashDX=dx/l;p.dashDY=dy/l;this.emit('sound',{sound:'dash'});return true;}
  if(!['idle','walk','guard'].includes(p.action))return false;
  if(name==='melee'){p.comboStep=p.chainWindow>0?p.comboStep%3+1:1;p.chainWindow=.85;this.startAction('melee',p.comboStep===3?.48:.32);this.emit('sound',{sound:'swing'});return true;}
  if(name==='throw'){if(p.sawCD>0||this.saw)return false;p.sawCD=3;this.startAction('throw',.36);this.saw={x:p.x+p.face*48,y:p.y,face:p.face,travel:0,returning:false,hits:[],angle:0};this.emit('sound',{sound:'saw'});return true;}
  if(name==='fire'){if(p.fireCD>0)return false;if(p.shells<=0){this.emit('notice',{text:'NO SHELLS · MELEE KILLS RESTORE AMMO',duration:1.2});return false;}p.shells--;p.fireCD=.72;this.startAction('fire',.28);this.fireShotgun();return true;}return false;
 }
 fireShotgun(){const p=this.player;let nearest=430;for(const e of this.enemies){const dx=(e.x-p.x)*p.face;if(e.hp>0&&dx>0&&dx<440&&Math.abs(e.y-p.y)<42+dx*.035){this.hitEnemy(e,dx<180?65:dx<300?44:28,'fire',p.face);nearest=Math.min(nearest,dx);}}for(const prop of this.props){const dx=(prop.x-p.x)*p.face;if(prop.hp>0&&dx>0&&dx<370&&Math.abs(prop.y-p.y)<49)this.hitProp(prop,38);}this.emit('tracer',{x:p.x+p.face*60,y:p.y,x2:p.x+p.face*nearest,y2:p.y});this.emit('sound',{sound:'shot'});this.emit('shake',{strength:4});}
 hitProp(prop,damage){if(prop.hp<=0)return;prop.hp=Math.max(0,prop.hp-damage);prop.state=prop.hp<=0?2:prop.hp<45?1:0;prop.flash=.1;this.emit('impact',{x:prop.x,y:prop.y,height:45,color:'#dca660',count:8});if(prop.hp<=0&&!prop.awarded){prop.awarded=true;this.score+=80;this.pickups.push({id:this.nextId++,x:prop.x,y:prop.y,type:prop.drop,life:60});this.emit('sound',{sound:'break'});}}
 hitEnemy(e,damage,kind,face){if(e.hp<=0)return;e.hp=Math.max(0,e.hp-damage);const knock=kind==='finisher'?70:kind==='saw'?24:kind==='parry'?35:kind==='fire'?30:16;e.x=clamp(e.x+face*knock,this.area*AREA+38,(this.area+1)*AREA-55);if(kind==='parry'||!e.boss){e.action='hurt';e.timer=kind==='parry'?1.0:e.boss?.16:.3;e.cd=Math.max(e.cd,e.timer+.25);}this.combo++;this.comboTimer=2.6;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=Math.round(damage*(1+Math.min(3,Math.floor(this.combo/8))*.25));this.emit('impact',{x:e.x,y:e.y,height:e.height*.62,color:kind==='parry'?'#a6eeba':'#ecb660',count:kind==='finisher'?14:8});this.emit('damageText',{x:e.x,y:e.y,amount:damage,color:kind==='parry'?'#bdecca':'#ffe2a8'});this.emit('sound',{sound:'hit'});if(e.hp===0){this.kills++;this.score+=e.boss?1600:160;e.action='dead';e.timer=1.1;e.moving=false;this.player.shells=Math.min(24,this.player.shells+1);this.player.guard=clamp(this.player.guard+10,0,100);if(kind==='melee'||kind==='finisher')this.player.hp=Math.min(100,this.player.hp+4);if(e.boss){this.emit('notice',{text:THEMES[this.chapter].boss+' DEFEATED',duration:2});this.emit('sound',{sound:'bossdown'});}else if(this.rand()<.17)this.pickups.push({id:this.nextId++,x:e.x,y:e.y,type:'health',life:45});this.emit('kill',{boss:e.boss});}}
 hurtPlayer(amount,attacker,unblockable=false){const p=this.player;if(p.hp<=0||p.invuln>0)return false;const front=attacker&&(attacker.x-p.x)*p.face>=-12;
  if(p.action==='guard'&&front&&!unblockable&&!this.saw){if(p.parryWindow>0){p.parryWindow=0;p.invuln=.15;p.guard=clamp(p.guard+25,0,100);p.shells=Math.min(24,p.shells+1);p.hp=Math.min(100,p.hp+3);this.parries++;this.score+=150;if(attacker.type)this.hitEnemy(attacker,32,'parry',p.face);this.emit('parry',{x:p.x,y:p.y});this.emit('notice',{text:'PERFECT PARRY · +1 SHELL',duration:1});this.emit('sound',{sound:'parry'});return 'parry';}p.guard=Math.max(0,p.guard-amount*2.5);this.emit('sound',{sound:'block'});this.emit('impact',{x:p.x+p.face*37,y:p.y,height:90,color:'#e7ca82',count:9});if(p.guard<=0){p.guardBreak=1.5;this.startAction('hurt',.48);this.emit('notice',{text:'GUARD BROKEN · DASH TO RECOVER',duration:1.3});}return 'block';}
  p.hp=Math.max(0,p.hp-amount);p.invuln=.75;this.startAction('hurt',.24);this.combo=0;this.comboTimer=0;if(attacker)p.x=clamp(p.x+(p.x<attacker.x?-24:24),Math.max(40,this.area*AREA-130),(this.area+1)*AREA-80);this.emit('hurt',{amount});this.emit('sound',{sound:'hurt'});if(p.hp===0){p.action='dead';p.timer=1;this.state='dying';this.deathTimer=1.2;}return true;
 }
 resolvePlayerHit(){const p=this.player,finish=p.comboStep===3,reach=finish?151:132,damage=finish?46:p.comboStep===2?31:27;let hit=false;for(const e of this.enemies){const dx=(e.x-p.x)*p.face;if(e.hp>0&&dx>-25&&dx<reach&&Math.abs(e.y-p.y)<(finish?56:43)){this.hitEnemy(e,damage,finish?'finisher':'melee',p.face);hit=true;}}for(const prop of this.props){const dx=(prop.x-p.x)*p.face;if(prop.hp>0&&dx>-20&&dx<reach&&Math.abs(prop.y-p.y)<51){this.hitProp(prop,finish?50:31);hit=true;}}if(hit)this.emit('shake',{strength:finish?6:3});if(finish&&hit)this.emit('notice',{text:'SHIELD BREAKER',duration:.65});}
 updateSaw(dt){const s=this.saw;if(!s)return;const p=this.player;s.angle+=dt*24;if(!s.returning){s.x+=s.face*570*dt;s.travel+=570*dt;if(s.travel>=480){s.returning=true;s.hits=[];}}else{const dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy);if(d<31){this.saw=null;this.emit('sound',{sound:'catch'});return;}s.x+=dx/d*650*dt;s.y+=dy/d*650*dt;}
  for(const e of this.enemies)if(e.hp>0&&!s.hits.includes(e.id)&&Math.abs(e.x-s.x)<52&&Math.abs(e.y-s.y)<43){s.hits.push(e.id);this.hitEnemy(e,s.returning?28:42,'saw',s.face);}for(const prop of this.props)if(prop.hp>0&&!s.hits.includes(prop.id)&&Math.abs(prop.x-s.x)<48&&Math.abs(prop.y-s.y)<42){s.hits.push(prop.id);this.hitProp(prop,48);}
 }
 step(dt,input={}){dt=clamp(dt,0,.05);if(this.state==='dying'){this.deathTimer-=dt;if(this.deathTimer<=0){this.state='dead';this.emit('defeat');}return;}if(this.state!=='play')return;this.time+=dt;const p=this.player;this.inputX=clamp(input.x||0,-1,1);this.inputY=clamp(input.y||0,-1,1);if(this.inputX&&['idle','walk','guard'].includes(p.action))p.face=this.inputX>0?1:-1;['invuln','dashCD','fireCD','sawCD','chainWindow','parryWindow','guardBreak'].forEach(k=>p[k]=Math.max(0,p[k]-dt));this.comboTimer-=dt;if(this.comboTimer<=0)this.combo=0;
  if(p.action==='guard'&&!input.guard)p.action='idle';if(input.guard&&p.action!=='guard')this.action('guard');if(input.actions)for(const a of input.actions)this.action(a);p.guard=clamp(p.guard+dt*(p.action==='guard'?2:18),0,100);
  const ox=p.x,oy=p.y;p.moving=false;if(p.timer>0){p.timer-=dt;const elapsed=p.duration-p.timer;if(p.action==='melee'&&!p.hitDone&&elapsed>(p.comboStep===3?.17:.11)){p.hitDone=true;this.resolvePlayerHit();}if(p.action==='dash'){p.x+=p.dashDX*555*dt;p.y+=p.dashDY*265*dt;}if(p.timer<=0)p.action='idle';}
  if(['idle','walk','guard'].includes(p.action)){const len=Math.max(1,Math.hypot(this.inputX,this.inputY)),speed=p.action==='guard'?.37:1;p.x+=this.inputX/len*220*dt*speed;p.y+=this.inputY/len*143*dt*speed;}p.y=clamp(p.y,LANES.min,LANES.max);p.x=clamp(p.x,Math.max(40,this.area*AREA-130),(this.area+1)*AREA-(this.clear?22:80));const dist=Math.hypot(p.x-ox,p.y-oy);if(dist>.02){p.walk+=dist;p.moving=true;if(p.action==='idle')p.action='walk';}else if(p.action==='walk')p.action='idle';
  this.updateSaw(dt);for(const e of this.enemies)this.updateEnemy(e,dt);for(const prop of this.props)prop.flash=Math.max(0,prop.flash-dt);
  for(const b of this.projectiles){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.friendly){for(const e of this.enemies)if(e.hp>0&&Math.abs(b.x-e.x)<34&&Math.abs(b.y-e.y)<27){this.hitEnemy(e,65,'parry',Math.sign(b.vx));b.life=0;break;}}else if(Math.abs(b.x-p.x)<28&&Math.abs(b.y-p.y)<25&&b.life>0){const result=this.hurtPlayer(b.damage,{x:p.x-Math.sign(b.vx)*100},false);if(result==='parry'){b.friendly=true;b.vx=-b.vx*1.5;b.vy=-b.vy;b.life=1.8;b.x=p.x+p.face*40;}else b.life=0;}}this.projectiles=this.projectiles.filter(b=>b.life>0);
  for(const i of this.pickups){i.life-=dt;if(Math.abs(p.x-i.x)<48&&Math.abs(p.y-i.y)<39){if(i.type==='health'){p.hp=Math.min(100,p.hp+25);this.emit('float',{x:i.x,y:i.y,text:'+25 HEALTH',color:'#b8eaa0'});}else{p.shells=Math.min(24,p.shells+5);this.emit('float',{x:i.x,y:i.y,text:'+5 SHELLS',color:'#e4c58b'});}i.life=0;this.emit('sound',{sound:'pickup'});}}this.pickups=this.pickups.filter(i=>i.life>0);
  if(p.hp<=0)return;if(!this.clear&&this.enemies.every(e=>e.hp<=0)){this.clear=true;this.projectiles=[];this.score+=450;this.emit('notice',{text:'AREA CLEARED · MOVE RIGHT',duration:2.2});this.emit('sound',{sound:'clear'});}if(this.clear&&p.x>(this.area+1)*AREA-60){if(this.area<THEMES[this.chapter].areas.length-1){this.area++;this.enemies=[];this.props=this.props.filter(o=>o.x>=this.area*AREA-160);this.pickups=this.pickups.filter(o=>o.x>=this.area*AREA-160);this.spawnArea();this.emit('notice',{text:THEMES[this.chapter].areas[this.area],duration:2});}else{this.state=this.chapter===THEMES.length-1?'win':'chapter';this.saw=null;this.score+=1500;this.emit(this.state==='win'?'victory':'chapterComplete');}}
 }
 fireVolley(e){const theme=THEMES[this.chapter],target=e.attackTarget,angle=Math.atan2(target.y-e.y,target.x-e.x),count=theme.volleyCount||3,speed=theme.volleySpeed||320;for(let i=0;i<count;i++){const a=angle+(i-(count-1)/2)*(theme.volleySpread||.27);this.projectiles.push({x:e.x+e.face*50,y:e.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:2.8,damage:theme.volleyDamage||13,color:theme.volleyColor||'#b7dc73',friendly:false});}}
 updateEnemy(e,dt){if(e.hp<=0){e.timer=Math.max(0,e.timer-dt);return;}const p=this.player,s=ENEMIES[e.type],theme=THEMES[this.chapter];e.cd=Math.max(0,e.cd-dt);e.moving=false;const dx=p.x-e.x,dy=p.y-e.y;if(!['windup','attack'].includes(e.action))e.face=dx>=0?1:-1;
  if(e.action==='hurt'){e.timer-=dt;if(e.timer<=0)e.action='idle';return;}
  if(e.action==='windup'){e.timer-=dt;if(e.timer<=0){e.action='attack';e.timer=.32;e.hitDone=false;this.emit('sound',{sound:e.type==='cultist'||e.attackKind==='volley'?'enemyShot':'enemySwing'});}return;}
  if(e.action==='attack'){e.timer-=dt;if(!e.hitDone){e.hitDone=true;if(e.type==='cultist'){const target=e.attackTarget,vx=target.x-e.x,vy=target.y-e.y,len=Math.hypot(vx,vy)||1;this.projectiles.push({x:e.x+e.face*40,y:e.y,vx:vx/len*340,vy:vy/len*340,life:2.8,damage:s.damage,friendly:false});}else if(e.boss&&e.attackKind==='volley'){this.fireVolley(e);}else if(e.stomp){this.emit('stomp',{x:e.x,y:e.y});if(Math.abs(dx)<(theme.stompReach||184)&&Math.abs(dy)<(theme.stompLane||88))this.hurtPlayer(s.damage+7,e,true);}else if(dx*e.face>-20&&Math.abs(dx)<s.reach+(e.boss?30:16)&&Math.abs(dy)<(e.boss?55:43))this.hurtPlayer(s.damage+(e.boss?3:0),e);}if(e.timer<=0){e.action='idle';e.cd=s.recovery+(e.boss&&this.chapter>=3?.2:0)+this.rand()*.5;}return;}
  if(p.hp<=0)return;const nextKind=e.boss?theme.bossPattern[e.attackCount%theme.bossPattern.length]:e.type==='cultist'?'shot':'melee',reach=e.boss?(nextKind==='volley'?390:150):s.reach;if(e.cd<=0&&Math.abs(dx)<reach&&Math.abs(dy)<(nextKind==='volley'?70:e.type==='cultist'?42:35)){const busy=this.enemies.filter(o=>o.hp>0&&['windup','attack'].includes(o.action)).length;if(busy<2){e.attackCount++;e.attackKind=nextKind;e.stomp=nextKind==='stomp';e.action='windup';e.duration=e.stomp||nextKind==='volley'?1.05:s.wind;e.timer=e.duration;e.attackTarget={x:p.x,y:p.y};return;}}
  let vx=0,vy=0,preferred=e.type==='cultist'?280:e.type==='knight'?98:67;if(Math.abs(dy)>12)vy=Math.sign(dy)*s.speed*.63;if(Math.abs(dx)>preferred)vx=Math.sign(dx)*s.speed;else if(e.type==='cultist'&&Math.abs(dx)<170)vx=-Math.sign(dx)*s.speed*.7;if(e.cd>.25&&Math.abs(dx)<preferred+12)vx=0;for(const other of this.enemies){if(other===e||other.hp<=0)continue;const ex=e.x-other.x,ey=e.y-other.y;if(Math.abs(ex)<47&&Math.abs(ey)<31){vx+=Math.sign(ex||e.id-other.id)*24;vy+=Math.sign(ey||e.id-other.id)*23;}}const ox=e.x,oy=e.y;e.x=clamp(e.x+vx*dt,this.area*AREA+40,(this.area+1)*AREA-60);e.y=clamp(e.y+vy*dt,LANES.min,LANES.max);const moved=Math.hypot(e.x-ox,e.y-oy);if(moved>.05){e.walk+=moved;e.moving=true;e.action='walk';}else e.action='idle';
 }
 get remaining(){return this.enemies.filter(e=>e.hp>0).length;}
 get boss(){return this.enemies.find(e=>e.boss&&e.hp>0);}
}
const api={Engine,THEMES,ENEMIES,AREA,LANES,clamp};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.DoomCore=api;
})(typeof window!=='undefined'?window:this);
