(function(){
'use strict';
const Core=window.DoomCore;
const {Engine,THEMES,AREA,LANES,clamp}=Core;
const LANE_DEPTH=.72,ACTOR_MARGIN=128,CHAPTER_TOTAL=String(THEMES.length).padStart(2,'0');
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false});
const game=new Engine(),catalog=window.DOOM_ASSETS,images={},keys=new Set(),pressed=new Set();
let width=1,height=1,dpr=1,zoom=1,camera=0,horizon=0,groundBase=0,laneScale=LANE_DEPTH,lastTime=0,loadDone=false,overlayType='',helpBack='main',noticeTime=0,shake=0,flash=0,transition=false;
let touchMode=matchMedia('(pointer:coarse)').matches,stickPointer=null,stickX=0,stickY=0,stickStart={x:0,y:0},effects=[],floats=[],tracers=[],uiClock=0,cinematic=true,heroTime=0;
let agentInput=null;
let audioContext=null,master=null,muted=false;
try{muted=localStorage.getItem('doom-dark-ages-beat-em-up-muted')==='1';}catch{}
const SAVE_KEY='doom-dark-ages-beat-em-up-campaign-v1';
const moreURL='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
document.querySelectorAll('.more-games').forEach(a=>a.href=moreURL);

function initAudio(){if(audioContext){if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});return;}try{audioContext=new(window.AudioContext||window.webkitAudioContext)();master=audioContext.createGain();master.gain.value=muted?0:.29;master.connect(audioContext.destination);}catch{}}
function tone(f,d,v=.35,type='triangle',end){if(!audioContext||muted)return;const t=audioContext.currentTime,o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d+.01);}
function noise(d,v=.4,cutoff=1400){if(!audioContext||muted)return;const n=Math.floor(audioContext.sampleRate*d),buffer=audioContext.createBuffer(1,n,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const src=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),g=audioContext.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;g.gain.value=v;src.connect(filter);filter.connect(g);g.connect(master);src.start();}
function sound(name){switch(name){case'shot':noise(.14,.55,2500);tone(95,.12,.3,'sawtooth',35);break;case'enemyShot':tone(160,.25,.2,'sawtooth',65);noise(.1,.14,1800);break;case'hit':noise(.09,.3,1000);tone(105,.075,.3,'triangle',35);break;case'swing':noise(.15,.16,2600);break;case'enemySwing':noise(.2,.13,900);break;case'saw':tone(125,.55,.17,'sawtooth',75);noise(.45,.19,1300);break;case'dash':noise(.16,.11,500);break;case'hurt':noise(.12,.28,480);tone(62,.2,.35,'sawtooth',27);break;case'guard':case'catch':noise(.055,.16,3000);tone(400,.1,.1,'triangle',220);break;case'block':noise(.11,.29,3500);tone(230,.18,.22,'triangle',140);break;case'parry':tone(700,.2,.2,'triangle',1100);noise(.14,.25,2800);break;case'pickup':tone(550,.1,.17);setTimeout(()=>tone(820,.14,.13),65);break;case'break':noise(.25,.3,700);break;case'clear':tone(260,.2,.15);setTimeout(()=>tone(390,.25,.15),100);break;case'bossdown':tone(75,.8,.3,'sawtooth',25);noise(.5,.2,600);break;}}
function updateSound(){const b=$('sound-button');b.classList.toggle('muted',muted);b.setAttribute('aria-label',muted?'Unmute sound':'Mute sound');b.title=muted?'Sound off (M)':'Sound on (M)';if(master)master.gain.value=muted?0:.29;}
function toggleSound(){muted=!muted;try{localStorage.setItem('doom-dark-ages-beat-em-up-muted',muted?'1':'0');}catch{}initAudio();updateSound();}
function fullscreen(){if(document.fullscreenElement){document.exitFullscreen?.().catch(()=>{});}else document.documentElement.requestFullscreen?.().catch(()=>showNotice('FULLSCREEN IS NOT AVAILABLE HERE',2));}
function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY));return s&&Number.isInteger(s.chapter)&&s.chapter>=0&&s.chapter<THEMES.length?s:null;}catch{return null;}}
function writeSave(save){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{}}
function deleteSave(){try{localStorage.removeItem(SAVE_KEY);}catch{}}
function showNotice(text,duration=2){$('notice').textContent=text;noticeTime=duration;$('notice').classList.add('show');}
function clearInput(){keys.clear();pressed.clear();stickX=stickY=0;stickPointer=null;$('stick-knob').style.transform='';document.querySelectorAll('.touch-action').forEach(b=>b.classList.remove('pressed'));}
function showMain(){game.returnToMenu();cinematic=true;heroTime=0;overlayType='';$('overlay').hidden=true;$('main-menu').hidden=false;$('menu-brand').hidden=false;$('hud').hidden=true;$('pause-button').hidden=true;$('keyboard-guide').hidden=true;$('touch-controls').hidden=true;$('notice').classList.remove('show');clearInput();const save=readSave();$('continue-button').hidden=!save||!loadDone;$('continue-button').textContent=save?'CONTINUE · CHAPTER '+String(save.chapter+1).padStart(2,'0'):'';const t=THEMES[game.chapter];document.querySelector('.chapter-stamp').innerHTML='<span>CHAPTER '+String(game.chapter+1).padStart(2,'0')+' / '+CHAPTER_TOTAL+'</span><strong>'+t.name+'</strong>';}
function showPlay(){cinematic=false;overlayType='';$('overlay').hidden=true;$('main-menu').hidden=true;$('menu-brand').hidden=true;$('hud').hidden=false;$('pause-button').hidden=false;$('keyboard-guide').hidden=touchMode;$('touch-controls').hidden=!touchMode;canvas.focus({preventScroll:true});updateHUD();}
function begin(saved){initAudio();cinematic=false;clearInput();effects=[];floats=[];tracers=[];game.start(saved);camera=0;showPlay();}
function makeButton(label,handler,primary=false){const b=document.createElement('button');b.className=primary?'button primary':'text-button';b.textContent=label;b.onclick=handler;return b;}
function makeMore(){const a=document.createElement('a');a.className='button more-games';a.href=moreURL;a.target='_blank';a.rel='noopener noreferrer';a.textContent='MORE GAMES ↗';return a;}
function panel(type,kicker,title,body,actions){overlayType=type;clearInput();$('main-menu').hidden=true;$('overlay').hidden=false;$('menu-brand').hidden=false;$('hud').hidden=true;$('pause-button').hidden=true;$('keyboard-guide').hidden=true;$('touch-controls').hidden=true;$('notice').classList.remove('show');$('panel-kicker').textContent=kicker;$('panel-title').textContent=title;$('panel-content').innerHTML=body;const primary=actions.filter(a=>a.classList.contains('primary')),secondary=actions.filter(a=>!a.classList.contains('primary')),items=[...primary,makeMore()];if(secondary.length){const links=document.createElement('div');links.className='panel-secondary';links.append(...secondary);items.push(links);}$('panel-actions').replaceChildren(...items);}
function pauseGame(){if(game.state!=='play'||transition)return;game.pause();const t=THEMES[game.chapter];panel('pause','CHAPTER '+String(game.chapter+1).padStart(2,'0')+' / '+CHAPTER_TOTAL,'THE WAR CAN WAIT','<p>'+t.name+' · '+t.areas[game.area]+'</p>',[makeButton('RESUME',()=>{game.resume();showPlay();},true),makeButton('CONTROLS',()=>showHelp('pause')),makeButton('MAIN MENU',showMain)]);}
function showHelp(back){helpBack=back;const controls=[['WASD','MOVE','Arrow keys also work. Change lanes to evade.'],['J','FLAIL COMBO','Two flail strikes, then a heavy shield bash.'],['K','GUARD / PARRY','Hold to block. Tap just before impact to parry.'],['E','SHIELD SAW','Hits on the way out and back. Guard returns with it.'],['L','SHOTGUN','Strongest up close. Every kill restores one shell.'],['SPACE','DASH','Evade red ground slams. Brief invulnerability.']];panel('help','THE SLAYER’S ARSENAL','STAND. PARRY. SHATTER.','<div class="controls-grid">'+controls.map(([key,title,desc])=>'<div class="control-row"><kbd>'+key+'</kbd><div><strong>'+title+'</strong><small>'+desc+'</small></div></div>').join('')+'</div><p class="help-tip">Green attacks can be parried. Red slams must be dodged. Melee kills restore health. Break supplies, clear every demon, then move right. Touch: use the stick and action buttons.</p>',[makeButton('BACK',()=>{if(helpBack==='pause'){game.state='play';pauseGame();}else showMain();},true)]);}
function chapterDots(){return '<div class="chapters-mini">'+THEMES.map((t,i)=>'<span class="'+(i<game.chapter?'done':i===game.chapter?'active':'')+'">'+String(i+1).padStart(2,'0')+' '+t.label+'</span>').join('')+'</div>';}
function outcome(victory){const t=THEMES[game.chapter];panel(victory?'victory':'chapter',victory?'CAMPAIGN COMPLETE':'CHAPTER '+String(game.chapter+1).padStart(2,'0')+' COMPLETE',victory?'HELL HAS MET ITS MATCH.':'THE WAY IS OPEN.','<p>'+(victory?t.victory:t.boss+' has fallen. Continue to '+THEMES[game.chapter+1].name+'.')+'</p>'+chapterDots()+'<div class="stats"><div><span>SCORE</span><strong>'+String(game.score).padStart(6,'0')+'</strong></div><div><span>DEMONS SLAIN</span><strong>'+game.kills+'</strong></div><div><span>BEST COMBO</span><strong>'+game.maxCombo+'</strong></div></div>'+(!victory?'<p>Next chapter: +40 health, +10 shells, and full guard.</p>':''),[makeButton(victory?'PLAY AGAIN':'NEXT CHAPTER',()=>victory?begin():nextChapter(),true),makeButton('MAIN MENU',showMain)]);if(victory)deleteSave();}
function defeat(){panel('defeat','THE SLAYER HAS FALLEN','RISE AGAIN.','<p>Return to the opening checkpoint of '+THEMES[game.chapter].name+'.</p><p>Your chapter-entry health, shells, and score will be restored.</p>',[makeButton('RETRY CHAPTER',()=>{cinematic=false;effects=[];tracers=[];floats=[];game.retry();camera=0;showPlay();},true),makeButton('MAIN MENU',showMain)]);}
function nextChapter(){if(transition||game.state!=='chapter'||game.chapter>=THEMES.length-1)return;transition=true;clearInput();$('overlay').hidden=true;$('menu-brand').hidden=true;const next=THEMES[game.chapter+1];$('transition-kicker').textContent='CHAPTER '+String(game.chapter+2).padStart(2,'0')+' / '+CHAPTER_TOTAL;$('transition-name').textContent=next.name;$('chapter-transition').classList.add('visible');setTimeout(()=>{game.enterChapter();game.state='transition';camera=0;effects=[];tracers=[];floats=[];},640);setTimeout(()=>{$('chapter-transition').classList.remove('visible');},1680);setTimeout(()=>{transition=false;game.state='play';showPlay();showNotice(next.brief+'\n+40 HEALTH · +10 SHELLS',3.7);},2250);}
game.onEvent=e=>{
 switch(e.type){
  case'checkpoint':writeSave(e.save);break;
  case'notice':showNotice(e.text,e.duration);break;
  case'sound':sound(e.sound);break;
  case'shake':shake=Math.max(shake,e.strength);break;
  case'hurt':flash=.26;shake=5;break;
  case'parry':shake=5;for(let i=0;i<22;i++)effects.push({x:e.x,y:e.y,z:85,vx:(Math.random()-.5)*340,vy:(Math.random()-.5)*100,vz:80+Math.random()*110,life:.3+Math.random()*.25,color:'#bfedbb',size:2+Math.random()*3});break;
  case'stomp':shake=7;for(let i=0;i<25;i++)effects.push({x:e.x,y:e.y,z:4,vx:(Math.random()-.5)*440,vy:(Math.random()-.5)*160,vz:50+Math.random()*60,life:.5,color:'#e79b57',size:3});break;
  case'impact':for(let i=0;i<e.count;i++)effects.push({x:e.x,y:e.y,z:e.height,vx:(Math.random()-.5)*190,vy:(Math.random()-.5)*65,vz:90+Math.random()*150,life:.28+Math.random()*.35,color:e.color,size:1+Math.random()*3});break;
  case'damageText':floats.push({x:e.x,y:e.y,z:150,text:String(e.amount),life:.65,color:e.color});break;
  case'float':floats.push({x:e.x,y:e.y,z:105,text:e.text,life:1.1,color:e.color});break;
  case'tracer':tracers.push({...e,life:.065});break;
  case'chapterComplete':outcome(false);break;
  case'victory':outcome(true);break;
  case'defeat':defeat();break;
 }
};
function resize(){width=canvas.clientWidth;height=canvas.clientHeight;touchMode=matchMedia('(pointer:coarse)').matches||width<650||(width<950&&height<500);if(game.state==='play'){$('keyboard-guide').hidden=touchMode;$('touch-controls').hidden=!touchMode;}dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.imageSmoothingEnabled=false;}
window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',()=>{resize();const full=!!document.fullscreenElement;$('fullscreen-button').setAttribute('aria-label',full?'Exit fullscreen':'Enter fullscreen');$('fullscreen-button').title=full?'Exit fullscreen (F)':'Enter fullscreen (F)';});if(window.visualViewport)visualViewport.addEventListener('resize',resize);
function frameFor(actor){if(actor===game.player){if(actor.action==='dead')return 11;if(actor.action==='hurt')return 10;if(actor.action==='dash')return 9;if(actor.action==='fire')return 8;if(actor.action==='throw')return 7;if(actor.action==='guard')return 6;if(actor.action==='melee')return 2+actor.comboStep;}else{if(actor.hp<=0)return 5;if(actor.action==='hurt')return 4;if(actor.action==='attack')return 3;}return actor.moving?1+Math.floor(actor.walk/(actor.type==='imp'?39:49))%2:0;}
function sprite(key,frame,x,y,bodyHeight,face=1){const meta=catalog.actors[key]||catalog.props[key],im=images[key];if(!meta||!im)return;const cw=meta.cellWidth,ch=meta.cellHeight,info=meta.frames?.[frame],anchor=info?.anchor||meta.anchor||[cw/2,ch*.94],bounds=meta.frames?.[0]?.bounds||[0,0,cw,ch],scale=bodyHeight/(meta.bodyHeight||bounds[3]-bounds[1]);ctx.save();ctx.globalAlpha=1;ctx.translate(Math.round(x),Math.round(y));ctx.scale(face,1);ctx.drawImage(im,frame%meta.cols*cw,Math.floor(frame/meta.cols)*ch,cw,ch,Math.round(-anchor[0]*scale),Math.round(-anchor[1]*scale),Math.round(cw*scale),Math.round(ch*scale));ctx.restore();}
function worldPoint(x,y){return {x:(x-camera)*zoom,y:groundBase+(y-125)*zoom*laneScale};}
function layer(theme,name,factor,bottom,bodyHeight,viewCamera=camera){
 const im=images[theme+'-'+name];if(!im)return;
 if(name==='far'){
  // One overscanned backdrop spans the camera's complete travel: no mirrored skylines or sky seams.
  const travel=(THEMES.find(t=>t.id===theme).areas.length*AREA+ACTOR_MARGIN*2)*zoom*factor;
  const pad=96*zoom,drawW=Math.max(width+travel+pad*2,bodyHeight*im.width/im.height);
  const drawH=drawW*im.height/im.width,scroll=clamp(viewCamera*zoom*factor+pad,0,drawW-width);
  ctx.drawImage(im,Math.floor(-scroll),Math.floor(Math.min(0,bottom-drawH*.85)),Math.ceil(drawW)+1,Math.ceil(drawH)+1);
  return;
 }
 const meta=catalog.themes[theme][name],scale=bodyHeight/(meta.silhouetteHeight||im.height);
 const drawW=im.width*scale,drawH=im.height*scale,top=bottom-(meta.groundY||im.height)*scale;
 const scroll=viewCamera*zoom*factor,first=Math.floor(scroll/drawW);
 // Repeat the native panorama without reflecting architecture or fitting it to the viewport.
 for(let i=first;i*drawW-scroll<width;i++){
  const x=i*drawW-scroll;
  ctx.drawImage(im,Math.floor(x),Math.floor(top),Math.ceil(drawW)+1,Math.ceil(drawH)+1);
 }
}
function scenery(chapter=game.chapter,viewCamera=camera,parallaxOffset=0){
 const theme=THEMES[chapter].id,sceneryCamera=viewCamera+parallaxOffset;
 ctx.fillStyle=THEMES[chapter].background;ctx.fillRect(0,0,width,height);
 const floorTop=horizon;
 layer(theme,'far',.08,horizon+24*zoom,Math.max(horizon+24*zoom,320*zoom),sceneryCamera);
 const ground=images[theme+'-floor'];
 if(ground){
  const h=Math.max(height-floorTop,260*zoom),w=h*ground.width/ground.height;
  const off=((viewCamera*zoom)%w+w)%w;
  for(let x=-off;x<width;x+=w)ctx.drawImage(ground,Math.floor(x),Math.floor(floorTop),Math.ceil(w)+1,Math.ceil(h)+1);
 }
 // World-space heights preserve landmark-to-player scale, including narrow portrait views.
 layer(theme,'mid',.30,horizon+20*zoom,410*zoom,sceneryCamera);
 layer(theme,'near',.62,horizon+40*zoom,360*zoom,sceneryCamera);
 const shade=ctx.createLinearGradient(0,floorTop,0,height);
 shade.addColorStop(0,'#08101810');shade.addColorStop(1,'#05091155');
 ctx.fillStyle=shade;ctx.fillRect(0,floorTop,width,height-floorTop);
}
function shadow(point,w){ctx.fillStyle='#02070980';ctx.beginPath();ctx.ellipse(point.x,point.y-1,w*zoom,11*zoom,0,0,Math.PI*2);ctx.fill();}
function label(text,x,y,color,size=12){ctx.font=size+'px Oxanium,Arial';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#09131ee8';ctx.strokeText(text,x,y);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function drawActor(actor){const point=worldPoint(actor.x,actor.y),isPlayer=actor===game.player,key=isPlayer?'slayer':actor.type,h=isPlayer?182:actor.height;if(point.x<-270||point.x>width+270)return;shadow(point,isPlayer?43:actor.type==='knight'?56:36);if(!isPlayer&&actor.hp>0&&actor.action==='windup'){const progress=1-actor.timer/actor.duration;ctx.strokeStyle=actor.stomp?'#ed7655':'#b9e897';ctx.lineWidth=2*zoom;ctx.beginPath();ctx.ellipse(point.x,point.y,(actor.stomp?(THEMES[game.chapter].stompReach||184):57)*zoom,(actor.stomp?(THEMES[game.chapter].stompLane||88)*laneScale:17)*zoom,0,-Math.PI/2,-Math.PI/2+Math.PI*2*progress);ctx.stroke();label(actor.stomp?'EVADE':actor.attackKind==='volley'?'VOLLEY':'!',point.x,point.y-h*zoom-11*zoom,actor.stomp?'#ffb088':'#d9efab',(actor.stomp||actor.attackKind==='volley'?12:23)*zoom);if(actor.type==='cultist'||actor.attackKind==='volley'){ctx.setLineDash([6*zoom,9*zoom]);const target=worldPoint(actor.attackTarget.x,actor.attackTarget.y);ctx.strokeStyle='#afdb7970';ctx.beginPath();ctx.moveTo(point.x,point.y-60*zoom);ctx.lineTo(target.x,target.y-60*zoom);ctx.stroke();ctx.setLineDash([]);}}sprite(key,frameFor(actor),point.x,point.y,h*zoom,actor.face);if(!isPlayer&&actor.hp>0&&actor.hp<actor.maxHP&&!actor.boss){ctx.fillStyle='#09110cce';ctx.fillRect(point.x-24*zoom,point.y-h*zoom-10*zoom,48*zoom,4*zoom);ctx.fillStyle='#c5874d';ctx.fillRect(point.x-24*zoom,point.y-h*zoom-10*zoom,48*zoom*actor.hp/actor.maxHP,4*zoom);}if(isPlayer&&actor.invuln>0&&game.state==='play'){ctx.strokeStyle='#dad39699';ctx.lineWidth=2*zoom;ctx.beginPath();ctx.ellipse(point.x,point.y,44*zoom,10*zoom,0,0,Math.PI*2);ctx.stroke();}}
function drawProp(prop){const point=worldPoint(prop.x,prop.y);if(point.x<-180||point.x>width+180)return;shadow(point,37);sprite(prop.theme+'-prop',prop.state,point.x,point.y,(THEMES.find(t=>t.id===prop.theme)?.propHeight||80)*zoom);}
function drawPickup(item){const p=worldPoint(item.x,item.y),bounce=Math.sin(game.time*4+item.id)*4*zoom;p.y-=39*zoom+bounce;ctx.fillStyle=item.type==='health'?'#132e26e8':'#102b36e8';ctx.strokeStyle=item.type==='health'?'#89c3a0':'#75bed4';ctx.lineWidth=1;const boxW=(item.type==='health'?52:62)*zoom;ctx.fillRect(p.x-boxW/2,p.y-12*zoom,boxW,24*zoom);ctx.strokeRect(p.x-boxW/2,p.y-12*zoom,boxW,24*zoom);label(item.type==='health'?'+ HP':'AMMO',p.x,p.y+3*zoom,item.type==='health'?'#b3e4c0':'#a9e0f0',10*zoom);}
function layoutBattlefield(dt){const portrait=height>width;horizon=height*(portrait?.51:.52);const back=horizon+(portrait?105:55)*zoom;const front=Math.min(height-(touchMode?(portrait?165:105):55),height*.87);laneScale=clamp((front-back)/((LANES.max-LANES.min)*zoom),.3,LANE_DEPTH);groundBase=back+(125-LANES.min)*laneScale*zoom;const view=width/zoom,target=clamp(game.player.x-view*.4,-ACTOR_MARGIN,Math.max(-ACTOR_MARGIN,THEMES[game.chapter].areas.length*AREA-view+ACTOR_MARGIN));if(game.state==='play')camera+=(target-camera)*Math.min(1,dt*6);else if(!game.hasRun)camera=target;const margin=Math.min(ACTOR_MARGIN,view*.28);camera=clamp(camera,game.player.x-view+margin,game.player.x-margin);}
function renderHero(dt){
 heroTime+=dt;laneScale=LANE_DEPTH;horizon=height*.55;groundBase=height*(height>width?.86:.85);
 const heroCamera=400-width*(height>width?.70:.69)/zoom;
 scenery(0,heroCamera,Math.sin(heroTime*.12)*58);
 const actors=[{key:'citadel-prop',x:665,y:35,height:80,shadow:37},{key:'knight',x:510,y:102,height:208,shadow:56,face:-1},{key:'slayer',x:400,y:125,height:182,shadow:43},{key:'citadel-prop',x:995,y:202,height:80,shadow:37}];
 for(const actor of actors){const point={x:(actor.x-heroCamera)*zoom,y:groundBase+(actor.y-125)*zoom*laneScale};shadow(point,actor.shadow);sprite(actor.key,0,point.x,point.y,actor.height*zoom,actor.face||1);}
}
function render(dt){ctx.setTransform(dpr,0,0,dpr,0,0);
 zoom=cinematic?(height>width?Math.min(height/530,1.4):Math.min(height/430,2.25)):Math.max(.43,Math.min(height/(touchMode?650:610),width/640,1.65));
 if(cinematic){renderHero(dt);return;}
 layoutBattlefield(dt);
 const shakeX=game.state==='play'?(Math.random()-.5)*shake:0,shakeY=game.state==='play'?(Math.random()-.5)*shake*.45:0;ctx.translate(shakeX,shakeY);scenery();
 const drawables=[...game.props.map(p=>({y:p.y,draw:()=>drawProp(p)})),...game.enemies.map(e=>({y:e.y,draw:()=>drawActor(e)})),{y:game.player.y,draw:()=>drawActor(game.player)}];
 drawables.sort((a,b)=>a.y-b.y);for(const o of drawables)o.draw();for(const item of game.pickups)drawPickup(item);
 for(const b of game.projectiles){const point=worldPoint(b.x,b.y);ctx.fillStyle=b.friendly?'#eafbb3':b.color||'#b7dc73';ctx.shadowColor=b.friendly?'#eafbb3':b.color||'#bde980';ctx.shadowBlur=10;ctx.beginPath();ctx.arc(point.x,point.y-75*zoom,6*zoom,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=b.friendly?'#e6fca3':(b.color||'#91be66')+'70';ctx.lineWidth=4*zoom;ctx.beginPath();ctx.moveTo(point.x-Math.sign(b.vx)*18*zoom,point.y-75*zoom);ctx.lineTo(point.x,point.y-75*zoom);ctx.stroke();}
 if(game.saw&&images.shield){const point=worldPoint(game.saw.x,game.saw.y);ctx.save();ctx.translate(point.x,point.y-90*zoom);ctx.rotate(game.saw.angle);ctx.drawImage(images.shield,-38*zoom,-38*zoom,76*zoom,76*zoom);ctx.restore();}
 for(const t of tracers){const a=worldPoint(t.x,t.y),b=worldPoint(t.x2,t.y2);ctx.strokeStyle='#f3d8a0c9';ctx.lineWidth=1.3*zoom;ctx.beginPath();ctx.moveTo(a.x,a.y-97*zoom);ctx.lineTo(b.x,b.y-90*zoom);ctx.stroke();}
 for(const e of effects){const p=worldPoint(e.x,e.y);ctx.fillStyle=e.color;ctx.fillRect(p.x,p.y-e.z*zoom,e.size*zoom,e.size*zoom);}
 for(const f of floats){const p=worldPoint(f.x,f.y);label(f.text,p.x,p.y-f.z*zoom,f.color,Math.max(9,13*zoom));}
 if(game.clear&&game.state==='play'){const gate=worldPoint((game.area+1)*AREA-105,135);const gx=clamp(gate.x,70,width-65);const gy=groundBase-80*zoom;label(game.area===THEMES[game.chapter].areas.length-1?'CONTINUE':'MOVE RIGHT',gx,gy-34*zoom,'#d9ecbd',Math.max(10,13*zoom));ctx.strokeStyle='#b2d68d';ctx.lineWidth=3*zoom;const shift=Math.sin(game.time*5)*5*zoom;ctx.beginPath();ctx.moveTo(gx-17*zoom+shift,gy-13*zoom);ctx.lineTo(gx+shift,gy);ctx.lineTo(gx-17*zoom+shift,gy+13*zoom);ctx.moveTo(gx+3*zoom+shift,gy-13*zoom);ctx.lineTo(gx+20*zoom+shift,gy);ctx.lineTo(gx+3*zoom+shift,gy+13*zoom);ctx.stroke();}
 ctx.setTransform(dpr,0,0,dpr,0,0);
 if(flash>0){ctx.fillStyle='rgba(168,26,25,'+(flash*.65)+')';ctx.fillRect(0,0,width,height);}
}
function updateEffects(dt){shake=Math.max(0,shake-dt*24);flash=Math.max(0,flash-dt);for(const e of effects){e.x+=e.vx*dt;e.y+=e.vy*dt;e.z+=e.vz*dt;e.vz-=750*dt;e.life-=dt;}effects=effects.filter(e=>e.life>0&&e.z>0);for(const f of floats){f.life-=dt;f.z+=35*dt;}floats=floats.filter(f=>f.life>0);tracers.forEach(t=>t.life-=dt);tracers=tracers.filter(t=>t.life>0);}
function updateHUD(){const p=game.player,t=THEMES[game.chapter];$('health-value').textContent=Math.ceil(p.hp)+' / 100';$('health-fill').style.width=p.hp+'%';$('health-fill').style.background=p.hp<30?'#d46b42':'#9eac68';$('guard-fill').style.width=p.guard+'%';$('guard-value').textContent=p.guardBreak>0?'!':Math.round(p.guard);$('ammo-value').textContent=String(p.shells).padStart(2,'0');$('saw-value').textContent=game.saw?'RETURNING':p.sawCD>0?p.sawCD.toFixed(1)+'s':'READY';$('chapter-label').textContent='CH. '+String(game.chapter+1).padStart(2,'0')+' / '+CHAPTER_TOTAL+' · AREA '+String(game.area+1).padStart(2,'0')+' / '+String(t.areas.length).padStart(2,'0');$('area-label').textContent=t.areas[game.area];$('objective-label').textContent=game.clear?'AREA CLEARED · MOVE RIGHT':game.remaining+' DEMONS REMAINING';$('objective-label').style.color=game.clear?'#cee2a2':'';$('score-value').textContent=String(game.score).padStart(6,'0');$('combo-value').textContent=game.combo>=3?game.combo+' HIT COMBO':'';const boss=game.boss;$('boss-hud').hidden=!boss;if(boss){$('boss-label').textContent=t.boss;$('boss-fill').style.width=(boss.hp/boss.maxHP*100)+'%';}}
function tick(now){const dt=Math.min(.04,(now-lastTime)/1000||.016);lastTime=now;const active=game.state==='play';if(active){const actions=[];if(keys.has('KeyJ')||pressed.has('melee'))actions.push('melee');if(keys.has('KeyE')||pressed.has('throw'))actions.push('throw');if(keys.has('KeyL')||pressed.has('fire'))actions.push('fire');if(agentInput)actions.push(...agentInput.actions);game.step(dt,{x:(agentInput?.x||0)+stickX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y:(agentInput?.y||0)+stickY+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),guard:keys.has('KeyK')||pressed.has('guard')||agentInput?.guard,actions});updateEffects(dt);if(noticeTime>0){noticeTime-=dt;if(noticeTime<=0)$('notice').classList.remove('show');}uiClock+=dt;if(uiClock>.07){uiClock=0;updateHUD();}}else if(game.state==='dying'){game.step(dt,{});updateEffects(dt);}render(dt);requestAnimationFrame(tick);}
function keydown(e){if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.repeat&&['Space','Escape','KeyP','KeyM','KeyF'].includes(e.code))return;if(e.code==='KeyM'){toggleSound();return;}if(e.code==='KeyF'){fullscreen();return;}if(e.code==='Escape'||e.code==='KeyP'){if(game.state==='play')pauseGame();else if(overlayType==='pause'){game.resume();showPlay();}else if(overlayType==='help'){if(helpBack==='pause'){game.state='play';pauseGame();}else showMain();}return;}if(game.state!=='play')return;keys.add(e.code);if(!e.repeat){if(e.code==='KeyJ')game.action('melee');if(e.code==='KeyK')game.action('guard');if(e.code==='KeyE')game.action('throw');if(e.code==='KeyL')game.action('fire');if(e.code==='Space')game.action('dash');}}
document.addEventListener('keydown',keydown);document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pauseGame();}});
$('start-button').onclick=()=>{if(loadDone)begin();else loadAssets();};$('continue-button').onclick=()=>begin(readSave());$('help-button').onclick=()=>showHelp('main');$('pause-button').onclick=pauseGame;$('sound-button').onclick=toggleSound;$('fullscreen-button').onclick=fullscreen;
const stick=$('stick');stick.addEventListener('pointerdown',e=>{if(game.state!=='play')return;touchMode=true;initAudio();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);const r=stick.getBoundingClientRect();stickStart={x:r.left+r.width/2,y:r.top+r.height/2};moveStick(e);});function moveStick(e){if(e.pointerId!==stickPointer)return;const dx=e.clientX-stickStart.x,dy=e.clientY-stickStart.y,len=Math.hypot(dx,dy),limit=35,ratio=Math.min(1,limit/(len||1));stickX=clamp(dx/limit,-1,1);stickY=clamp(dy/limit,-1,1);if(len<7)stickX=stickY=0;$('stick-knob').style.transform='translate('+dx*ratio+'px,'+dy*ratio+'px)';}stick.addEventListener('pointermove',moveStick);function endStick(e){if(e.pointerId===stickPointer){stickPointer=null;stickX=stickY=0;$('stick-knob').style.transform='';}}stick.addEventListener('pointerup',endStick);stick.addEventListener('pointercancel',endStick);stick.addEventListener('lostpointercapture',endStick);
document.querySelectorAll('.touch-action').forEach(b=>{const action=b.dataset.action;b.addEventListener('pointerdown',e=>{e.preventDefault();if(game.state!=='play')return;initAudio();b.setPointerCapture(e.pointerId);b.classList.add('pressed');game.action(action);if(action!=='dash')pressed.add(action);});const end=()=>{pressed.delete(action);b.classList.remove('pressed');};b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);b.addEventListener('lostpointercapture',end);});
document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!touchMode){touchMode=true;if(game.state==='play')showPlay();}},{passive:true});
async function loadAssets(){const entries=[];for(const [key,meta]of Object.entries(catalog.actors))entries.push([key,meta.file||key+'.png']);for(const [key,meta]of Object.entries(catalog.props))entries.push([key,meta.file||key+'.png']);for(const[id,layers]of Object.entries(catalog.themes))for(const name of ['far','mid','near','floor'])entries.push([id+'-'+name,layers[name]?.file||id+'-'+name+'.png']);entries.push(['shield','shield.png']);let complete=0,failed=[];const total=entries.length+1;loadDone=false;$('start-button').disabled=true;$('loading-error').hidden=true;const progress=()=>{const pct=Math.round(complete/total*100);$('start-button').firstElementChild.textContent='LOADING '+pct+'%';$('start-button').style.setProperty('--load',pct+'%');};progress();await Promise.all(entries.map(([key,file])=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images[key]=im;complete++;progress();resolve();};im.onerror=()=>{failed.push(file);complete++;progress();resolve();};im.src='assets/'+file+'?v=20260922-new-backgrounds';})));try{await document.fonts.load('16px Oxanium');}catch{}complete++;progress();if(!entries.length)failed.push('artwork');if(failed.length){$('start-button').disabled=false;$('start-button').firstElementChild.textContent='RETRY LOADING';$('loading-error').textContent='Some artwork could not load. Check your connection and try again.';$('loading-error').hidden=false;return;}loadDone=true;$('start-button').disabled=false;$('start-button').firstElementChild.textContent='START GAME';const save=readSave();$('continue-button').hidden=!save;$('continue-button').textContent=save?'CONTINUE · CHAPTER '+String(save.chapter+1).padStart(2,'0'):'';}
function battleStatus(){const p=game.player;return{state:game.state,chapter:game.chapter+1,chapterName:THEMES[game.chapter].name,area:game.area+1,objective:game.clear?'Move right to the exit':'Defeat all demons',health:p.hp,shells:p.shells,guard:Math.round(p.guard),shieldCooldown:Math.round(p.sawCD*10)/10,shieldInFlight:!!game.saw,score:game.score,remaining:game.remaining,parries:game.parries,player:{x:Math.round(p.x),lane:Math.round(p.y),facing:p.face,action:p.action},enemies:game.enemies.filter(e=>e.hp>0).map(e=>({type:e.type,boss:e.boss,health:e.hp,relativeX:Math.round(e.x-p.x),relativeLane:Math.round(e.y-p.y),action:e.action,unblockable:e.stomp&&e.action==='windup'})),supplies:game.pickups.map(i=>({type:i.type,relativeX:Math.round(i.x-p.x),relativeLane:Math.round(i.y-p.y)}))};}
if(document.modelContext?.registerTool){const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}};register({name:'read_battle_status',description:'Read player health, shield, nearby demons, and chapter progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>battleStatus()});register({name:'campaign_menu',description:'Use an available campaign menu: start, continue, pause, resume, retry after defeat, or advance after clearing a chapter.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','continue','pause','resume','retry','next_chapter','main_menu']}},required:['action'],additionalProperties:false},execute:async({action})=>{if(!loadDone)throw Error('Artwork is still loading.');if(!['start','continue','pause','resume','retry','next_chapter','main_menu'].includes(action))throw Error('Unknown menu action.');if(action==='start'){if(game.state==='play')throw Error('Return to the menu first.');begin();}if(action==='continue'){if(game.state==='play')throw Error('Return to the menu first.');const saved=readSave();if(!saved)throw Error('No saved checkpoint.');begin(saved);}if(action==='pause')pauseGame();if(action==='resume'){if(game.state!=='pause')throw Error('The game is not paused.');game.resume();showPlay();}if(action==='retry'){if(game.state!=='dead')throw Error('Retry is available after defeat.');game.retry();camera=0;showPlay();}if(action==='next_chapter'){if(game.state!=='chapter')throw Error('Finish the current chapter first.');nextChapter();await new Promise(r=>setTimeout(r,2300));}if(action==='main_menu')showMain();return battleStatus();}});register({name:'play_controls',description:'Hold ordinary game controls for 50–1000 ms. Movement x/y is -1 to 1. Flail, shotgun, shield throw, guard, and dash use their normal rules.',inputSchema:{type:'object',properties:{x:{type:'number',minimum:-1,maximum:1},y:{type:'number',minimum:-1,maximum:1},milliseconds:{type:'integer',minimum:50,maximum:1000},attack:{type:'string',enum:['none','melee','throw','fire']},guard:{type:'boolean'},dash:{type:'boolean'}},required:['milliseconds'],additionalProperties:false},execute:async({x=0,y=0,milliseconds,attack='none',guard=false,dash=false})=>{if(!Number.isFinite(x)||!Number.isFinite(y)||Math.abs(x)>1||Math.abs(y)>1||!Number.isInteger(milliseconds)||milliseconds<50||milliseconds>1000||!['none','melee','throw','fire'].includes(attack)||typeof guard!=='boolean'||typeof dash!=='boolean')throw Error('Invalid controls.');if(game.state!=='play')throw Error('Start or resume first.');if(agentInput)throw Error('Another input is active.');initAudio();agentInput={x,y,guard,actions:attack==='none'?[]:[attack]};game.inputX=x;game.inputY=y;if(guard)game.action('guard');if(dash)game.action('dash');try{await new Promise(r=>setTimeout(r,milliseconds));}finally{agentInput=null;}updateHUD();return battleStatus();}});}
updateSound();resize();loadAssets();requestAnimationFrame(tick);
})();
