export class GameAudio{
 constructor(muted=false){this.muted=muted;this.ready=false;}
 async unlock(){
  try{
   if(!this.context){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.context=new A();const c=this.context;this.master=c.createGain();this.master.gain.value=this.muted?0:.58;this.master.connect(c.destination);this.engineGain=c.createGain();this.engineGain.gain.value=0;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=380;this.filter=filter;filter.connect(this.engineGain);this.engineGain.connect(this.master);this.engine=[0,1].map(i=>{const o=c.createOscillator();o.type=i?'triangle':'sawtooth';o.frequency.value=i?64:32;o.detune.value=i?7:0;o.connect(filter);o.start();return o;});const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),a=buffer.getChannelData(0);let prev=0;for(let i=0;i<a.length;i++){prev=(prev+(Math.random()*2-1)*.045)/1.035;a[i]=prev*3.5;}this.noiseBuffer=buffer;const source=c.createBufferSource();source.buffer=buffer;source.loop=true;const windFilter=c.createBiquadFilter();windFilter.type='highpass';windFilter.frequency.value=450;this.windGain=c.createGain();this.windGain.gain.value=0;source.connect(windFilter);windFilter.connect(this.windGain);this.windGain.connect(this.master);source.start();this.ready=true;}
   if(this.context.state==='suspended')await this.context.resume();
  }catch{this.ready=false;}
 }
 setMuted(value){this.muted=value;if(this.ready)this.master.gain.setTargetAtTime(value?0:.58,this.context.currentTime,.025);}
 tone(freq,duration=.15,type='sine',volume=.14,delay=0,endFreq){if(!this.ready||this.muted)return;const c=this.context,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(duration=.2,volume=.3){if(!this.ready||this.muted)return;const c=this.context,t=c.currentTime,s=c.createBufferSource(),g=c.createGain();s.buffer=this.noiseBuffer;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);s.connect(g);g.connect(this.master);s.start();s.stop(t+duration);s.onended=()=>{s.disconnect();g.disconnect();};}
 play(type){if(type==='level-up'){[523,659,784,1047].forEach((n,i)=>this.tone(n,.28,'triangle',.1,i*.10));}if(type==='near-miss'){this.tone(620,.11,'sine',.13,0,1200);this.noise(.09,.09);}if(type==='needle'){this.tone(780,.15,'triangle',.14);this.tone(1175,.25,'triangle',.12,.07);}if(type==='pickup'){[660,880,1320].forEach((n,i)=>this.tone(n,.22,'sine',.1,i*.055));}if(type==='boost'){this.tone(140,.65,'sawtooth',.07,0,480);this.noise(.6,.15);}if(type==='crash'){this.noise(.75,.95);this.tone(100,.6,'triangle',.3,0,25);}if(type==='shield-hit'){this.noise(.25,.35);this.tone(1300,.35,'sine',.15,0,250);}if(type==='start'){this.tone(440,.13,'triangle',.1);this.tone(880,.25,'triangle',.1,.14);}}
 update(model){if(!this.ready)return;const t=this.context.currentTime,on=model.mode==='playing';this.engineGain.gain.setTargetAtTime(on?.042:0,t,.09);this.windGain.gain.setTargetAtTime(on?.035+model.speed/220*.075:0,t,.12);const f=30+model.speed*.24+Math.sin(model.elapsed*5)*1.5;this.engine[0].frequency.setTargetAtTime(f,t,.07);this.engine[1].frequency.setTargetAtTime(f*2,t,.07);this.filter.frequency.setTargetAtTime(model.boost>0?1000:520,t,.15);}
}
