(function(){
'use strict';
const Core=window.GearsCore;
const {Engine,THEMES,AREA,LANES,clamp}=Core;
const NEAR_BASE=55,FLOOR_INSET=20,LANE_DEPTH=.69,ACTOR_MARGIN=140;
const GROUND_FRONT=[.84,.62,.56,.84,.74];
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false});
const game=new Engine(),catalog=window.GEARS_ASSETS,images={},keys=new Set(),pressed=new Set();
let width=1,height=1,dpr=1,zoom=1,camera=0,horizon=0,groundBase=0,laneScale=LANE_DEPTH,lastTime=0,loadDone=false,overlayType='',helpBack='main',noticeTime=0,shake=0,flash=0,transition=false;
let touchMode=matchMedia('(pointer:coarse)').matches,stickPointer=null,stickX=0,stickY=0,stickStart={x:0,y:0},effects=[],floats=[],tracers=[],uiClock=0,cinematic=true;
let agentInput=null;
let audioContext=null,master=null,muted=false;
try{muted=localStorage.getItem('gears-beat-em-up-muted')==='1';}catch{}
const SAVE_KEY='gears-beat-em-up-campaign-v1';
const moreURL='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
document.querySelectorAll('.more-games').forEach(a=>a.href=moreURL);

function initAudio(){if(audioContext){if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});return;}try{audioContext=new(window.AudioContext||window.webkitAudioContext)();master=audioContext.createGain();master.gain.value=muted?0:.29;master.connect(audioContext.destination);}catch{}}
function tone(f,d,v=.35,type='triangle',end){if(!audioContext||muted)return;const t=audioContext.currentTime,o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d+.01);}
function noise(d,v=.4,cutoff=1400){if(!audioContext||muted)return;const n=Math.floor(audioContext.sampleRate*d),buffer=audioContext.createBuffer(1,n,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const src=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),g=audioContext.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;g.gain.value=v;src.connect(filter);filter.connect(g);g.connect(master);src.start();}
function sound(name){switch(name){case'shot':noise(.095,.43,2600);tone(110,.08,.3,'sawtooth',45);break;case'enemyShot':noise(.16,.37,1200);tone(72,.14,.25,'triangle',31);break;case'hit':noise(.08,.26,880);tone(100,.065,.28,'triangle',40);break;case'swing':noise(.12,.11,1900);break;case'enemySwing':noise(.17,.13,900);break;case'saw':noise(.58,.28,1700);tone(105,.65,.18,'sawtooth',69);break;case'sawhit':noise(.19,.4,950);break;case'roll':noise(.16,.11,420);break;case'hurt':noise(.1,.28,520);tone(62,.17,.4,'sawtooth',30);break;case'reload':tone(600,.04,.15,'square');break;case'rack':noise(.06,.2,2400);break;case'perfect':tone(600,.15,.18);setTimeout(()=>tone(900,.18,.16),70);break;case'pickup':tone(550,.1,.18);setTimeout(()=>tone(800,.14,.14),65);break;case'break':noise(.23,.34,650);break;case'clear':tone(260,.2,.15);setTimeout(()=>tone(390,.25,.15),100);break;case'bossdown':tone(85,.8,.3,'sawtooth',30);noise(.5,.18,650);break;}}
function updateSound(){const b=$('sound-button');b.classList.toggle('muted',muted);b.setAttribute('aria-label',muted?'Unmute sound':'Mute sound');b.title=muted?'Sound off (M)':'Sound on (M)';if(master)master.gain.value=muted?0:.29;}
function toggleSound(){muted=!muted;try{localStorage.setItem('gears-beat-em-up-muted',muted?'1':'0');}catch{}initAudio();updateSound();}
function fullscreen(){if(document.fullscreenElement){document.exitFullscreen?.().catch(()=>{});}else document.documentElement.requestFullscreen?.().catch(()=>showNotice('FULLSCREEN IS NOT AVAILABLE HERE',2));}
function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY));return s&&Number.isInteger(s.chapter)&&s.chapter>=0&&s.chapter<5?s:null;}catch{return null;}}
function writeSave(save){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{}}
function deleteSave(){try{localStorage.removeItem(SAVE_KEY);}catch{}}
function showNotice(text,duration=2){$('notice').textContent=text;noticeTime=duration;$('notice').classList.add('show');}
function clearInput(){keys.clear();pressed.clear();stickX=stickY=0;stickPointer=null;$('stick-knob').style.transform='';document.querySelectorAll('.touch-action').forEach(b=>b.classList.remove('pressed'));}
function showMain(){game.returnToMenu();overlayType='';$('overlay').hidden=true;$('main-menu').hidden=false;$('menu-brand').hidden=false;$('hud').hidden=true;$('pause-button').hidden=true;$('keyboard-guide').hidden=true;$('touch-controls').hidden=true;$('notice').classList.remove('show');clearInput();const save=readSave();$('continue-button').hidden=!save||!loadDone;$('continue-button').textContent=save?'CONTINUE · CHAPTER '+String(save.chapter+1).padStart(2,'0'):'';const t=THEMES[game.chapter];document.querySelector('.chapter-stamp').innerHTML='<span>CHAPTER '+String(game.chapter+1).padStart(2,'0')+' / 05</span><strong>'+t.name+'</strong>';}
function showPlay(){overlayType='';$('overlay').hidden=true;$('main-menu').hidden=true;$('menu-brand').hidden=true;$('hud').hidden=false;$('pause-button').hidden=false;$('keyboard-guide').hidden=touchMode;$('touch-controls').hidden=!touchMode;canvas.focus({preventScroll:true});updateHUD();}
function begin(saved){initAudio();cinematic=false;clearInput();effects=[];floats=[];tracers=[];game.start(saved);camera=0;showPlay();}
function makeButton(label,handler,primary=false){const b=document.createElement('button');b.className='button'+(primary?' primary':'');b.textContent=label;b.onclick=handler;return b;}
function makeMore(){const a=document.createElement('a');a.className='button more-games';a.href=moreURL;a.target='_blank';a.rel='noopener noreferrer';a.textContent='MORE GAMES ↗';return a;}
function panel(type,kicker,title,body,actions){overlayType=type;clearInput();$('main-menu').hidden=true;$('overlay').hidden=false;$('menu-brand').hidden=false;$('hud').hidden=true;$('pause-button').hidden=true;$('keyboard-guide').hidden=true;$('touch-controls').hidden=true;$('notice').classList.remove('show');$('panel-kicker').textContent=kicker;$('panel-title').textContent=title;$('panel-content').innerHTML=body;$('panel-actions').replaceChildren(...actions,makeMore());}
function pauseGame(){if(game.state!=='play'||transition)return;game.pause();const t=THEMES[game.chapter];panel('pause','CHAPTER '+String(game.chapter+1).padStart(2,'0')+' / 05', 'HOLD YOUR POSITION', '<p>'+t.name+' · '+t.areas[game.area]+'</p><p>Take a breath. The fight will wait.</p>',[makeButton('RESUME',()=>{game.resume();showPlay();},true),makeButton('CONTROLS',()=>showHelp('pause')),makeButton('MAIN MENU',showMain)]);}
function showHelp(back){helpBack=back;const controls=[['WASD','MOVE','Or use the arrow keys. Change lanes to evade.'],['J','MELEE COMBO','Three strikes end with a heavy knockback.'],['K','CHAINSAW','Uses 45 charge. Land strikes to recharge.'],['L','LANCER FIRE','Hold to fire. Face targets in the same lane.'],['SPACE','DODGE ROLL','Roll through attacks. Brief invulnerability.'],['R','ACTIVE RELOAD','Press again in the white zone for a damage boost.']];panel('help','FIELD MANUAL','CLOSE IN. HIT HARD.', '<div class="controls-grid">'+controls.map(([key,title,desc])=>'<div class="control-row"><kbd>'+key+'</kbd><div><strong>'+title+'</strong><small>'+desc+'</small></div></div>').join('')+'</div><p class="help-tip">Break supplies for health and ammunition. Clear every threat, then move right. On touchscreens, use the movement stick and action buttons.</p>',[makeButton('BACK',()=>{if(helpBack==='pause'){game.state='play';pauseGame();}else showMain();},true)]);}
function chapterDots(){return '<div class="chapters-mini">'+THEMES.map((t,i)=>'<span class="'+(i<game.chapter?'done':i===game.chapter?'active':'')+'">'+String(i+1).padStart(2,'0')+' '+t.name+'</span>').join('')+'</div>';}
function outcome(victory){const t=THEMES[game.chapter];panel(victory?'victory':'chapter',victory?'CAMPAIGN COMPLETE':'CHAPTER '+String(game.chapter+1).padStart(2,'0')+' COMPLETE',victory?'THE LINE HOLDS.':'FRONT SECURED', '<p>'+ (victory?'RAAM has fallen. You fought through all five fronts on Sera.':t.boss+' is down. Regroup and move to '+THEMES[game.chapter+1].name+'.')+'</p>'+chapterDots()+'<div class="stats"><div><span>SCORE</span><strong>'+String(game.score).padStart(6,'0')+'</strong></div><div><span>LOCUST DEFEATED</span><strong>'+game.kills+'</strong></div><div><span>BEST COMBO</span><strong>'+game.maxCombo+'</strong></div></div>'+(!victory?'<p>Next chapter: +40 health, a full magazine, and 48 reserve rounds.</p>':''),[makeButton(victory?'PLAY AGAIN':'NEXT CHAPTER',()=>victory?begin():nextChapter(),true),makeButton('MAIN MENU',showMain)]);if(victory)deleteSave();}
function defeat(){panel('defeat','MARCUS FENIX · KIA','GET BACK IN THE FIGHT', '<p>Retry '+THEMES[game.chapter].name+' from its opening checkpoint.</p><p>Your chapter-entry health, supplies, and score will be restored.</p>',[makeButton('RETRY CHAPTER',()=>{cinematic=false;effects=[];tracers=[];floats=[];game.retry();camera=0;showPlay();},true),makeButton('MAIN MENU',showMain)]);}
function nextChapter(){if(transition)return;transition=true;clearInput();$('overlay').hidden=true;$('menu-brand').hidden=true;const next=THEMES[game.chapter+1];$('transition-kicker').textContent='CHAPTER '+String(game.chapter+2).padStart(2,'0')+' / 05';$('transition-name').textContent=next.name;$('chapter-transition').classList.add('visible');setTimeout(()=>{game.enterChapter();game.state='transition';camera=0;effects=[];tracers=[];floats=[];},640);setTimeout(()=>{$('chapter-transition').classList.remove('visible');},1680);setTimeout(()=>{transition=false;game.state='play';showPlay();showNotice(next.brief+'\n+40 HEALTH · AMMO RESUPPLIED',3.7);},2250);}
game.onEvent=e=>{
 switch(e.type){
  case'checkpoint':writeSave(e.save);break;
  case'notice':showNotice(e.text,e.duration);break;
  case'sound':sound(e.sound);break;
  case'shake':shake=Math.max(shake,e.strength);break;
  case'hurt':flash=.26;shake=5;break;
  case'impact':for(let i=0;i<e.count;i++)effects.push({x:e.x,y:e.y,z:e.height,vx:(Math.random()-.5)*190,vy:(Math.random()-.5)*65,vz:90+Math.random()*150,life:.28+Math.random()*.35,color:e.color,size:1+Math.random()*3});break;
  case'damageText':floats.push({x:e.x,y:e.y,z:150,text:String(e.amount),life:.65,color:e.color});break;
  case'float':floats.push({x:e.x,y:e.y,z:105,text:e.text,life:1.1,color:e.color});break;
  case'tracer':tracers.push({...e,life:.065});break;
  case'chapterComplete':outcome(false);break;
  case'victory':outcome(true);break;
  case'defeat':defeat();break;
 }
};
function resize(){width=canvas.clientWidth;height=canvas.clientHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.imageSmoothingEnabled=false;}
window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',()=>{resize();const full=!!document.fullscreenElement;$('fullscreen-button').setAttribute('aria-label',full?'Exit fullscreen':'Enter fullscreen');$('fullscreen-button').title=full?'Exit fullscreen (F)':'Enter fullscreen (F)';});if(window.visualViewport)visualViewport.addEventListener('resize',resize);
function frameFor(actor){if(actor===game.player){if(actor.action==='dead')return 8;if(actor.action==='hurt')return 7;if(actor.action==='roll'||actor.action==='reload')return 6;if(actor.action==='fire')return 5;if(actor.action==='saw')return 4;if(actor.action==='melee')return 3;}else{if(actor.hp<=0)return 5;if(actor.action==='hurt')return 4;if(actor.action==='attack')return 3;}
 return actor.moving?1+(Math.floor(actor.walk/(actor.type==='wretch'?40:49))%2):0;
}
function sprite(key,frame,x,y,bodyHeight,face=1){const meta=catalog.actors[key]||catalog.props[key],im=images[key];if(!meta||!im)return;const cw=meta.cellWidth,ch=meta.cellHeight,anchor=meta.anchor||[cw/2,ch*.95],bounds=meta.frames?.[0]?.bounds||[0,0,cw,ch],scale=bodyHeight/(bounds[3]-bounds[1]);ctx.save();ctx.translate(Math.round(x),Math.round(y));ctx.scale(face,1);ctx.drawImage(im,(frame%meta.cols)*cw,Math.floor(frame/meta.cols)*ch,cw,ch,Math.round(-anchor[0]*scale),Math.round(-anchor[1]*scale),Math.round(cw*scale),Math.round(ch*scale));ctx.restore();}
function worldPoint(x,y){return {x:(x-camera)*zoom,y:groundBase+(y-135)*zoom*laneScale};}
function layer(theme,name,factor,bottom,drawH){const key=theme+'-'+name,im=images[key];if(!im)return;const drawW=drawH*im.width/im.height,offset=((camera*zoom*factor)%drawW+drawW)%drawW;for(let x=-offset-drawW;x<width+drawW;x+=drawW){ctx.drawImage(im,Math.floor(x),Math.floor(bottom-drawH),Math.ceil(drawW)+1,Math.ceil(drawH)+1);}}
function scenery(){const theme=THEMES[game.chapter].id;ctx.fillStyle=game.chapter===2?'#1c1b18':game.chapter===4?'#241716':'#19282e';ctx.fillRect(0,0,width,height);const floorTop=horizon-15;
 layer(theme,'far',.08,horizon+95*zoom,Math.max(horizon+100*zoom,height*.69));
 const ground=images[theme+'-ground'];if(ground){const h=Math.max(height-floorTop,190*zoom),w=h*ground.width/ground.height,off=((camera*zoom)%w+w)%w;for(let x=-off-w;x<width+w;x+=w)ctx.drawImage(ground,Math.floor(x),Math.floor(floorTop),Math.ceil(w)+1,Math.ceil(h)+1);}
 layer(theme,'mid',.30,horizon+43*zoom,Math.max(horizon*.78,200*zoom));
 layer(theme,'near',.62,horizon+NEAR_BASE*zoom,Math.max(horizon*.55,155*zoom));
 const shade=ctx.createLinearGradient(0,floorTop,0,height);shade.addColorStop(0,'#06101618');shade.addColorStop(1,'#06101665');ctx.fillStyle=shade;ctx.fillRect(0,floorTop,width,height-floorTop);
}
function shadow(point,w){ctx.fillStyle='#02070980';ctx.beginPath();ctx.ellipse(point.x,point.y-1,w*zoom,11*zoom,0,0,Math.PI*2);ctx.fill();}
function label(text,x,y,color,size=12){ctx.font=size+'px Russo,Arial';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#09131ee8';ctx.strokeText(text,x,y);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function drawActor(actor){const p=worldPoint(actor.x,actor.y),isPlayer=actor===game.player,key=isPlayer?'marcus':actor.type,h=isPlayer?184:actor.height;
 if(p.x<-300||p.x>width+300)return;
 shadow(p,isPlayer?43:actor.type==='wretch'?34:44*(actor.boss?1.2:1));
 if(!isPlayer&&actor.hp>0&&actor.action==='windup'){
  const progress=1-actor.timer/actor.duration;ctx.strokeStyle=actor.type==='grenadier'?'#eaa761':'#dc6250';ctx.lineWidth=2*zoom;ctx.beginPath();ctx.ellipse(p.x,p.y,60*zoom,19*zoom,0,-Math.PI*.5,-Math.PI*.5+Math.PI*2*progress);ctx.stroke();label('!',p.x,p.y-h*zoom-13*zoom,'#ffd596',21*zoom);
  if(actor.type==='grenadier'){ctx.setLineDash([7*zoom,8*zoom]);const target=worldPoint(actor.attackTarget.x,actor.attackTarget.y);ctx.strokeStyle='#e4986265';ctx.beginPath();ctx.moveTo(p.x,p.y-60*zoom);ctx.lineTo(target.x,target.y-60*zoom);ctx.stroke();ctx.setLineDash([]);}
 }
 sprite(key,frameFor(actor),p.x,p.y,h*zoom,actor.face);
 if(!isPlayer&&actor.hp>0&&actor.hp<actor.maxHP&&!actor.boss){ctx.fillStyle='#071216bd';ctx.fillRect(p.x-24*zoom,p.y-h*zoom-12*zoom,48*zoom,4*zoom);ctx.fillStyle='#d0715e';ctx.fillRect(p.x-24*zoom,p.y-h*zoom-12*zoom,48*zoom*(actor.hp/actor.maxHP),4*zoom);}
 if(isPlayer&&actor.invuln>0&&game.state==='play'){ctx.strokeStyle='#9bd3e76e';ctx.lineWidth=2*zoom;ctx.beginPath();ctx.ellipse(p.x,p.y,44*zoom,10*zoom,0,0,Math.PI*2);ctx.stroke();}
}
function drawProp(prop){const p=worldPoint(prop.x,prop.y);if(p.x<-180||p.x>width+180)return;shadow(p,37);sprite(prop.theme+'-prop',prop.state,p.x,p.y,(prop.theme==='refinery'?118:prop.theme==='hollow'?106:104)*zoom);}
function drawPickup(item){const p=worldPoint(item.x,item.y),bounce=Math.sin(game.time*4+item.id)*4*zoom;p.y-=39*zoom+bounce;ctx.fillStyle=item.type==='health'?'#132e26e8':'#102b36e8';ctx.strokeStyle=item.type==='health'?'#89c3a0':'#75bed4';ctx.lineWidth=1;const boxW=(item.type==='health'?52:62)*zoom;ctx.fillRect(p.x-boxW/2,p.y-12*zoom,boxW,24*zoom);ctx.strokeRect(p.x-boxW/2,p.y-12*zoom,boxW,24*zoom);label(item.type==='health'?'+ HP':'AMMO',p.x,p.y+3*zoom,item.type==='health'?'#b3e4c0':'#a9e0f0',10*zoom);}
function layoutBattlefield(dt){
 horizon=height*(width<600?.52:.54);
 const floorTop=horizon-15,floorHeight=Math.max(height-floorTop,190*zoom);
 const back=horizon+(NEAR_BASE+FLOOR_INSET)*zoom;
 const front=floorTop+floorHeight*GROUND_FRONT[game.chapter]-10*zoom;
 laneScale=Math.min(LANE_DEPTH,(front-back)/((LANES.max-LANES.min)*zoom));
 groundBase=back+(135-LANES.min)*laneScale*zoom;
 const view=width/zoom,target=clamp(game.player.x-view*.40,-ACTOR_MARGIN,Math.max(-ACTOR_MARGIN,3*AREA-view+ACTOR_MARGIN));
 if(game.state==='play')camera+=(target-camera)*Math.min(1,dt*5);else if(!game.hasRun)camera=target;
 const margin=Math.min(ACTOR_MARGIN,view*.25);
 camera=clamp(camera,game.player.x-view+margin,game.player.x-margin);
}
function render(dt){ctx.setTransform(dpr,0,0,dpr,0,0);const preview=cinematic&&!game.hasRun;
 zoom=preview?clamp(height/570,1.1,1.9)*1.8:Math.max(.46,Math.min(height/700,width/650,1.5));
 if(preview){laneScale=LANE_DEPTH;horizon=height*.54;groundBase=height*.83;camera=game.player.x-width*.69/zoom;}
 else layoutBattlefield(dt);
 const shakeX=game.state==='play'?(Math.random()-.5)*shake:0,shakeY=game.state==='play'?(Math.random()-.5)*shake*.45:0;ctx.translate(shakeX,shakeY);scenery();
 const drawables=[...game.props.map(p=>({y:p.y,draw:()=>drawProp(p)})),...game.enemies.map(e=>({y:e.y,draw:()=>drawActor(e)})),{y:game.player.y,draw:()=>drawActor(game.player)}];
 drawables.sort((a,b)=>a.y-b.y);for(const o of drawables)o.draw();for(const item of game.pickups)drawPickup(item);
 for(const b of game.projectiles){const p=worldPoint(b.x,b.y);ctx.strokeStyle='#e5af77';ctx.lineWidth=3*zoom;ctx.beginPath();ctx.moveTo(p.x-Math.sign(b.vx)*15*zoom,p.y-64*zoom);ctx.lineTo(p.x,p.y-64*zoom);ctx.stroke();}
 for(const t of tracers){const a=worldPoint(t.x,t.y),b=worldPoint(t.x2,t.y2);ctx.strokeStyle='#f2d391b0';ctx.lineWidth=1.3*zoom;ctx.beginPath();ctx.moveTo(a.x,a.y-97*zoom);ctx.lineTo(b.x,b.y-90*zoom);ctx.stroke();}
 for(const e of effects){const p=worldPoint(e.x,e.y);ctx.fillStyle=e.color;ctx.fillRect(p.x,p.y-e.z*zoom,e.size*zoom,e.size*zoom);}
 for(const f of floats){const p=worldPoint(f.x,f.y);label(f.text,p.x,p.y-f.z*zoom,f.color,Math.max(9,13*zoom));}
 if(game.clear&&game.state==='play'){const gate=worldPoint((game.area+1)*AREA-105,135);const gx=clamp(gate.x,70,width-65);const gy=groundBase-80*zoom;label(game.area===2?'EXTRACT':'MOVE RIGHT',gx,gy-34*zoom,'#d9ecbd',Math.max(10,13*zoom));ctx.strokeStyle='#b2d68d';ctx.lineWidth=3*zoom;const shift=Math.sin(game.time*5)*5*zoom;ctx.beginPath();ctx.moveTo(gx-17*zoom+shift,gy-13*zoom);ctx.lineTo(gx+shift,gy);ctx.lineTo(gx-17*zoom+shift,gy+13*zoom);ctx.moveTo(gx+3*zoom+shift,gy-13*zoom);ctx.lineTo(gx+20*zoom+shift,gy);ctx.lineTo(gx+3*zoom+shift,gy+13*zoom);ctx.stroke();}
 ctx.setTransform(dpr,0,0,dpr,0,0);
 if(flash>0){ctx.fillStyle='rgba(168,26,25,'+(flash*.65)+')';ctx.fillRect(0,0,width,height);}
}
function updateEffects(dt){shake=Math.max(0,shake-dt*24);flash=Math.max(0,flash-dt);for(const e of effects){e.x+=e.vx*dt;e.y+=e.vy*dt;e.z+=e.vz*dt;e.vz-=750*dt;e.life-=dt;}effects=effects.filter(e=>e.life>0&&e.z>0);for(const f of floats){f.life-=dt;f.z+=35*dt;}floats=floats.filter(f=>f.life>0);tracers.forEach(t=>t.life-=dt);tracers=tracers.filter(t=>t.life>0);}
function updateHUD(){const p=game.player,t=THEMES[game.chapter];$('health-value').textContent=Math.ceil(p.hp)+' / 100';$('health-fill').style.width=p.hp+'%';$('health-fill').style.background=p.hp<30?'#d24f41':'#7ac3d0';$('fury-fill').style.width=p.fury+'%';$('fury-value').textContent=p.fury>=45?'READY':Math.round(p.fury)+'%';$('ammo-value').textContent=String(p.ammo).padStart(2,'0');$('reserve-value').textContent='/ '+p.reserve;$('chapter-label').textContent='CH. '+String(game.chapter+1).padStart(2,'0')+' / 05 · AREA '+String(game.area+1).padStart(2,'0')+' / 03';$('area-label').textContent=t.areas[game.area];$('objective-label').textContent=game.clear?'AREA SECURED · MOVE RIGHT':game.remaining+' LOCUST REMAINING';$('objective-label').style.color=game.clear?'#bce0a4':'';$('score-value').textContent=String(game.score).padStart(6,'0');$('combo-value').textContent=game.combo>=3?game.combo+' HIT COMBO':'';$('reload-ui').hidden=p.action!=='reload';if(p.action==='reload'){$('reload-cursor').style.left=clamp((1-p.timer/p.reloadTotal)*100,0,100)+'%';$('reload-label').textContent=p.reloadTried?'RELOADING…':'RELOAD · HIT R IN THE WHITE ZONE';}const boss=game.boss;$('boss-hud').hidden=!boss;if(boss){$('boss-label').textContent=t.boss;$('boss-fill').style.width=(boss.hp/boss.maxHP*100)+'%';}}
function tick(now){const dt=Math.min(.04,(now-lastTime)/1000||.016);lastTime=now;const active=game.state==='play';if(active){const actions=[];if(keys.has('KeyJ')||pressed.has('melee'))actions.push('melee');if(keys.has('KeyK')||pressed.has('saw'))actions.push('saw');if(keys.has('KeyL')||pressed.has('fire'))actions.push('fire');if(agentInput)actions.push(...agentInput.actions);game.step(dt,{x:(agentInput?.x||0)+stickX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y:(agentInput?.y||0)+stickY+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),actions});updateEffects(dt);if(noticeTime>0){noticeTime-=dt;if(noticeTime<=0)$('notice').classList.remove('show');}uiClock+=dt;if(uiClock>.08){uiClock=0;updateHUD();}}else if(game.state==='dying'){game.step(dt,{});updateEffects(dt);}render(dt);requestAnimationFrame(tick);}
function keydown(e){if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','Tab'].includes(e.code)&&e.code!=='Tab')e.preventDefault();if(e.repeat&&['KeyR','Space','Escape','KeyP','KeyM','KeyF'].includes(e.code))return;if(e.code==='KeyM'){toggleSound();return;}if(e.code==='KeyF'){fullscreen();return;}if(e.code==='Escape'||e.code==='KeyP'){if(game.state==='play')pauseGame();else if(overlayType==='pause'){game.resume();showPlay();}else if(overlayType==='help'){if(helpBack==='pause'){game.state='play';pauseGame();}else showMain();}return;}if(game.state!=='play')return;keys.add(e.code);if(!e.repeat){if(e.code==='KeyJ')game.action('melee');if(e.code==='KeyK')game.action('saw');if(e.code==='KeyL')game.action('fire');}if(e.code==='Space')game.action('roll');if(e.code==='KeyR')game.action('reload');}
document.addEventListener('keydown',keydown);document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pauseGame();}});
$('start-button').onclick=()=>{if(loadDone)begin();else loadAssets();};$('continue-button').onclick=()=>begin(readSave());$('help-button').onclick=()=>showHelp('main');$('pause-button').onclick=pauseGame;$('sound-button').onclick=toggleSound;$('fullscreen-button').onclick=fullscreen;$('reload-button').onclick=()=>game.action('reload');
const stick=$('stick');stick.addEventListener('pointerdown',e=>{if(game.state!=='play')return;touchMode=true;initAudio();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);const r=stick.getBoundingClientRect();stickStart={x:r.left+r.width/2,y:r.top+r.height/2};moveStick(e);});function moveStick(e){if(e.pointerId!==stickPointer)return;const dx=e.clientX-stickStart.x,dy=e.clientY-stickStart.y,len=Math.hypot(dx,dy),limit=35,ratio=Math.min(1,limit/(len||1));stickX=clamp(dx/limit,-1,1);stickY=clamp(dy/limit,-1,1);if(len<7)stickX=stickY=0;$('stick-knob').style.transform='translate('+dx*ratio+'px,'+dy*ratio+'px)';}stick.addEventListener('pointermove',moveStick);function endStick(e){if(e.pointerId===stickPointer){stickPointer=null;stickX=stickY=0;$('stick-knob').style.transform='';}}stick.addEventListener('pointerup',endStick);stick.addEventListener('pointercancel',endStick);stick.addEventListener('lostpointercapture',endStick);
document.querySelectorAll('.touch-action').forEach(b=>{const action=b.dataset.action;b.addEventListener('pointerdown',e=>{e.preventDefault();if(game.state!=='play')return;initAudio();b.setPointerCapture(e.pointerId);b.classList.add('pressed');game.action(action);if(action!=='roll')pressed.add(action);});const end=()=>{pressed.delete(action);b.classList.remove('pressed');};b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);b.addEventListener('lostpointercapture',end);});
document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!touchMode){touchMode=true;if(game.state==='play')showPlay();}},{passive:true});
async function loadAssets(){const entries=[];for(const [key,meta]of Object.entries(catalog.actors))entries.push([key,meta.file||key+'.png']);for(const [key,meta]of Object.entries(catalog.props))entries.push([key,meta.file||key+'.png']);for(const[id,layers]of Object.entries(catalog.themes))for(const name of ['far','mid','near','ground'])entries.push([id+'-'+name,layers[name]?.file||id+'-'+name+'.png']);let complete=0,failed=[];const total=entries.length+1;loadDone=false;$('start-button').disabled=true;$('loading-error').hidden=true;const progress=()=>{const pct=Math.round(complete/total*100);$('start-button').firstElementChild.textContent='LOADING '+pct+'%';$('start-button').style.setProperty('--load',pct+'%');};progress();await Promise.all(entries.map(([key,file])=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images[key]=im;complete++;progress();resolve();};im.onerror=()=>{failed.push(file);complete++;progress();resolve();};im.src='assets/'+file;})));try{await document.fonts.load('16px Russo');}catch{}complete++;progress();if(!entries.length)failed.push('artwork');if(failed.length){$('start-button').disabled=false;$('start-button').firstElementChild.textContent='RETRY LOADING';$('loading-error').textContent='Some artwork could not load. Check your connection and try again.';$('loading-error').hidden=false;return;}loadDone=true;$('start-button').disabled=false;$('start-button').firstElementChild.textContent='START GAME';const save=readSave();$('continue-button').hidden=!save;$('continue-button').textContent=save?'CONTINUE · CHAPTER '+String(save.chapter+1).padStart(2,'0'):'';}
function battleStatus(){const p=game.player;return{state:game.state,chapter:game.chapter+1,chapterName:THEMES[game.chapter].name,area:game.area+1,objective:game.clear?'Move right to the exit':'Defeat all Locust',health:p.hp,ammo:p.ammo,reserve:p.reserve,chainsaw:Math.round(p.fury),score:game.score,remaining:game.remaining,player:{x:Math.round(p.x),lane:Math.round(p.y),facing:p.face,action:p.action},enemies:game.enemies.filter(e=>e.hp>0).map(e=>({type:e.type,boss:e.boss,health:e.hp,relativeX:Math.round(e.x-p.x),relativeLane:Math.round(e.y-p.y),action:e.action})),supplies:game.pickups.map(i=>({type:i.type,relativeX:Math.round(i.x-p.x),relativeLane:Math.round(i.y-p.y)}))};}
if(document.modelContext?.registerTool){const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}};register({name:'read_battle_status',description:'Read the current battlefield, player supplies, nearby enemies, and campaign progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>battleStatus()});register({name:'campaign_menu',description:'Use the game menu to start a new campaign, continue a checkpoint, pause, resume, retry the current chapter, or advance after completing a chapter.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','continue','pause','resume','retry','next_chapter']}},required:['action'],additionalProperties:false},execute:async({action})=>{if(!loadDone)throw Error('Game assets are still loading.');if(!['start','continue','pause','resume','retry','next_chapter'].includes(action))throw Error('Unknown menu action.');if(action==='start'){if(game.state==='play')throw Error('Return to the menu before starting again.');begin();}if(action==='continue'){const s=readSave();if(!s)throw Error('No saved checkpoint.');begin(s);}if(action==='pause')pauseGame();if(action==='resume'){if(game.state!=='pause')throw Error('The game is not paused.');game.resume();showPlay();}if(action==='retry'){if(game.state!=='dead')throw Error('Retry is available after defeat.');game.retry();camera=0;showPlay();}if(action==='next_chapter'){if(game.state!=='chapter')throw Error('Complete this chapter first.');nextChapter();await new Promise(r=>setTimeout(r,2300));}return battleStatus();}});register({name:'play_controls',description:'Hold normal game controls for 50–1000 milliseconds. Movement x and y range from -1 to 1; y changes the combat lane. Combat actions use normal timing, ammo, and charge. Use reload or dodge once at the start of the input.',inputSchema:{type:'object',properties:{x:{type:'number',minimum:-1,maximum:1},y:{type:'number',minimum:-1,maximum:1},milliseconds:{type:'integer',minimum:50,maximum:1000},attack:{type:'string',enum:['none','melee','saw','fire']},reload:{type:'boolean'},dodge:{type:'boolean'}},required:['milliseconds'],additionalProperties:false},execute:async({x=0,y=0,milliseconds,attack='none',reload=false,dodge=false})=>{if(!Number.isFinite(x)||!Number.isFinite(y)||Math.abs(x)>1||Math.abs(y)>1||!Number.isInteger(milliseconds)||milliseconds<50||milliseconds>1000||!['none','melee','saw','fire'].includes(attack))throw Error('Invalid control input.');if(game.state!=='play')throw Error('Start or resume the game first.');if(agentInput)throw Error('Another control input is active.');initAudio();agentInput={x,y,actions:attack==='none'?[]:[attack]};game.inputX=x;game.inputY=y;if(reload)game.action('reload');if(dodge)game.action('roll');try{await new Promise(r=>setTimeout(r,milliseconds));}finally{agentInput=null;}updateHUD();return battleStatus();}});}
game.player.x=400;game.player.y=135;game.enemies=[{id:999,type:'drone',x:500,y:119,hp:64,maxHP:64,height:184,face:-1,action:'idle',moving:false,walk:0}];game.props=game.props.filter(p=>p.x>650);
updateSound();resize();loadAssets();requestAnimationFrame(tick);
})();
