(function(root){
'use strict';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), AREA=880, LANES={min:18,max:208};
const THEMES=[
 {id:'hotel',name:'Wrenwood Hotel',areas:['Hotel Approach','Service Courtyard','The Locked Gate'],brief:'Find the route through Wrenwood. Clear the infected.',boss:'THE DOORMAN',bossType:'brute',bossHP:330,pattern:['swing','slam'],propHeight:66,colors:['#263344','#d89b68'],roster:[['infected','infected','infected'],['infected','infected','spitter'],['infected','infected']]},
 {id:'ward',name:'Rhodes Hill',areas:['The Care Center','Treatment Wing','Intensive Care'],brief:'Search Rhodes Hill. Follow Grace’s transmission.',boss:'WARD OVERSEER',bossType:'brute',bossHP:460,pattern:['swing','dash','slam'],propHeight:98,colors:['#153238','#99c6bc'],roster:[['infected','spitter','infected'],['infected','brute','infected'],['spitter','infected']]},
 {id:'isolation',name:'Isolation Wing',areas:['Service Tunnels','Quarantine Block','Containment Breach'],brief:'Cut through quarantine. Stop the contamination.',boss:'QUARANTINE CARRIER',bossType:'spitter',bossHP:450,pattern:['bolt','volley','slam'],propHeight:105,colors:['#2c3431','#bed087'],roster:[['spitter','infected','spitter'],['brute','spitter','infected'],['infected','spitter']]},
 {id:'city',name:'Raccoon City',areas:['Ashen Streets','Police Barricade','Collapsed Overpass'],brief:'Return to the ruins. Reach the underground entrance.',boss:'RUIN STALKER',bossType:'brute',bossHP:580,pattern:['dash','swing','slam','dash'],propHeight:85,colors:['#39343d','#d99170'],roster:[['brute','infected','infected'],['spitter','brute','infected','infected'],['spitter','infected','infected']]},
 {id:'ark',name:'ARK Facility',areas:['Access Control','Bio-Storage','Last Extraction'],brief:'Purge the facility. Reach Grace at the extraction point.',boss:'REQUIEM TYRANT',bossType:'brute',bossHP:760,pattern:['volley','dash','slam','swing'],propHeight:108,colors:['#172b40','#86cddd'],roster:[['spitter','infected','brute'],['brute','spitter','infected','infected'],['spitter','infected']]}
];
for(const t of THEMES){t.roster[0].push('infected');t.roster[1].push('infected','spitter');t.roster[2].push('infected');}
const TYPES={infected:{hp:66,speed:78,reach:86,wind:.86,recovery:1.2,damage:8,height:166},spitter:{hp:82,speed:65,reach:440,wind:1.12,recovery:1.65,damage:10,height:169},brute:{hp:155,speed:59,reach:118,wind:1.12,recovery:1.45,damage:13,height:216}};
class Engine {
 constructor(){this.onEvent=()=>{};this.state='menu';this.chapter=0;this.player=this.newPlayer();this.enemies=[];this.props=[];this.pickups=[];this.projectiles=[];this.areas=[];this.score=0;this.kills=0;this.combo=0;this.maxCombo=0;this.time=0;this.frontier=0;this.area=0;this.checkpoint=null;this.nextId=1;}
 newPlayer(){return{x:125,y:116,hp:100,maxHP:100,stamina:100,focus:40,flasks:2,ammo:8,reserve:56,magSize:8,face:1,action:'idle',timer:0,duration:0,walk:0,moving:false,invuln:0,rollCD:0,chain:0,comboStep:0,queued:'',queueTime:0,hitDone:false,regenWait:0};}
 emit(type,data={}){this.onEvent({type,...data});}
 rand(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296;}
 start(save){this.chapter=save&&Number.isInteger(save.chapter)&&save.chapter>=0&&save.chapter<5?save.chapter:0;this.score=save?clamp(Number(save.score)||0,0,99999999):0;this.kills=save?clamp(Number(save.kills)||0,0,9999):0;this.maxCombo=save?clamp(Number(save.maxCombo)||0,0,9999):0;this.loadChapter();}
 loadChapter(){this.player=this.newPlayer();this.enemies=[];this.props=[];this.pickups=[];this.projectiles=[];this.areas=THEMES[this.chapter].areas.map(()=>({active:false,cleared:false}));this.frontier=0;this.area=0;this.combo=0;this.comboTimer=0;this.time=0;this.seed=7183+this.chapter*199;this.nextId=1;this.inputX=this.inputY=0;this.state='play';this.checkpoint={chapter:this.chapter,score:this.score,kills:this.kills,maxCombo:this.maxCombo};
  const theme=THEMES[this.chapter];for(let a=0;a<3;a++){theme.roster[a].forEach((type,i)=>this.spawnEnemy(type,a*AREA+325+(i%4)*123,34+(i%4)*49,a));if(a===2)this.spawnEnemy(theme.bossType,a*AREA+720,116,a,true);[[265,195],[575,32],[780,191]].forEach(([x,y],i)=>this.props.push({id:this.nextId++,x:x+a*AREA,y,hp:50,state:0,awarded:false,drop:i===1?'ammo':'health',theme:theme.id}));}this.activate(0);this.emit('checkpoint',{save:{...this.checkpoint}});this.emit('notice',{text:theme.brief,duration:3.4});}
 retry(){if(!this.checkpoint)return;Object.assign(this,{chapter:this.checkpoint.chapter,score:this.checkpoint.score,kills:this.checkpoint.kills,maxCombo:this.checkpoint.maxCombo});this.loadChapter();}
 nextChapter(){if(this.state!=='chapter'||this.chapter>=4)return false;this.chapter++;this.loadChapter();return true;}
 pause(){if(this.state==='play'){this.state='paused';return true;}return false;}
 resume(){if(this.state==='paused')this.state='play';}
 spawnEnemy(type,x,y,area,boss=false){const t=TYPES[type],hp=boss?THEMES[this.chapter].bossHP:Math.round(t.hp*(1+this.chapter*.05));this.enemies.push({id:this.nextId++,type,x,y,hp,maxHP:hp,area,boss,height:t.height*(boss?1.1:1),face:-1,action:'idle',timer:0,duration:0,cd:.6+this.rand(),walk:0,moving:false,active:false,attackCount:0,kind:'swing',hitDone:false,deadTime:0,phase:false,staggerCD:0});}
 activate(a){if(this.areas[a].active)return;this.areas[a].active=true;this.frontier=a;for(const e of this.enemies)if(e.area===a)e.active=true;}
 get upper(){return Math.min(3*AREA-26,(this.frontier+1)*AREA-(this.areas[this.frontier]?.cleared?0:42));}
 get remaining(){return this.enemies.filter(e=>e.active&&e.hp>0).length;}
 get boss(){return this.enemies.find(e=>e.active&&e.boss&&e.hp>0);}
 startAction(name,duration){const p=this.player;p.action=name;p.timer=p.duration=duration;p.moving=false;p.hitDone=false;}
 action(name){if(this.state!=='play')return false;const p=this.player;
  if(name==='roll'){if(p.rollCD>0||p.stamina<18||p.hp<=0||p.action==='heal')return false;p.stamina-=18;p.regenWait=.4;p.rollCD=.7;p.invuln=Math.max(p.invuln,.38);const x=this.inputX||(!this.inputY?p.face:0),y=this.inputY||0,l=Math.hypot(x,y)||1;p.rollX=x/l;p.rollY=y/l;this.startAction('roll',.31);p.queued='';this.emit('sound',{name:'roll'});return true;}
  if(!['idle','walk'].includes(p.action)){if(name==='attack'&&p.action==='attack'&&p.timer<.19){p.queued=name;p.queueTime=.3;}return false;}
  if(name==='heal'){if(p.flasks<1||p.hp>=p.maxHP)return false;p.flasks--;this.startAction('heal',.72);this.emit('sound',{name:'heal'});return true;}
  if(name==='reload'){if(p.ammo>=p.magSize||p.reserve<=0)return false;this.startAction('reload',.86);this.emit('sound',{name:'reload'});return true;}
  if(name==='special'){if(p.focus<100){this.emit('hint',{text:'Build adrenaline by defeating enemies'});return false;}p.focus=0;p.invuln=1.0;this.startAction('special',.68);this.emit('sound',{name:'burst'});return true;}
  if(name==='shoot'){if(p.ammo<=0){this.emit('hint',{text:p.reserve>0?'Reload · R':'Find ammunition in supply containers'});return false;}this.startAction('shoot',.29);return true;}
  if(name==='heavy'){if(p.stamina<25)return false;p.stamina-=25;p.regenWait=.55;this.startAction('heavy',.64);this.emit('sound',{name:'kick'});return true;}
  if(name==='attack'){if(p.stamina<7)return false;p.stamina-=7;p.regenWait=.2;p.comboStep=p.chain>0?p.comboStep%3+1:1;p.chain=.95;this.startAction('attack',p.comboStep===3?.46:.31);return true;}return false;
 }
 hitProp(o,damage){if(o.hp<=0)return;o.hp=Math.max(0,o.hp-damage);o.state=o.hp===0?2:1;this.emit('impact',{x:o.x,y:o.y,z:32,color:'#dcb571',count:8});if(o.hp===0&&!o.awarded){o.awarded=true;this.score+=50;this.pickups.push({id:this.nextId++,x:o.x,y:o.y,type:o.drop});this.emit('sound',{name:'break'});}}
 hitEnemy(e,damage,kind,face){if(e.hp<=0||!e.active)return;e.hp=Math.max(0,e.hp-damage);const knock=kind==='heavy'?58:kind==='finisher'?42:kind==='shoot'?25:12;e.x=clamp(e.x+face*knock,28,this.upper);if(!e.boss||((kind==='heavy'||kind==='finisher')&&e.staggerCD<=0)){if(e.boss)e.staggerCD=2.5;e.action='hurt';e.timer=kind==='heavy'?.58:.24;e.cd=Math.max(e.cd,e.timer+.25);}this.combo++;this.comboTimer=3;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=Math.round(damage*(1+Math.min(3,Math.floor(this.combo/8))*.2));this.emit('impact',{x:e.x,y:e.y,z:e.height*.57,color:kind==='shoot'?'#83e3f0':'#f8d78a',count:kind==='heavy'?14:7});this.emit('float',{x:e.x,y:e.y,z:e.height+5,text:String(damage),color:'#ffe8b3'});this.emit('sound',{name:kind==='heavy'?'kick':'punch'});this.emit('shake',{amount:kind==='heavy'?4:2});
  if(e.hp===0){e.action='dead';e.deadTime=0;e.moving=false;this.kills++;this.score+=e.boss?1500:100;this.player.focus=Math.min(100,this.player.focus+16);this.player.hp=Math.min(this.player.maxHP,this.player.hp+2);if(this.kills%4===0)this.pickups.push({id:this.nextId++,x:e.x,y:e.y,type:'health'});if(e.boss){this.emit('notice',{text:'THREAT ELIMINATED',duration:3});this.emit('sound',{name:'clear'});}}
 }
 resolveAttack(){const p=this.player,heavy=p.action==='heavy',finish=p.comboStep===3&&!heavy,reach=heavy?152:finish?137:122,damage=Math.round((heavy?66:finish?42:p.comboStep===2?29:24)*(1+this.chapter*.09)),kind=heavy?'heavy':finish?'finisher':'melee';for(const e of this.enemies){const dx=(e.x-p.x)*p.face;if(e.active&&e.hp>0&&dx>-27&&dx<reach&&Math.abs(e.y-p.y)<(heavy?64:47))this.hitEnemy(e,damage,kind,p.face);}for(const o of this.props){const dx=(o.x-p.x)*p.face;if(o.hp>0&&dx>-25&&dx<reach&&Math.abs(o.y-p.y)<54)this.hitProp(o,damage);}this.emit('slash',{x:p.x+p.face*55,y:p.y,z:95,face:p.face,heavy});}
 bolt(x,y,face,enemy=false,damage=54,vy=0){this.projectiles.push({id:this.nextId++,x,y,face,initialX:x-face*(enemy?110:94),vx:face*(enemy?300:1100),vy,enemy,damage,z:enemy?125:134,life:enemy?4:.8,hits:[],pierce:1});}
 hurtPlayer(damage,e){const p=this.player;if(p.invuln>0||p.hp<=0||this.state!=='play')return false;p.hp=Math.max(0,p.hp-damage);p.invuln=.78;p.x=clamp(p.x+(p.x<e.x?-17:17),28,this.upper);this.startAction('hurt',.24);p.queued='';this.combo=0;this.emit('hurt');this.emit('sound',{name:'hurt'});if(p.hp<=0){p.action='dead';this.state='dying';this.deathTimer=1.1;}return true;}
 updateEnemy(e,dt){if(e.hp<=0){e.deadTime+=dt;return;}if(!e.active)return;const p=this.player,t=TYPES[e.type];e.moving=false;e.cd=Math.max(0,e.cd-dt);e.staggerCD=Math.max(0,e.staggerCD-dt);let dx=p.x-e.x,dy=p.y-e.y;if(!['windup','attack'].includes(e.action))e.face=dx>=0?1:-1;
  if(e.boss&&e.hp<e.maxHP*.5&&!e.phase){e.phase=true;this.emit('float',{x:e.x,y:e.y,z:e.height+30,text:'ENRAGED',color:'#f3b26b'});}
  if(e.action==='hurt'){e.timer-=dt;if(e.timer<=0)e.action='idle';return;}
  if(e.action==='windup'){e.timer-=dt;if(e.timer<=0){e.action='attack';e.timer=e.kind==='dash'?.42:.35;e.hitDone=false;this.emit('sound',{name:'enemy'});}return;}
  if(e.action==='attack'){e.timer-=dt;if(e.kind==='dash'){e.x=clamp(e.x+e.face*360*dt,28,this.upper);if(!e.hitDone&&Math.abs(p.x-e.x)<95&&Math.abs(dy)<45){e.hitDone=true;this.hurtPlayer(t.damage+4,e);}}else if(!e.hitDone){e.hitDone=true;if(e.kind==='bolt'||e.kind==='volley'){const n=e.kind==='volley'?3:1;for(let i=0;i<n;i++)this.bolt(e.x+e.face*(e.type==='spitter'?115:100),e.y,e.face,true,t.damage+(e.boss?2:0),(i-(n-1)/2)*38);}else if(e.kind==='slam'){this.emit('slam',{x:e.x,y:e.y});if(Math.abs(dx)<172&&Math.abs(dy)<78)this.hurtPlayer(t.damage+5,e);}else if(dx*e.face>-28&&Math.abs(dx)<t.reach+24&&Math.abs(dy)<45)this.hurtPlayer(t.damage+(e.boss?2:0),e);}if(e.timer<=0){e.action='idle';e.cd=t.recovery*(e.phase?.85:1)+this.rand()*.32;}return;}
  if(p.hp<=0)return;const pattern=THEMES[this.chapter].pattern,kind=e.boss?pattern[e.attackCount%pattern.length]:e.type==='spitter'?'bolt':'swing',reach=kind==='bolt'||kind==='volley'?470:kind==='dash'?280:kind==='slam'?147:t.reach;
  if(e.cd<=0&&Math.abs(dx)<reach&&Math.abs(dy)<(kind==='slam'?66:42)&&this.enemies.filter(o=>o.hp>0&&['windup','attack'].includes(o.action)).length<2){e.kind=kind;e.attackCount++;e.action='windup';e.duration=e.timer=(kind==='slam'?1.18:kind==='dash'?1.0:t.wind)*(e.phase?.9:1);return;}
  const preferred=e.type==='spitter'?280:e.type==='brute'?91:68,speed=t.speed*(e.phase?1.15:1);let vx=Math.abs(dx)>preferred?Math.sign(dx)*speed:0,vy=Math.abs(dy)>9?Math.sign(dy)*speed*.7:0;if(e.type==='spitter'&&Math.abs(dx)<160&&e.cd>.2)vx=-Math.sign(dx)*speed*.6;for(const o of this.enemies){if(o===e||o.hp<=0||!o.active)continue;const xx=e.x-o.x,yy=e.y-o.y;if(Math.abs(xx)<41&&Math.abs(yy)<26){vx+=Math.sign(xx||e.id-o.id)*20;vy+=Math.sign(yy||e.id-o.id)*18;}}
  const ox=e.x,oy=e.y;e.x=clamp(e.x+vx*dt,28,this.upper);e.y=clamp(e.y+vy*dt,LANES.min,LANES.max);const d=Math.hypot(e.x-ox,e.y-oy);e.moving=d>.03;if(e.moving){e.walk+=d;e.action='walk';}else e.action='idle';
 }
 step(dt,input={}){dt=clamp(dt,0,.04);if(this.state==='dying'){this.deathTimer-=dt;if(this.deathTimer<=0){this.state='dead';this.emit('defeat');}return;}if(this.state!=='play')return;this.time+=dt;const p=this.player;this.inputX=clamp(input.x||0,-1,1);this.inputY=clamp(input.y||0,-1,1);if(this.inputX&&['idle','walk'].includes(p.action))p.face=this.inputX>0?1:-1;for(const k of ['invuln','rollCD','chain','queueTime','regenWait'])p[k]=Math.max(0,p[k]-dt);if(!p.queueTime)p.queued='';p.stamina=clamp(p.stamina+(!p.regenWait?36:8)*dt,0,100);this.comboTimer-=dt;if(this.comboTimer<=0)this.combo=0;
  for(const a of input.actions||[])this.action(a);if(input.attack)this.action('attack');if(input.heavy)this.action('heavy');if(input.shoot)this.action('shoot');const ox=p.x,oy=p.y;p.moving=false;
  if(p.timer>0){p.timer-=dt;const elapsed=p.duration-p.timer;if(!p.hitDone){if(['attack','heavy'].includes(p.action)&&elapsed>(p.action==='heavy'?.31:p.comboStep===3?.18:.11)){p.hitDone=true;this.resolveAttack();}else if(p.action==='shoot'&&elapsed>.08){p.hitDone=true;p.ammo--;this.bolt(p.x+p.face*94,p.y,p.face,false,Math.round(54*(1+this.chapter*.08)));this.emit('sound',{name:'shoot'});}
    else if(p.action==='reload'&&elapsed>.62){p.hitDone=true;const n=Math.min(p.magSize-p.ammo,p.reserve);p.ammo+=n;p.reserve-=n;}
    else if(p.action==='special'&&elapsed>.24){p.hitDone=true;for(const e of this.enemies)if(e.active&&e.hp>0&&Math.abs(e.x-p.x)<250&&Math.abs(e.y-p.y)<110)this.hitEnemy(e,110,'heavy',Math.sign(e.x-p.x)||p.face);for(const o of this.props)if(o.hp>0&&Math.abs(o.x-p.x)<250&&Math.abs(o.y-p.y)<110)this.hitProp(o,100);this.emit('slam',{x:p.x,y:p.y});}else if(p.action==='heal'&&elapsed>.48){p.hitDone=true;p.hp=Math.min(p.maxHP,p.hp+50);this.emit('float',{x:p.x,y:p.y,z:175,text:'+50 HP',color:'#f0c96c'});this.emit('heal');}}
   if(p.action==='roll'){p.x+=p.rollX*520*dt;p.y+=p.rollY*280*dt;}if(p.timer<=0){p.action='idle';if(p.queued){const a=p.queued;p.queued='';this.action(a);}}}
  if(['idle','walk'].includes(p.action)){const l=Math.max(1,Math.hypot(this.inputX,this.inputY));p.x+=this.inputX/l*211*dt;p.y+=this.inputY/l*148*dt;}p.x=clamp(p.x,28,this.upper);p.y=clamp(p.y,LANES.min,LANES.max);const moved=Math.hypot(p.x-ox,p.y-oy);p.moving=moved>.02;if(p.moving){const oldStep=Math.floor(p.walk/49);p.walk+=moved;if(Math.floor(p.walk/49)!==oldStep&&p.action!=='roll')this.emit('sound',{name:'step'});if(p.action==='idle')p.action='walk';}else if(p.action==='walk')p.action='idle';
  for(const e of this.enemies)this.updateEnemy(e,dt);
  for(const b of this.projectiles){b.life-=dt;const oldX=b.initialX??b.x;delete b.initialX;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<LANES.min-30||b.y>LANES.max+30)b.life=0;const hitX=x=>x>=Math.min(oldX,b.x)-22&&x<=Math.max(oldX,b.x)+22;
   if(b.enemy){if(hitX(p.x)&&Math.abs(b.y-p.y)<28){if(this.hurtPlayer(b.damage,b))b.life=0;}}else{for(const e of this.enemies)if(e.active&&e.hp>0&&!b.hits.includes(e.id)&&hitX(e.x)&&Math.abs(b.y-e.y)<35){b.hits.push(e.id);this.hitEnemy(e,b.damage,'shoot',b.face);if(b.hits.length>=b.pierce){b.life=0;break;}}if(b.life>0)for(const o of this.props)if(o.hp>0&&!b.hits.includes(o.id)&&hitX(o.x)&&Math.abs(b.y-o.y)<35){b.hits.push(o.id);this.hitProp(o,b.damage);if(b.hits.length>=b.pierce)b.life=0;}}
  }this.projectiles=this.projectiles.filter(b=>b.life>0);
  for(const item of this.pickups){if(p.hp>0&&Math.abs(p.x-item.x)<42&&Math.abs(p.y-item.y)<34){if(item.type==='health'){if(p.hp>=p.maxHP)continue;p.hp=Math.min(p.maxHP,p.hp+22);}else{if(p.reserve>=96)continue;p.reserve=Math.min(96,p.reserve+16);}item.collected=true;this.emit('float',{x:item.x,y:item.y,z:100,text:item.type==='health'?'+22 HP':'+16 AMMO',color:item.type==='health'?'#eec97f':'#8adaec'});this.emit('sound',{name:'pickup'});}}this.pickups=this.pickups.filter(i=>!i.collected);
  if(p.hp<=0)return;const current=this.areas[this.frontier];if(!current.cleared&&!this.enemies.some(e=>e.area===this.frontier&&e.hp>0)){current.cleared=true;this.score+=300;this.emit('notice',{text:'AREA CLEAR · MOVE RIGHT',duration:2.4});this.emit('sound',{name:'clear'});}if(current.cleared&&this.frontier<2&&p.x>(this.frontier+1)*AREA-280)this.activate(this.frontier+1);const a=clamp(Math.floor(p.x/AREA),0,2);if(a!==this.area){this.area=a;this.emit('area',{area:a});}if(this.areas.every(a=>a.cleared)&&p.x>3*AREA-75){this.score+=1000;this.projectiles=[];this.state=this.chapter===4?'win':'chapter';this.emit(this.state==='win'?'victory':'chapterComplete');}
 }
}
const api={Engine,THEMES,TYPES,AREA,LANES,clamp};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.RequiemCore=api;
})(typeof window!=='undefined'?window:this);
