(()=>{
'use strict';
const {Engine,THEMES,TYPES,AREA,clamp}=EldenCore, game=new Engine(), $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false}),images={},keys=new Set(),touchHeld=new Set();
const SAVE='elden-ring-beat-em-up-v1',MORE='https://g55.co/?utm_source=moreGamesButton&utm_medium='+encodeURIComponent(document.title);
document.querySelectorAll('.more').forEach(a=>a.href=MORE);
let W=innerWidth,H=innerHeight,DPR=1,scale=1,ground=0,camera=0,ready=false,muted=false,menuKind='main',helpOrigin='main',heroScene=true,hasRun=false,transitioning=false,clock=0,noticeTimer=0,hurtFlash=0,shake=0,lastTime=0,hudTick=0,joyX=0,joyY=0,joyPointer=null,audioContext=null,save=null;
const particles=[],floats=[],rings=[],actionQueue=[];
try{save=JSON.parse(localStorage.getItem(SAVE)||'null');if(!save||!Number.isInteger(save.chapter)||save.chapter<0||save.chapter>4)save=null;muted=localStorage.getItem(SAVE+'-mute')==='1';}catch{}
function persist(s){save=s;try{localStorage.setItem(SAVE,JSON.stringify(s));}catch{}}
function touchMode(){return matchMedia('(pointer:coarse)').matches||W<800;}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ground=H*(H>W?.59:.61);if(H<420)ground=H*.53;scale=Math.max(W/2600,(H-ground)/SCENERY.floorDepth,Math.min(H/700,W/560));ctx.setTransform(DPR,0,0,DPR,0,0);clearInput();syncVisibility();}
function clearInput(){keys.clear();touchHeld.clear();actionQueue.length=0;joyX=joyY=0;joyPointer=null;$('stick').style.transform='';document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
function sound(name){if(muted)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const settings={swing:[190,.13,'triangle'],hit:[78,.11,'square'],hurt:[65,.2,'sawtooth'],roll:[140,.1,'sine'],spell:[590,.32,'sine'],enemy:[110,.17,'triangle'],flask:[640,.35,'sine'],pickup:[790,.18,'sine'],clear:[430,.5,'sine'],break:[98,.2,'sawtooth']},[f,d,type]=settings[name]||settings.hit,o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(name==='clear'?860:Math.max(35,f*.45),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.045,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+d+.02);}catch{}}
function updateMute(){ $('mute').textContent=muted?'♪':'♫';$('mute').setAttribute('aria-label',muted?'Unmute sound':'Mute sound');$('mute').title=muted?'Sound off (M)':'Sound on (M)';}
function toggleMute(){muted=!muted;try{localStorage.setItem(SAVE+'-mute',String(+muted));}catch{}updateMute();if(!muted)sound('pickup');}
function toggleFullscreen(){if(document.fullscreenElement){document.exitFullscreen?.().catch(()=>{});}else if(document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().catch(()=>{notice('Fullscreen is unavailable here',2);});}else notice('Use your browser’s fullscreen controls',2);}
function notice(text,time=2.5){$('notice').textContent=text;noticeTimer=time;$('notice').style.opacity='1';}
game.onEvent=e=>{if(e.type==='sound')sound(e.name);else if(e.type==='checkpoint')persist(e.save);else if(e.type==='notice')notice(e.text,e.duration);else if(e.type==='hint')notice(e.text,1.1);else if(e.type==='float')floats.push({...e,life:1,ttl:1});else if(e.type==='impact'){for(let i=0;i<e.count;i++)particles.push({...e,vx:(Math.random()-.5)*170,vy:(Math.random()-.5)*100,vz:70+Math.random()*80,life:.3+Math.random()*.23});}else if(e.type==='hurt'){hurtFlash=.2;shake=4;}else if(e.type==='shake')shake=Math.max(shake,e.amount);else if(e.type==='slam'){rings.push({...e,life:.45,ttl:.45,r:175,color:'#e7af61'});shake=5;}else if(e.type==='heal'){rings.push({x:game.player.x,y:game.player.y,life:.65,ttl:.65,r:55,color:'#e5c978'});}else if(e.type==='slash'){rings.push({...e,life:.12,ttl:.12,r:e.heavy?118:75,color:'#e7d4a0',slash:true});}else if(['defeat','victory','chapterComplete'].includes(e.type))showMenu(e.type==='defeat'?'dead':e.type==='victory'?'win':'chapter');else if(e.type==='area')notice(THEMES[game.chapter].areas[e.area],1.6);};
function syncVisibility(){const playing=menuKind===null;$('hud').hidden=!playing;$('pause').hidden=!playing;$('touch').hidden=!playing||!touchMode();$('keyboard-guide').hidden=!playing||touchMode();$('branding').hidden=playing;$('menu').hidden=playing;$('shade').hidden=playing;$('shade').classList.toggle('ingame',!heroScene);if(!playing){$('boss-hud').hidden=true;$('combo').hidden=true;$('notice').style.opacity=0;}}
function showMenu(kind){menuKind=kind;clearInput();$('main-panel').hidden=kind!=='main';$('other-panel').hidden=kind==='main';$('other-panel').classList.toggle('help-panel',kind==='help');
 if(kind==='main'){heroScene=true;$('continue').hidden=!save&&!hasRun;$('continue').textContent=hasRun?'Continue journey':save?'Continue · Chapter '+(save.chapter+1):'Continue journey';$('footer-left').textContent='FIVE CHAPTERS · ONE THRONE';}
 else{heroScene=kind==='help'?helpOrigin==='main':false;const p=game.player,t=THEMES[game.chapter];$('other-help').hidden=kind==='help';$('main-menu').hidden=kind==='help'&&helpOrigin==='main';let kicker,title,body,label,action;
  if(kind==='help'){kicker='THE WAY OF THE TARNISHED';title='How to play';body='<dl class="controls"><dt>WASD / Arrows</dt><dd>Move</dd><dt>J</dt><dd>Three-hit sword combo</dd><dt>K</dt><dd>Staggering heavy strike</dd><dt>L</dt><dd>Glintstone magic</dd><dt>Space / Shift</dt><dd>Evasive dodge</dd><dt>R</dt><dd>Healing flask (3)</dd></dl><p>Gold rings warn of attacks. Dodge before impact. Stamina and focus recover over time.</p><p>Break supplies, defeat all foes, then follow grace right. Cleared routes stay open.</p>';label='BACK';action=()=>showMenu(helpOrigin);}
  else if(kind==='pause'){kicker='A MOMENT OF RESPITE';title='Journey paused';body='<p>'+t.name+'<br>'+t.areas[game.area]+'</p><p>Your journey will resume here.</p>';label='RESUME JOURNEY';action=resume;}
  else if(kind==='dead'){kicker='GRACE STILL GUIDES YOU';title='You Died';body='<p>The journey does not end here.</p><p>Return to the beginning of '+t.name+' with your flasks and strength restored.</p>';label='RETRY CHAPTER';action=()=>handoff(()=>game.retry());}
  else if(kind==='chapter'){kicker='CHAPTER '+String(game.chapter+1).padStart(2,'0')+' COMPLETE';title='Grace restored';body='<p>'+t.name+' lies behind you.</p><p>Next: <strong>'+THEMES[game.chapter+1].name+'</strong><br>Health, focus and flasks will be replenished.<br>Your sword and magic grow stronger.</p><div class="stats"><div>RUNES<span>'+game.score.toLocaleString()+'</span></div><div>BEST COMBO<span>'+game.maxCombo+'</span></div></div>';label='CONTINUE JOURNEY';action=()=>handoff(()=>game.nextChapter());}
  else{kicker='THE ELDEN THRONE IS YOURS';title='Elden Lord';body='<p>You followed the grace through all five chapters and defeated the Omen King.</p><div class="stats"><div>RUNES<span>'+game.score.toLocaleString()+'</span></div><div>FOES FELLED<span>'+game.kills+'</span></div><div>BEST COMBO<span>'+game.maxCombo+'</span></div></div>';label='JOURNEY AGAIN';action=()=>handoff(()=>game.start());}
  $('menu-kicker').textContent=kicker;$('menu-title').textContent=title;$('menu-body').innerHTML=body;$('primary').textContent=label+'   →';$('primary').onclick=action;$('footer-left').textContent=kind==='help'?'KEYBOARD OR ON-SCREEN TOUCH CONTROLS':t.name.toUpperCase();
 }syncVisibility();}
function resume(){game.resume();menuKind=null;heroScene=false;syncVisibility();canvas.focus();}
function pause(){if(transitioning)return;if(menuKind===null&&game.pause())showMenu('pause');else if(menuKind==='pause')resume();}
function handoff(action){if(!ready||transitioning)return;transitioning=true;clearInput();$('transition').classList.add('active');setTimeout(()=>{action();hasRun=true;camera=0;particles.length=floats.length=rings.length=0;menuKind=null;heroScene=false;syncVisibility();setTimeout(()=>{$('transition').classList.remove('active');transitioning=false;canvas.focus();},70);},420);}
$('start').onclick=()=>handoff(()=>game.start());$('continue').onclick=()=>{if(hasRun&&game.state==='paused')resume();else if(hasRun&&game.state==='chapter')showMenu('chapter');else if(hasRun&&game.state==='dead')showMenu('dead');else if(hasRun&&game.state==='win')showMenu('win');else handoff(()=>game.start(save));};$('help').onclick=()=>{helpOrigin='main';showMenu('help');};$('other-help').onclick=()=>{helpOrigin=menuKind;showMenu('help');};$('main-menu').onclick=()=>{game.pause();showMenu('main');};$('pause').onclick=pause;$('mute').onclick=toggleMute;$('fullscreen').onclick=toggleFullscreen;
const keyActions={KeyJ:'attack',KeyK:'heavy',KeyL:'spell',Space:'roll',ShiftLeft:'roll',ShiftRight:'roll',KeyR:'flask'};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){if(menuKind==='help')showMenu(helpOrigin);else pause();return;}if(e.code==='KeyM'){toggleMute();return;}if(e.code==='KeyF'){toggleFullscreen();return;}if(menuKind!==null||transitioning)return;keys.add(e.code);if(keyActions[e.code])actionQueue.push(keyActions[e.code]);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{clearInput();if(menuKind===null&&game.pause())showMenu('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(menuKind===null&&game.pause())showMenu('pause');}});
const joystick=$('joystick');function joy(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.32,l=Math.max(max,Math.hypot(dx,dy));joyX=dx/l;joyY=dy/l;if(Math.hypot(joyX,joyY)<.12)joyX=joyY=0;$('stick').style.transform='translate('+joyX*max+'px,'+joyY*max+'px)';}joystick.addEventListener('pointerdown',e=>{if(joyPointer!==null)return;joyPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);joy(e);e.preventDefault();});joystick.addEventListener('pointermove',e=>{if(joyPointer===e.pointerId)joy(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(type,e=>{if(e.pointerId===joyPointer){joyPointer=null;joyX=joyY=0;$('stick').style.transform='';}});
document.querySelectorAll('[data-action]').forEach(b=>{const action=b.dataset.action;b.addEventListener('pointerdown',e=>{if(transitioning||menuKind!==null)return;b.setPointerCapture(e.pointerId);touchHeld.add(action);actionQueue.push(action);b.classList.add('pressed');e.preventDefault();});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>{touchHeld.delete(action);b.classList.remove('pressed');});});
function input(){return{x:clamp((keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joyX,-1,1),y:clamp((keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joyY,-1,1),attack:keys.has('KeyJ')||touchHeld.has('attack'),heavy:keys.has('KeyK')||touchHeld.has('heavy'),actions:actionQueue.splice(0)};}
function panorama(id,key,ch,cam,s){const im=images[id];if(!im)return;const width=SCENERY.widths[key],height=width*im.height/im.width,parallax=SCENERY.parallax[key],view=W/s,travel=Math.max(0,3*AREA-view),origin=(view+travel*parallax-width)/2,x=(origin-cam*parallax)*s,y=key==='floor'?ground-1:ground-height*s;ctx.drawImage(im,x,y,width*s,height*s+(key==='floor'?2:1));if(key==='far'&&y>0){const sky=SCENERY.skyColors[THEMES[ch].id],fade=ctx.createLinearGradient(0,y,0,y+36*s);fade.addColorStop(0,sky);fade.addColorStop(1,sky+'00');ctx.fillStyle=fade;ctx.fillRect(0,y,W,36*s);}}
function environment(ch,cam,s=scale){const t=THEMES[ch];s=Math.max(s,W/2600,(H-ground)/SCENERY.floorDepth);ctx.fillStyle=SCENERY.skyColors[t.id]||t.colors[0];ctx.fillRect(0,0,W,H);for(const key of ['far','mid','near','floor'])panorama(t.id+'-'+key,key,ch,cam,s);}
function sprite(id,frame,x,y,height,face=1,alpha=1){const im=images[id],a=ART[id];if(!im||!a)return;const s=height/a.body;ctx.save();ctx.translate(x,y);ctx.scale(face*s,s);ctx.globalAlpha=alpha;ctx.drawImage(im,(frame%a.cols)*a.cw,Math.floor(frame/a.cols)*a.ch,a.cw,a.ch,-a.anchorX,-a.anchorY,a.cw,a.ch);ctx.restore();}
function shadow(x,y,rx,ry,a=.3){ctx.fillStyle='rgba(3,8,6,'+a+')';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function screen(o){return{x:(o.x-camera)*scale,y:ground+o.y*scale};}
function actorFrame(a,hero=false){if(a.action==='dead')return hero?8:5;if(a.action==='hurt')return hero?6:4;if(hero){if(a.action==='roll')return 7;if(a.action==='spell'||a.action==='flask')return 5;if(a.action==='heavy')return 4;if(a.action==='attack')return a.comboStep===3?4:3;}else if(a.action==='attack')return 3;if(a.moving)return 1+Math.floor(a.walk/35)%2;return 0;}
function drawText(text,x,y,size,color='#f1deb0',align='center'){ctx.font=size+'px Grace, Georgia, serif';ctx.textAlign=align;ctx.lineWidth=3;ctx.strokeStyle='#07100ede';ctx.strokeText(text,x,y);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function imageSprite(id,x,y,w,face=1,alpha=1){const im=images[id];if(!im)return;const h=w*im.height/im.width;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore();}
function renderHero(){const menuScale=Math.min(H/710,W/1000),cam=90+Math.sin(clock*.075)*55;environment(0,cam,Math.max(.65,menuScale));const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#05171740');g.addColorStop(.6,'#05171700');g.addColorStop(1,'#03101190');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let heroH=Math.min(H*.58,W*.36),hx=W*.70,hy=H*.87;if(W<650&&H>W){heroH=H*.32;hx=W*.69;hy=H*.94;}if(W>=850){const ex=W*.92,eh=heroH*.91;shadow(ex,hy-6,eh*.21,eh*.045);sprite('omen',0,ex,hy-6,eh,-1);}shadow(hx,hy,heroH*.22,heroH*.05);sprite('tarnished',0,hx,hy,heroH,-1);for(let i=0;i<24;i++){const x=(i*193+Math.sin(clock*.1+i)*22)%W,y=(H-(clock*9+i*67)%(H+50));ctx.globalAlpha=.12+(i%4)*.07;ctx.fillStyle='#f2cf69';ctx.fillRect(x,y,2,2);}ctx.globalAlpha=1;}
function renderLevel(){const t=THEMES[game.chapter];environment(game.chapter,camera);const allClear=game.areas.length&&game.areas.every(a=>a.cleared);
 for(const e of game.enemies){if(e.active&&e.hp>0&&e.action==='windup'){const {x,y}=screen(e),progress=1-e.timer/e.duration;ctx.strokeStyle='#f9bd6ccc';ctx.fillStyle='rgba(211,126,50,'+(.06+progress*.13)+')';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(x+(e.kind==='slam'?0:e.face*30*scale),y,(e.kind==='slam'?172:60)*scale,(e.kind==='slam'?78:25)*scale,0,0,Math.PI*2);ctx.fill();ctx.stroke();drawText('!',x,y-e.height*scale-13,20*scale,'#ffd685');}}
 const entities=[...game.props.map(o=>({...o,renderType:'prop'})),...game.enemies.map(e=>({...e,renderType:'enemy'})),{...game.player,renderType:'player'}].sort((a,b)=>a.y-b.y||(a.renderType==='player'?1:-1));
 for(const item of game.pickups){const {x,y}=screen(item);shadow(x,y,13*scale,4*scale,.2);ctx.save();ctx.globalAlpha=.5;ctx.fillStyle=item.type==='health'?'#f5bd68':'#85dceb';ctx.beginPath();ctx.ellipse(x,y-10*scale,11*scale,15*scale,0,0,Math.PI*2);ctx.fill();ctx.restore();imageSprite('grace',x,y-13*scale,17*scale);}
 for(const o of entities){const {x,y}=screen(o);if(x<-300*scale||x>W+300*scale)continue;if(o.renderType==='prop'){shadow(x,y,28*scale,8*scale,.24);sprite(t.id+'-prop',o.state,x,y,t.propHeight*scale);continue;}const hero=o.renderType==='player',height=(hero?150:o.height)*scale;if(!hero&&o.hp<=0&&o.deadTime>6)continue;const alpha=!hero&&o.hp<=0?clamp(1-(o.deadTime-3)/3,0,1):1;shadow(x,y,height*.22,height*.043,alpha*.32);sprite(hero?'tarnished':o.type,actorFrame(o,hero),x,y,height,o.face,alpha);if(hero&&o.invuln>0){ctx.strokeStyle='#e8db9a88';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(x,y,31*scale,10*scale,0,0,Math.PI*2);ctx.stroke();}if(!hero&&o.active&&o.hp>0&&o.hp<o.maxHP&&!o.boss){ctx.fillStyle='#10191ee0';ctx.fillRect(x-25*scale,y-height-10*scale,50*scale,4*scale);ctx.fillStyle='#ba695a';ctx.fillRect(x-25*scale,y-height-10*scale,50*scale*o.hp/o.maxHP,4*scale);}}
 for(const b of game.projectiles){const {x,y}=screen(b);imageSprite('glintstone',x,y-b.z*scale,(b.enemy?70:83)*scale,b.face);}
 for(const a of game.areas.map((v,i)=>({...v,i}))){if(!a.cleared)continue;const x=((a.i+1)*AREA-86-camera)*scale;if(x<-60||x>W+60)continue;imageSprite('grace',x,ground+112*scale,43*scale,1,.86+Math.sin(clock*3)*.12);if(game.player.x>(a.i+1)*AREA-440)drawText(a.i===2?'GRACE →':'→',x,ground+49*scale,15*scale,'#e8ce85');}
 if(!allClear&&game.player.x>game.upper-180){const x=(game.upper-camera)*scale;drawText('Defeat the remaining foes',x-10*scale,ground+20*scale,11*scale,'#ddc58e','right');}
 for(const r of rings){const {x,y}=screen(r),p=1-r.life/r.ttl;ctx.strokeStyle=r.color;ctx.globalAlpha=clamp(r.life/r.ttl,0,1)*.7;ctx.lineWidth=r.slash?3*scale:2;ctx.beginPath();if(r.slash){ctx.arc(x,y-r.z*scale,r.r*scale*.6,-1.1+(r.face<0?Math.PI:0),1.1+(r.face<0?Math.PI:0));}else ctx.ellipse(x,y,r.r*scale*(.3+p*.7),r.r*scale*.3*(.3+p*.7),0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
 for(const q of particles){const {x,y}=screen(q);ctx.globalAlpha=Math.min(1,q.life*3);ctx.fillStyle=q.color;ctx.fillRect(x,y-q.z*scale,3*scale,3*scale);}ctx.globalAlpha=1;
 for(const q of floats){const {x,y}=screen(q);ctx.globalAlpha=Math.min(1,q.life*2);drawText(q.text,x,y-q.z*scale,13*scale,q.color);}ctx.globalAlpha=1;
 if(hurtFlash>0){ctx.fillStyle='rgba(130,25,21,'+hurtFlash*.55+')';ctx.fillRect(0,0,W,H);}const vignette=ctx.createLinearGradient(0,0,0,H);vignette.addColorStop(0,'#051010a6');vignette.addColorStop(.21,'#03100b00');vignette.addColorStop(.82,'#03100b00');vignette.addColorStop(1,'#020c1066');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);
}
function updateHUD(){const p=game.player,t=THEMES[game.chapter];$('hp-text').textContent=Math.ceil(p.hp)+' / '+p.maxHP;$('hp-bar').style.width=p.hp/p.maxHP*100+'%';$('fp-bar').style.width=p.focus+'%';$('stamina-bar').style.width=p.stamina+'%';$('flask-text').textContent='FLASKS '+p.flasks;$('fp-text').textContent='FP '+Math.floor(p.focus);$('chapter-text').textContent='CHAPTER '+String(game.chapter+1).padStart(2,'0')+' / 05 · AREA '+String(game.area+1).padStart(2,'0')+' / 03';$('area-text').textContent=t.areas[game.area];$('threat-text').textContent=game.remaining?game.remaining+' FOES REMAINING':'FOLLOW THE GRACE →';$('score-text').textContent=String(game.score).padStart(6,'0');$('combo').hidden=game.combo<3;$('combo').textContent=game.combo+' HITS';const b=game.boss;$('boss-hud').hidden=!b;if(b){$('boss-name').textContent=t.boss;$('boss-value').textContent=b.hp+' / '+b.maxHP;$('boss-bar').style.width=b.hp/b.maxHP*100+'%';}}
function frame(ts){const dt=Math.min(.04,(ts-lastTime)/1000||.016);lastTime=ts;clock+=dt;if(menuKind===null&&!transitioning){game.step(dt,input());const worldView=W/scale,target=clamp(game.player.x-worldView*.42,0,Math.max(0,3*AREA-worldView));camera+=(target-camera)*(1-Math.exp(-dt*7));for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vz-=440*dt;p.life-=dt;}for(const f of floats){f.life-=dt;f.z+=28*dt;}for(const r of rings)r.life-=dt;for(const a of [particles,floats,rings])for(let i=a.length-1;i>=0;i--)if(a[i].life<=0)a.splice(i,1);hurtFlash=Math.max(0,hurtFlash-dt);shake=Math.max(0,shake-dt*15);noticeTimer-=dt;$('notice').style.opacity=menuKind===null&&noticeTimer>0?'1':'0';hudTick-=dt;if(hudTick<=0&&menuKind===null){updateHUD();hudTick=.08;}}
 ctx.setTransform(DPR,0,0,DPR,0,0);ctx.imageSmoothingEnabled=true;ctx.save();if(shake>0&&menuKind===null)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);if(heroScene)renderHero();else renderLevel();ctx.restore();requestAnimationFrame(frame);}
async function load(){const ids=[...Object.keys(ART),'glintstone','grace',...THEMES.flatMap(t=>['far','mid','near','floor'].map(k=>t.id+'-'+k))];let count=0,failed=[];ready=false;$('start').disabled=true;await Promise.all(ids.map(id=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images[id]=im;count++;$('start-label').textContent='LOADING '+Math.round(count/ids.length*100)+'%';$('loading-bar').style.width=count/ids.length*100+'%';resolve();};im.onerror=()=>{failed.push(id);resolve();};im.src='assets/'+id+'.png';})));await document.fonts.ready;if(failed.length){$('start').disabled=false;$('start-label').textContent='RETRY LOADING';$('start').onclick=load;notice('Some artwork could not load. Select Retry Loading.',20);return;}ready=true;$('start').disabled=false;$('start-label').textContent='START GAME';$('loading-bar').style.width='0';$('start').onclick=()=>handoff(()=>game.start());}
addEventListener('resize',resize);document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');resize();});showMenu('main');updateMute();resize();requestAnimationFrame(frame);load();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_game_state',description:'Read the current Elden Ring beat em up status, chapter, health and remaining foes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({state:game.state,menu:menuKind,chapter:THEMES[game.chapter].name,health:game.player.hp,remainingFoes:game.remaining})});register({name:'set_game_paused',description:'Pause or resume the current active game using the same controls as the Pause and Resume buttons.',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input.paused!=='boolean'||Object.keys(input).some(k=>k!=='paused'))throw new Error('paused must be a boolean');if(transitioning)throw new Error('Wait for the chapter transition');if(input.paused&&game.state==='play')pause();else if(!input.paused&&menuKind==='pause')resume();else throw new Error('There is no matching active game to pause or resume');return{state:game.state,paused:game.state==='paused'};}});addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
